### ISSUE TITLE
Ability to not repeat the first line in the dropdown

### ISSUE THREAD

**Issue by manojlds** [matryer/bitbar#102]
If I am not mistaken, currently, the text in the menu bar is repeated as the first in the dropdown too. It would be great if we can turn this on or off as needed. Thoughts?

**Comment by jcaille** [comment]
Coming in #48, i've added a `refresh` keyword that I usually assign to the first line : Clicking the name of the plugin refreshes it.

An option for plugins that don't need this behaviour would be nice. What do you think of something such as `statusBarOnly` which displays it in the status bar rotation, but never in the dropdown ?

**Comment by manojlds** [comment]
@jcaille yeah something like that sounds good.

**Comment by matryer** [comment]
Can we live with it the way it is for a while before deciding if we need this option or not?

**Comment by jcaille** [comment]
Oops, did not see your comment.
I've gone ahead and created a PR for this feature :)
