### ISSUE TITLE
Better plugin management

### ISSUE THREAD

**Issue by jcaille** [matryer/bitbar#103]
The plugin discovery strategy is pretty simple today : "Execute everything that's in the plugin folder". As much as I love the straightforwardness of this, I feel that this has some drawbacks 

* First launch experience is not very clear (select which folder ?)
* Installing, removing and updating plugins is difficult (copy or symlink to the plugin folder)
* Having helper scripts right by your plugins is impossible (they should be put in a different folder)

One of the proposed solution in the discussion of PR #53 would be to symlink installed scripts to the plugin folder, but this adds another layer to installing / removing plugins.

Drawing from this, Bitbar could managed installed plugins by itself. For example :
* By defaults, Bitbar looks for plugins in an `ApplicationData/Bitbar/Plugins` folder. This folder can be changed.
* Drag and dropping a script on the Bitbar status menu item symlinks this file to the plugin folder (thus "installing" it in Bitbar)
* Additional options (`Remove plugin`, `Set refresh time`, ...) should be added to the plugin dropdown. Those options either remove or modify the name of the symlinked executable file (thus keeping the legacy API)

This might be a bit overkill, but I'd be willing to give it a try and implement it.
I believe this might make it easier to distribute Bitbar as well as plugins and improve the user experience by just having user drag and drop plugins instead of having to manage the plugin folder.

**Comment by matryer** [comment]
I think BitBar should let you add and remove plugins through an interface ultimately. But right now, it's a dev tool because of dev-ish dependencies and the like. Maybe save this for BitBar 2? :)

**Comment by matryer** [comment]
please move discussion to https://github.com/matryer/bitbar/issues/112
