### ISSUE TITLE
clang: error: no such file or directory: '/App/Vendor/STPrivilegedTask/STPrivilegedTask.m'

### ISSUE THREAD

**Issue by m99coder** [matryer/bitbar#104]
Hi Mat,

first of all: Great Application.

I wanted to build out of current master because the release included in your repository is quite old and probably not containing the last bugfixes. XCode Version 7.2 (7C68) complains about not finding `STPrivilegedTask.m`. I already tried `git submodule update --remote --merge`.

![bitbar-xcode-build](https://cloud.githubusercontent.com/assets/3276992/12139475/0de2a702-b461-11e5-9c84-d918965c5ad7.png)

Thanks for any advice.
Marco

**Comment by LaurentFough** [comment]
Getting the same error.
- different actions though: using Cocoapods to add in the Sparkle framework.

Pod is setup and and install properly... error on build, same as mentioned by @m99coder .

**Comment by matryer** [comment]
I have no idea I’m afraid, it’s working for me.

Maybe try cloning the repo again!?

**Comment by m99coder** [comment]
All the `Vendor` folders are empty. How are they filled? Automatically by XCode build?

**Comment by matryer** [comment]
They're linked repos - see https://github.com/matryer/bitbar/tree/master/App/Vendor

Try this:

```
git submodule update --remote --merge
```

**Comment by matryer** [comment]
p.s. once we figure this out, we'll add some notes to "Contributing"

**Comment by m99coder** [comment]
The correct command is `git submodule init && git submodule update` in the root folder (same folder as `.gitmodules` file). After this it works like a charm.

**Comment by matryer** [comment]
We need to make sure this is clear for people wishing to contribute. What’s the best way to do that?

**Comment by m99coder** [comment]
I would recommend to add notes to `README.md` as you suggested. Without `git submodule init` it won’t work. You have to execute it once. Afterwards `git submodule update` is fair enough to do the job.

**Comment by LaurentFough** [comment]
Works (builds fine) for me here.
- with: `git submodule init && git submodule update`
