### ISSUE TITLE
Cannot "Change Plugin Folder"

### ISSUE THREAD

**Issue by oalders** [matryer/bitbar#116]
When I use the "Change Plugin Folder" menu item, it allows me to choose a new folder via the Finder.  After I do this I get a message that no plugins are found.  (There is, however, one plugin in the folder I'm choosing).  When I then choose "Open Plugin Folder" the Finder opens to my "Documents" folder, rather than the folder I'd previously chosen for my plugins.

This is v1.2 installed via `homebrew`.  OS is 10.11.2

**Comment by matryer** [comment]
`v1.2` is pretty old - going to release `1.4` v soon.

**Comment by matryer** [comment]
Or you can build from source?

**Comment by oalders** [comment]
I'll try building from source now. :)

**Comment by matryer** [comment]
Or you can try the 1.4 beta release: https://github.com/matryer/bitbar/releases/tag/v1.4.0-beta

**Comment by oalders** [comment]
Hmmm...  After downloading the 1.4 release I get this:

<img width="1275" alt="screenshot 2016-01-06 10 05 51" src="https://cloud.githubusercontent.com/assets/96205/12145589/217ca168-b45d-11e5-8329-be30a097724a.png">
<img width="282" alt="screenshot 2016-01-06 10 06 48" src="https://cloud.githubusercontent.com/assets/96205/12145615/44837bd2-b45d-11e5-8d13-011076247a38.png">

**Comment by oalders** [comment]
If I choose "Run in Terminal..." it just tries to exec a document from my `Documents` folder.

**Comment by matryer** [comment]
Can you try clearing your defaults:

**Comment by matryer** [comment]
with this: https://github.com/matryer/bitbar#resetting-plugin-directory

**Comment by oalders** [comment]
That didn't seem to change anything.  I had tried that as well on the older release before opening this ticket.  Is there a config file I can edit manually?

**Comment by matryer** [comment]
So here's a weird thing... you have to go INSIDE the folder, not just select it. Try that and let me know.

**Comment by oalders** [comment]
:fireworks: 

Thank you!!!

**Comment by oalders** [comment]
BTW, thanks for your work on this.  I've got the Spotify plugin working now.  Very nice. :)

**Comment by matryer** [comment]
Great, thanks.

I’m going to add an issue to allow it to use the selected item, rather than where you’re contained.

**Comment by matryer** [comment]
https://github.com/matryer/bitbar/issues/120

**Comment by oalders** [comment]
:+1:
