### ISSUE TITLE
v1.3.1 Bitbar app not saving plugin folder

### ISSUE THREAD

**Issue by NicholasMurray** [matryer/bitbar#122]
The Bitbar app does not seem to be saving the plugin folder and no plugins are subsequently found.

![screen shot 2016-01-06 at 16 07 53](https://cloud.githubusercontent.com/assets/1111211/12147308/2a39ecec-b490-11e5-9641-13cd601f452a.png)
![screen shot 2016-01-06 at 16 09 14](https://cloud.githubusercontent.com/assets/1111211/12147317/337fbae8-b490-11e5-87ec-f898f5985d8e.png)

**Comment by matryer** [comment]
Please install [v1.4beta](https://github.com/matryer/bitbar/releases) and let me know if this still happens?

**Comment by NicholasMurray** [comment]
Hmmm, not sure whats going wrong now, its not prompting me for a folder and it does this...

![screen shot 2016-01-06 at 19 52 02](https://cloud.githubusercontent.com/assets/1111211/12152987/67338b84-b4af-11e5-926d-4aa392e61bae.png)

![screen shot 2016-01-06 at 19 55 25](https://cloud.githubusercontent.com/assets/1111211/12153020/8e4d08c6-b4af-11e5-9aae-0dd9d9e2a33d.png)

**Comment by matryer** [comment]
In “Preferences…” you have the option to select a plugin folder. Be sure to go INSIDE the folder (i.e. don’t just select it) and it’ll work.

This is fixed in master and will go into the next release.

**Comment by NicholasMurray** [comment]
Ah yes, its working now, double clicking the folder worked, thanks!! Great little app BTW.
