### ISSUE TITLE
1.4 beta doesn't use monospace digits in the default font anymore

### ISSUE THREAD

**Issue by thomasbachem** [matryer/bitbar#123]
I'm relying on monospaced digits (meaning that all digits have the same width) in my custom stocks plugin. This is typical a font feature.

1.3.1 and 1.4beta use exactly the same font on OS X 10.11.1 El Capitan (the San Francisco system font), but while 1.3.1 uses monospaced digits, 1.4beta doesn't anymore. See screenshots:

1.3.1:
![bitbar-1-3](https://cloud.githubusercontent.com/assets/231538/12147808/1ffce4cc-b49b-11e5-87e1-16167e375ddd.png)

1.4beta:
![bitbar-1-4](https://cloud.githubusercontent.com/assets/231538/12147810/2143a834-b49b-11e5-8336-f7c1a61a6c64.png)

I think monospaced digits are always preferable for BitBar use cases.

This may help to resolve it:
* [Thread in Apple Developer Forums](https://forums.developer.apple.com/thread/6738)
* [Threat at StackOverflow](http://stackoverflow.com/questions/21569861)

**Comment by matryer** [comment]
Thanks for the report. I might be mad, but I can't see a difference between those two images. If you have some time, it would be great if you could solve this problem since you seem to understand it so well? If not, leave it and we'll get around to it.

**Comment by thomasbachem** [comment]
Look at the "1" in "-1,31%" and compare it to the "0" from "-0,69%" (in the line below). They have different widths in the second screenshot, but not in the first.

I'll have a look at the code but am not experienced with Xcode.

**Comment by thomasbachem** [comment]
I think we need this: http://stackoverflow.com/a/33983421 somewhere here: https://github.com/matryer/bitbar/blob/master/App/BitBar/Plugin.m#L60

**Comment by matryer** [comment]
OK leave it with us - thanks

**Comment by keithamus** [comment]
Over in #137 there is some discussion about being able to change colour inline. This could be somewhat of a duplicate - because I think some text would benefit from proportional over monospaced, and obviously vice-versa.

In #137 the two emerging solutions are either XML or ANSI Escape codes. Both would support changing the fonts. [ANSI Codes support up to 9 alternative fonts](https://en.wikipedia.org/wiki/ANSI_escape_code). An example of how to render them:

```bash
MONOSPACE='\033[0;19m' # this is just an example, `19m` can be `11m` to `19m`
RESET='\033[0m'
echo -e "This is normal font.... ${MONOSPACE}This is monospace font${RESET}"
```

Also, obviously, the same could be done for XML/HTML:

```html
<span>This is normal font.... <span style="font-family:monospace">This is monospace font</span></span>
```

```xml
<entry>This is normal font.... <font family="monospace">This is monospace font</font></entry>
```

**Comment by thomasbachem** [comment]
@keithamus Thanks, but please note that I'm just talking about monospaced DIGITS in a proportional font, not a monospaced font. I think monospaced digits are always preferable.

**Comment by thomasbachem** [comment]
Was quite easy to implement even for an Objective C newbie, see pull request #148 :)
