### ISSUE TITLE
Limit length of text shown [Spotify]

### ISSUE THREAD

**Issue by shopblocks** [matryer/bitbar#124]
Is it possible to get the name limited on this to the first say, 15 characters of the song then the artist name?

![image](https://cloud.githubusercontent.com/assets/14819903/12148285/8418229c-b495-11e5-9b9f-a26971b26b1f.png)

Otherwise stuff like this happens.

**Comment by matryer** [comment]
hahaha - good idea. Looks like it is possible: http://tldp.org/LDP/abs/html/string-manipulation.html

I'd love to start a bash Tips and Tricks page for stuff like this to help people make better plugins.

**Comment by matryer** [comment]
Do you think BitBar should enforce something?

**Comment by taylorzane** [comment]
I think that 20 characters looks a bit better. 20 characters is approximately the width of the menu bar (when no text expands it beyond the initial width).

We could have a default clipping length, and then allow users to make an exception with a `length` attribute, where any value of `length` that is less than 0 removes the limit.

```bash
echo "some really long text goes here and I need to see all of it | length=100"
||
echo "some really long text... | length=-1"
```

**Comment by johngibb** [comment]
Why not just truncate in your shell script?

    $ echo "this is a long string" | cut -c1-10
    this is a 

#124

**Comment by taylorzane** [comment]
I was using it more in a sense of preventing a naïve runaway string. Most people aren't expecting a string to be 100+ characters when they open up a menu bar. While I was at it I figured I'd implement the length param to allow people to specify the length of their line language-independently.

**Comment by matryer** [comment]
I saw this get fixed recently. Closing.
