### ISSUE TITLE
In dropped down state, menu bar item color should be switched to white

### ISSUE THREAD

**Issue by thomasbachem** [matryer/bitbar#127]
When using a color for the menu bar item itself, it looks bad when the dropdown is open, since most colors don't go well with the blue selection color.

Example:

Without dropdown:
![bitbar-color](https://cloud.githubusercontent.com/assets/231538/12150205/c1f93e12-b4a8-11e5-8486-580ee30caf64.png)

With dropdown opened:
![bitbar-active](https://cloud.githubusercontent.com/assets/231538/12150211/cc0c0eca-b4a8-11e5-983a-2b5b6cea5026.png)

We should consider to switch the color of selected menu bar items to white.

**Comment by thomasbachem** [comment]
PS: All other menu bar items I know switch to white when active.

**Comment by manojlds** [comment]
+1

**Comment by matryer** [comment]
Do you guys think the "Enhancement" label is enough to indicate that we want people to work on it?

**Comment by thomasbachem** [comment]
Perhaps an "Accepted" label makes sense?
