### ISSUE TITLE
Ability to have submenus

### ISSUE THREAD

**Issue by manojlds** [matryer/bitbar#135]
I would like to create submenus, so that we know that these menus go under a parent menu. Is this possible already? Simple way would be to have some indentation. Suggestions please?

**Comment by jcaille** [comment]
Something was started in #28 (using `json` to describe the structure of the menu)
IMHO, It is a bit more verbose, but makes it easy to parse and understand.

**Comment by manojlds** [comment]
@jcaille +1 to something like that.

**Comment by matryer** [comment]
I wonder if using indentation (two spaces) might be simpler?

```
Places
  London
  Paris
  Tokyo
Fruit
  Apple
  Orange
  Melon
    Watermelon
    Honeydew
```

**Comment by jcaille** [comment]
It might be simpler to write scripts using this method, but it seems to me like it would be more error prone when parsing (what happens if I use tab ? 4 spaces ? an odd number of spaces ?), and would prevent using spaces to align monospaced text for example.

**Comment by matryer** [comment]
Dashes?

```
Main menu
--Sub menu
--Sub menu item two
----Sub, sub, menu item
```

**Comment by jcaille** [comment]
Problems would be similar (plus outputting negative numbers might pose problems)

Sorry for being a bit negative, I do agree that JSON might be too verbose and difficult to output from a simple shell script, but such an format will be easily expandable in the future for adding additional features  (e.g. cmd+click action, keyboard shortcuts, ...)

**Comment by matryer** [comment]
No this is a very healthy discussion.

I always like to resist complexity - so that’s why I want to avoid JSON for as long as possible… plus it will mean people are hand coding JSON, which will likely mean more mistakes and wasted time for contributors.

Double hyphen `--` is my favourite so far - and wouldn’t clash with negative numbers?

**Comment by jcaille** [comment]
Yep. We should definitively keep the existing syntax for simple scripts
Outputting JSON from shell is difficult, but writing it from `python`, `ruby` or most other language should not be too hard. There might be a format that lies in the middle.

For example, we could use a special lines (such as the separator `---`) to open or close a submenu (I would suggest either something similar, such as `vvv` and `^^^`, or a keyword `bitbar_submenu_open` and `bitbar_submenu_close`). 

On the other hand, this might not be easily legible when looking over a plugin script

**Comment by keithamus** [comment]
To join in on the bikeshed - perhaps having a set of two characters would be the most legible and easiest to parse:

```
Main menu
-> Sub menu
-> Sub menu item two
-> -> Sub menu, menu item
-> Sub menu item three
-> -> Sub menu, sub menu item
```

**Comment by JayBrown** [comment]
Indentation would be fine, in principle, and it works (spaces, tab), but it doesn't seem to function with href, bash and other options after the |

**Comment by walk-me-through-it** [comment]
+1 for the idea.
I definitely lack the coding experience to see what's wrong with @keithamus's idea, but it looks on the face of it readable and sensible to me.

**Comment by frakman1** [comment]
Hi everyone. 

I know this is a closed issue but I want to re-visit this and ask a question about submenus.

I just started using bitbar and absolutely love the concept and all the possibilities!

I have a giant excel spreadsheet that serves as a company directory that I wish to somehow import into a bitbar menu. I want to be able to drill down by First name and and reveal address, number etc via sub-menus from the menu bar. 

I can easily convert the Excel data into a json file using an online converter. I was hoping that I could somehow easily import this json file into bitbar script that would magically populate all the submenus. 

Does anyone have any ideas on how I can make this work or if something similar has been attempted already or if you have an alternate approach? I appreciate any input and guidance. 

The json file would be in this format:

 {
   "A": "Last Name",
   "B": "First Name",
   "C": "Preferred Name (if different from first name)",
   "D": "Group",
   "E": "Sub-Group",
   "F": "Contractor",
   "G": "NEW Floor",
   "H": "NEW \nCubicle/Office Number",
   "I": "Email Address",
   "J": "New Fuze Phone Number ",
   "K": "Internal Extension",
   "L": "Mobile Number "
 },
