### ISSUE TITLE
Ability to change color within a line

### ISSUE THREAD

**Issue by manojlds** [matryer/bitbar#137]
Something like:

```
Hello from | color="black" + bitbar | color="green"
```

kind of scenarios.

**Comment by matryer** [comment]
How does colour changing work in terminals? I think there are escaped sequences or something - might be worth investigating, as it would be nice if we could use an existing pattern.

**Comment by manojlds** [comment]
In shell script you do something like this:

```bash
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m'

echo -e "${YELLOW}This is in yellow!${NC}"
echo -e "${RED}This is in red!${NC}"
```

**Comment by matryer** [comment]
Seems like we should support that!?

**Comment by manojlds** [comment]
If we can support as is, great. Might complicate the implementation though. I guess these colors are recognized only by terminals, and translating into a native app maybe tough. Can you mark this as a feature, and let someone contribute via PR.

**Comment by matryer** [comment]
Maybe that's not the right implementation then - but something similar? People are pretty used to HTML these days so maybe something like this:

```
Status is <color=green>OK</>
Status is <color=yellow>WARN</>
Status is <color=red>ERROR</>
```

**Comment by manojlds** [comment]
Sounds good. 

Also, speaking of HTML, what do you think of frameworks like this - https://github.com/maxogden/menubar

**Comment by matryer** [comment]
There is something very nice about limiting plugins to text. It forces nice looking apps.

**Comment by alesf** [comment]
Nice. With XML-like structure an element could include most of the available parameters (color, size, font, link, ...).

**Comment by keithamus** [comment]
One of the benefits of using ANSI terminal colours (as @manojlds mentioned [here](https://github.com/matryer/bitbar/issues/137#issuecomment-169615924)) is that we can see what the colours will look like in the terminal window! They look a little hacky but can easily be abstracted away with a couple of simple functions from within the script.

Supporting XML/HTML - while extensible, belies the original simplicity of this app, IMO.

**Comment by matryer** [comment]
@keithamus makes a good point people :)

**Comment by matryer** [comment]
I like the idea that it looks/works the same in the Terminal and BitBar.

**Comment by manojlds** [comment]
@keithamus @matryer that will definitely be the best approach, and yeah I guess a fundamental principal of BitBar is fidelity with terminal output.

**Comment by thomasbachem** [comment]
I like the ANSI idea! We need a way to define colors either globally in a config file or per script then. And we should try to implement the ones for bold, italic, underlined and strike-through as well. Not sure whether we need to implement background colors. Reference: https://en.wikipedia.org/wiki/ANSI_escape_code
