### ISSUE TITLE
command not found 

### ISSUE THREAD

**Issue by Joel-Costamagna** [matryer/bitbar#140]
i'm trying to do my first script and i would like to use the istats utility to display the Cpu temperature.
i installed it with `sudo gem install istats` and it run perfectly on the terminal.
but when i use the script in the bitbar, it says `command not found: istats" . Is there a problem of rights to access the istats command ?

**Comment by manojlds** [comment]
Did you check the recommendation on `PATH` manipulation in the README?

**Comment by Joel-Costamagna** [comment]
sorry i didn't saw that it works now thanks :)
