### ISSUE TITLE
Text encoding

### ISSUE THREAD

**Issue by javray** [matryer/bitbar#141]
I have some spanish text, how can I show them?, I get something like this in the dropdown:

Bajo el m?\195?\161ximo de CPUs de 8 a 6

And the correct text would:

Bajo el máximo de CPUs de 8 a 6

I'm using bash.

Thanks,

**Comment by matryer** [comment]
I don't know the answer to that question - can you try it and let us know what it does?

**Comment by javray** [comment]
![captura de pantalla 2016-01-08 a las 10 12 00](https://cloud.githubusercontent.com/assets/454310/12194466/9c97802c-b5f0-11e5-8293-5b700a9f1e1d.png)

I have an script in bash that execute a svn log command. Commit message is in Spanish and has accents. I don´t know how to show it the correct way.

**Comment by matryer** [comment]
I don’t know either - this one is going to take some investigation.

**Comment by javray** [comment]
I have found the solution:

 export LANG="es_ES.UTF-8"

I put that first in the bash script and it works.

Thanks.

**Comment by matryer** [comment]
Oh great nice one - maybe you could submit a PR with that documented in the README.md?

**Comment by jtokoph** [comment]
The issue is that the language isn't being loaded via locales

I've added to my [clipboard plugin](https://github.com/matryer/bitbar-plugins/blob/674a86666f4ce7519009fe13a31b2105759145ac/System/clipboard-history.3s.sh#L11)

```bash
# Hack for language not being set properly and unicode support
export LANG="${LANG:-en_US.UTF-8}"
```

**Comment by matryer** [comment]
should this be a fix in BitBar itself?

**Comment by jtokoph** [comment]
It might be possible.

Get the user's current local string in an LC format with UTF-8:

```objective-c
NSLocale * currentLocale = [NSLocale currentLocale];
NSString * localeString = [NSString stringWithFormat:@"%@_%@.UTF-8", (NSString*)[currentLocale objectForKey:NSLocaleLanguageCode], (NSString*)[currentLocale objectForKey:NSLocaleCountryCode]];
NSLog(@"localeIdentifier: %@", localeString);
```
Outputs `localeIdentifier: en_US.UTF-8` for me.

Then you should be able to set that environment variable for the task with something like this:

```objective-c
NSMutableDictionary *env = [task environment];
[environment setObject:localeString
forKey:@"LC_ALL"];
```

Can't try this out right now since I'm not running Xcode on this machine.

**Comment by jtokoph** [comment]
Opened pull request #146 which works for me.

**Comment by robo-hamburger** [comment]
Hit a similar problem with python. Something like `#!/usr/bin/env PYTHONIOENCODING=UTF-8 /usr/local/bin/python3` seems to fix it.

**Comment by lukeaus** [comment]
If using python 2:

```
#!/usr/bin/env PYTHONIOENCODING=UTF-8 /usr/local/bin/python
# -*- coding: utf-8 -*-
print u'blah'
```
