### ISSUE TITLE
Passing command line parameters to program

### ISSUE THREAD

**Issue by konstantinkobs** [matryer/bitbar#142]
Let's think about a plugin, that tracks the price of a product on Amazon. The user should be allowed to pass the link to the program, so it can scrape the site and show the price in BitBar. Or we want to create a plugin, that shows whether an update is available in your favorite RSS feeds.

For these purposes, it would be nice to have the possibility to pass arguments to your program without changing its code.

**Comment by matryer** [comment]
Nice ideas, can you open an issue over at the [Plugins repo](https://github.com/matryer/bitbar-plugins)?
