### ISSUE TITLE
Ability to manually refresh from command  line.

### ISSUE THREAD

**Issue by Lugoues** [matryer/bitbar#149]
Would be nice to have the ability to manually refresh a plugin via a command line call. Would be useful for event based things, like cmus notifications.

**Comment by tresni** [comment]
:+1:  I'd also like to see it support refreshing via AppleScript

**Comment by ffittschen** [comment]
A manual refresh not only from the command line, but from within a plugin/script would be nice. 

E.g. I use the trash plugin with 1min refresh time. I click "Empty trash" and my trash is getting wiped, but the plugin shows the old number until in auto-refreshes. It would be nice to be able to refresh it, as soon as I click "Empty trash".

**Comment by Lugoues** [comment]
Why was this closed?

**Comment by matryer** [comment]
Ah my mistake, I saw the "Nevermind, I just discovered the refresh=true option." and assumed it was a question. :)
