### ISSUE TITLE
Plugin Idea: Display command line errors

### ISSUE THREAD

**Issue by jamiewilson** [matryer/bitbar#151]
For a long time I've wished that I could get a little indicator and a truncated version of the output for errors on the command line in my menu bar. 

This is particularly useful for things like build tools, static site generators that rebuild on changes and local dev servers. If you introduce breaking changes, it often doesn't affect the current set of files being served, and you can putz around for while wondering why your latest changes didn't refresh. 

Just a thought. Love BitBar! Thanks for sharing it.

**Comment by iosdeveloper** [comment]
Please move this to matryer/bitbar-plugins.
