### ISSUE TITLE
BitBar misses it's refresh interval if computer has gone into standby

### ISSUE THREAD

**Issue by Daio-io** [matryer/bitbar#154]
Currently if your computer goes into standby and remains in standby during its expected refresh interval, BitBar will not update when you come out of standby until it comes around to another refresh interval.

This is OK for plugins that have short refresh intervals but can be problematic for plugins with a longer refresh. It could mean that your plugin will never update if your machine goes in and out of standby a lot, leaving you having to manually reset every time.

Maybe a way to detect if the plugin has missed a refresh on wake and then refresh if it has could be implemented?

**Comment by matryer** [comment]
Interesting one. Is seems like BitBar should keep track of the last run time, and just calculate the amount of elapsed time since then when making a decision about whether to run or not. @muhqu I wonder if you could have a look at this?

**Comment by Daio-io** [comment]
:+1:
