### ISSUE TITLE
brew install doesn't work for OSX EL Capitan

### ISSUE THREAD

**Issue by vsrboth** [matryer/bitbar#159]
Here is i got after running the command line `brew cask install bitbar`.

```ruby
Error: Cask 'bitbar' definition is invalid: Bad header line: parse failed

**Comment by manojlds** [comment]
You need to fix your brew cask. 

```
brew uninstall --force brew-cask; brew update
```

**Comment by matryer** [comment]
Should we add this to the Troubleshooting place?

**Comment by brandonpittman** [comment]
I keep getting `Error: The option '--prefpanedir' requires an argument` on install.

**Comment by manojlds** [comment]
@matryer - yeah we could. It's a general brew cask migration where cask has been made part of Homebrew. We could link to the cask README too.

**Comment by matryer** [comment]
This is done.
