### ISSUE TITLE
terminal=false does not work?

### ISSUE THREAD

**Issue by gorangajic** [matryer/bitbar#162]
```
#!/bin/bash

echo "🤖";
echo "---";
echo "🗯 nudge | bash=\"adb shell input keyevent 82\" terminal=false"
```

am I doing something wrong ?

**Comment by tresni** [comment]
For `terminal=false` you need to break up your `bash` command.  I only found this out by checking the source code, it's not documented from what I saw.

```
echo "🗯 nudge | bash=adb param1=shell param2=input param3=keyevent param4=82 terminal=false"
```

You can do up-to `param5`.  If you need more then that...  PR's welcome I'm sure ;-)

**Comment by matryer** [comment]
Personally I find that pattern pretty limiting - I wonder if there's a better way to handle this?

**Comment by matryer** [comment]
I'd expect @gorangajic's code to work just fine - so perhaps the parser inside BitBar needs a bit of love.

**Comment by tresni** [comment]
The problem is that `NSTask` expects the [`setLaunchPath` to *only* be the executable](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSTask_Class/#//apple_ref/occ/instm/NSTask/setLaunchPath:) to launch, so you have to separate that.  This could still be possible just by tokenizing the `bash=` argument on the first space.  Otherwise you end up with an error:

```
1/6/16 3:16:26.071 PM BitBar[49665]: An uncaught exception was raised
1/6/16 3:16:26.071 PM BitBar[49665]: launch path not accessible
1/6/16 3:16:26.074 PM BitBar[49665]: (
	0   CoreFoundation                      0x00007fff87d4e03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8991476e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff87d4deed +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff8483a21c -[NSConcreteTask launchWithDictionary:] + 444
	4   BitBar                              0x00000001000106cb -[Plugin performMenuItemOpenTerminalAction:] + 1282
	5   libsystem_trace.dylib               0x00007fff84d9ccd7 _os_activity_initiate + 75
	6   AppKit                              0x00007fff8bb08eb1 -[NSApplication sendAction:to:from:] + 452
	7   AppKit                              0x00007fff8bb08c4e -[NSMenuItem _corePerformAction] + 382
	8   AppKit                              0x00007fff8bb0897c -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
	9   libsystem_trace.dylib               0x00007fff84d9ccd7 _os_activity_initiate + 75
	10  AppKit                              0x00007fff8bbcfb00 -[NSMenu performActionForItemAtIndex:] + 131
	11  AppKit                              0x00007fff8bbcfa66 -[NSMenu _internalPerformActionForItemAtIndex:] + 35
	12  AppKit                              0x00007fff8bbcf8b2 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 107
	13  AppKit                              0x00007fff8baf0d6b NSSLMMenuEventHandler + 724
	14  HIToolbox                           0x00007fff834a7b6c _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1260
	15  HIToolbox                           0x00007fff834a6fae _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 386
	16  HIToolbox                           0x00007fff834bccb6 SendEventToEventTarget + 40
	17  HIToolbox                           0x00007fff834f6f45 _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 428
	18  HIToolbox                           0x00007fff83534b8d SendMenuCommandWithContextAndModifiers + 59
	19  HIToolbox                           0x00007fff83534b30 SendMenuItemSelectedEvent + 188
	20  HIToolbox                           0x00007fff83534a09 _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
	21  HIToolbox                           0x00007fff83510cc1 _ZL19PopUpMenuSelectCoreP8MenuData5PointdS1_tjPK4RecttjS4_S4_PK14__CFDictionaryPK10__CFStringPP13OpaqueMenuRefPt + 1877
	22  HIToolbox                           0x00007fff8350fd74 _ZL26_HandlePopUpMenuSelection8P13OpaqueMenuRefP14OpaqueEventRefj5PointtjPK4RecttS6_S6_PK14__CFDictionaryPK10__CFStringPS0_Pt + 633
	23  HIToolbox                           0x00007fff8350f93b _HandlePopUpMenuSelectionWithDictionary + 287
	24  AppKit                              0x00007fff8bbc571d _NSSLMPopUpCarbonMenu3 + 5810
	25  AppKit                              0x00007fff8bbc4059 _NSPopUpCarbonMenu3 + 153
	26  AppKit                              0x00007fff8bbc3fb1 -[NSCarbonMenuImpl popUpMenu:atLocation:width:forView:withSelectedItem:withFont:withFlags:withOptions:] + 350
	27  AppKit                              0x00007fff8bf9d448 +[NSStatusBarButtonCell popupStatusBarMenu:inRect:ofView:withEvent:] + 682
	28  AppKit                              0x00007fff8bf9c87d -[NSStatusBarButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 159
	29  AppKit                              0x00007fff8bb1b366 -[NSControl mouseDown:] + 714
	30  AppKit                              0x00007fff8c0852dc -[NSWindow _reallySendEvent:isDelayedEvent:] + 14125
	31  AppKit                              0x00007fff8ba14c86 -[NSWindow sendEvent:] + 470
	32  AppKit                              0x00007fff8bf9fdee -[NSStatusBarWindow sendEvent:] + 242
	33  AppKit                              0x00007fff8ba11212 -[NSApplication sendEvent:] + 2504
	34  AppKit                              0x00007fff8b93ab68 -[NSApplication run] + 711
	35  AppKit                              0x00007fff8b8b7244 NSApplicationMain + 1832
	36  BitBar                              0x0000000100001f2c start + 52
)
```

The second problem is that [`setArguments` needs an array](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSTask_Class/#//apple_ref/occ/instm/NSTask/setArguments:).  If you pass it a string, that is passed as a single argument.  So the `params#` arguments solve this as they get parsed into an array.  Again, could possibly be solved by tokenizing the string based on space but that's prone to issues around properly parsing with quotes.  If you hijack another character, then we need to have a potential escape for that character in case it's needed :)  So, yeah, it's not pretty, but it does work :)

**Comment by gorangajic** [comment]
I have found what is the problem `PATH` was not set for `adb`, so I have used `source ~/.zshrc` where `adb` `PATH` is already defined

```sh
#!/bin/bash

if [[ "$1" = "nudge" ]]; then
  source ~/.zshrc
  adb shell input keyevent 82
  exit
fi

echo "🤖";
echo "---";
echo "🗯nudge | bash=$0 param1=nudge terminal=false"
```

it was difficult to debug this because error was silent, maybe it would be good to write output somewhere for example `~/.bitbar-debug` when exit code is different than 0 and show osx notification that something went wrong

**Comment by tresni** [comment]
You can specify the path in the `bash=` option if you don't want to callback to your script:

```
echo "nudge | bash=/path/to/adb param1=..."
```

**Comment by jcaille** [comment]
Hey ! A few days ago, #50 was merged in. This means that you can just enclose your command in single or double quotes to avoir the whole `param` thing.

`do stuff | bash='say Hello world'`

**Comment by syllogismos** [comment]
I'm having a similar issue with `terminal=false`, when `terminal=true` its working as expected but I want it to do it silently without opening a new terminal.

Mine is a python script, which goes like this
```
print "Start | bash='/usr/local/bin/aws' param1='ec2' param2='start-instances' param3='--instance-ids' param4='%s' param5='>>/tmp/bitbar_ec2' terminal=false" % (item['instance_id'])
```

I tried without param1 and etc, giving the whole path of aws, and etc solutions that were mentioned here. But still its not working with `terminal=false`.
I even tried dumping the output to some file, with `terminal=true` I can see logs in that tmp file but nothing with `terminal=false`

Please help me. I almost have a perfect plugin that does all the things I do with ec2, except for this little annoyance. I can make it work with `terminal=true` but I dont want a terminal popping up.

**Comment by oleander** [comment]
@syllogismos `>>/tmp/bitbar_ec2` is going to be passed as an argument to `aws`, like `aws ">>/tmp/bitbar_ec2"` which is not what you want. Instead you need to use `bash -c '...'` Take a look at this issue for more details. https://github.com/matryer/bitbar/issues/415

**Comment by syllogismos** [comment]
Hey thanks for the quick response.

I actually don't need the `>>/tmp/bitbar_ec2` part, that I added only for debugging. Even without /tmp/bitbar_ec2 its not working with `terminal=false`.

But I do use the `bash -c` method somewhere else.. and I tried these two things below. Still its not working with `terminal=false`

```
print "Stop | bash='/bin/bash' param1='-c' param2='aws' param3='ec2' param4='stop-instances' param5='--instance-ids' param6='%s' terminal=false" % (item['instance_id'])
```
With this I had to use 6 params, which bitbar is not able to parse.. and gives this output with `terminal=true`
```
$ /bin/bash -c aws ec2 stop-instances --instance-ids
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: too few arguments
```

Instead of this, I combined the param5 and param6 into one and did
```
print "Stop | bash='/bin/bash' param1='-c' param2='aws' param3='ec2' param4='stop-instances' param5='--instance-ids %s' terminal=false" % (item['instance_id'])
```
The thing when `terminal=True`, prints out this output
```
$ /bin/bash -c aws ec2 stop-instances --instance-ids i-0e6cd1ea15b3e8477
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: too few arguments
```


And finally I did it without using params at all
and used this
```
print "Start | bash='/bin/bash -c aws ec2 start-instances --instance-ids %s' terminal=false" % (item['instance_id'])
```
This also with `terminal=true` returned this 
```
$ /bin/bash -c aws ec2 start-instances --instance-ids i-0e6cd1ea15b3e8477     
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: too few arguments
```

In earlier case, I did get things working with `terminal=true`, here with `-c` even that is not working.

I tried executing the above command that was in the terminal and changed it slightly for it to work.
I have to surround the `aws` command in double quotes like this
```
$ /bin/bash -c "aws ec2 start-instances --instance-ids i-0e6cd1ea15b3e8477"
{
    "StartingInstances": [
        {
            "InstanceId": "i-0e6cd1ea15b3e8477", 
            "CurrentState": {
                "Code": 0, 
                "Name": "pending"
            }, 
            "PreviousState": {
                "Code": 80, 
                "Name": "stopped"
            }
        }
    ]
}
```

But how can I print the double quotes from bitbar. These are all the things I tried.

**Comment by oleander** [comment]
@syllogismos I'm off to a meeting so don't have time to look at the your code right now. Keep in mind that `bash -c` only takes one argument (it takes more, but I don't have time to explain it now). You need to pass `bash="/path/to/bash" param1="-c", param2="aws arg1 arg2 arg2"`. 

I'm not sure how keen @matryer is me promoting my version/pull request being developed [here](https://github.com/matryer/bitbar/pull/391), but you can give it a try. I explicitly solve this problem already. 

- [BitBar v3.0.1 - Github Release](https://github.com/oleander/bitbar/releases/download/untagged-296d5d289628e56e2a8e/BitBar.dmg)

**Comment by syllogismos** [comment]
Thanks for responding quickly.
I tried that as well. Will just make sure one more time.

**Comment by syllogismos** [comment]
```
print "Stop | bash='/bin/bash' param1='-c' param2='aws ec2 stop-instances --instance-ids %s'" % (item['instance_id'])
```

This is trying to execute below command
```
/bin/bash -c aws ec2 stop-instances --instance-ids i-0e6cd1ea15b3e8477 
```
But I need double quotes for this to work as expected like this
```
/bin/bash -c "aws ec2 stop-instances --instance-ids i-0e6cd1ea15b3e8477"
```

Maybe `aws` command line works a little bit different than other utilities.

**Comment by oleander** [comment]
@syllogismos The quotes are only needed when using `terminal=true`, not `terminal=false`. (yes, this is confusing, I know :))

**Comment by oleander** [comment]
@syllogismos I explain the problem briefly here if you're interested in why this doesn't work as you expect. https://github.com/oleander/bitbar/commit/9792c95805d1abc97d4afc2cdbbc460fc7a66539#commitcomment-22144737 This is also where the problem was fixed.

**Comment by syllogismos** [comment]
Thanks that comment explains why some of the things I did earlier are working, like pbcopy. And also the nice python errors that are shown in the bitbar menu. They are all very helpful.

But in this case, even with terminal = false, and params as you described is not working in this case.

I tried so many variations of how to fix this, I'm afraid I missed something so simple and am wasting my time on this. But I double checked what you asked me to do and it still seems to be not working.

Also there is no way for me to debug `terminal=false`
```
print "Start | bash='/bin/bash' param1='-c' param2='aws ec2 start-instances --instance_ids i-0e6cd1ea15b3e8477' terminal=false" 
```

**Comment by oleander** [comment]
@syllogismos Did you try the BitBar version I linked to? How do you install aws? I can give it a try on my machine.

**Comment by syllogismos** [comment]
I'll update my bitbar and see.. hopefully my old scripts wont fail..

`pip install aws`
and then
`aws configure` and give your aws keys for it to work

**Comment by syllogismos** [comment]
I updated it to the latest 1.9.2 and still it doesn't seem to work.

I will try to give you basic instrictions of this basic script for you to test..

`pip install aws`
create a new user from aws console that can access Ec2, and get both the access and secrey keys. use them to configure by doing this
`aws configure`
create a new instance from aws console, note the instance id from the browser, it will be of the form `i-sd134af123`

and then create a new bitbar plugin with the following contents
and hardcode the instance id as shown below.
```
#! /usr/bin/env python
print 'EC2'
print '---'
print "Start | bash='/bin/bash' param1='-c' param2='aws ec2 start-instances --instance_ids i-0e6cd1ea15b3e8477' terminal=false"
print "Stop | bash='/bin/bash' param1='-c' param2='aws ec2 stop-instances --instance_ids i-0e6cd1ea15b3e8477' terminal=false"
```

**Comment by oleander** [comment]
@syllogismos You need to download it manually; https://github.com/oleander/bitbar/releases/download/untagged-296d5d289628e56e2a8e/BitBar.dmg It's a build from my pull request.

**Comment by syllogismos** [comment]
Its asking me to set the plugin folder again.. and mine is a hidden folder, and apparently I have to restart computer to make a hidden folder as plugin folder, https://github.com/matryer/bitbar/issues/395 

I will test it later today and update you.
