### ISSUE TITLE
Alert Notification Menubar

### ISSUE THREAD

**Issue by lrzuniga** [matryer/bitbar#163]
Hi,

Bitbar is showing a yellow triangle alert icon in the menu bar. (link: http://www.screencast.com/t/mTwGiF2cR)

Not sure why.

Here is the command in the shell script that is causing the alert notification:

logger -t PRTG -s -p local1.info "$MSG"

Yes, I am sending messages from local osx computer to a syslog server.

Any info appreciated.

Luis

**Comment by tresni** [comment]
Usually when I see this is means the shell script is either not executable or doesn't have the necessary shebang (e.g. `#! /bin/bash1`).  Normally if you hover over the icon or click on it, it'll tell you exactly why it's showing up.

**Comment by lrzuniga** [comment]
Here is the script...everything seems to be working ok. The messages are showing up in the syslog server, but I'd just like to remove the alert icon.

(Ive removed some of the code as it is just a bunch of elif's)

Thanks for your help!


#!/bin/sh
#Identify the AP and Freq.  connected to wifi adapter.

mac=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | awk '/ BSSID/ {print substr($0, index($0, $2))}')
time_stamp=$(date)

if [ "$mac" = "9c:d6:43:c4:20:aa" ]; then
			MSG="Casa"
			#102
	elif [[ "$mac" = "0:17:c5:df:16:2c" ]]; then
			MSG="AP 102:2.5"
<SNIP>	
	else
		MSG="N/A"
fi

#Print to menu bar
echo "$MSG"

#send to PRTG syslog
/usr/bin/logger -t PRTG -s -p local1.info "$MSG"

**Comment by lrzuniga** [comment]
hovering over the triangle didnt show any description

**Comment by lrzuniga** [comment]
figured it out

was sending logger output to standard error as well as standard out

fixed

thanks for a great tool!

**Comment by matryer** [comment]
You're welcome :)
