### ISSUE TITLE
Ability to bundle the app with customizations?

### ISSUE THREAD

**Issue by cpg** [matryer/bitbar#164]
BitBar is great!

Is there a (documented) way to bundle the app to end users (people who would not necessarily want to or could create directories, follow technical directions, etc.), with a couple of plugins in it, so that we can ship the zip file and they just have to install the app?

I could not find much mention of how to do this in the docs or in the issues and I think it would be useful beyond BitBar itself and the more technical audience it caters to.

Ideally, we'd also like to give it a nice name (possibly including "BitBar" and/or a link and credits, of course) and customize some things to avoid confusion, like removing "run from terminal" and some preferences.

**Comment by matryer** [comment]
Oh this is a great idea. No we haven't thought about a way to do this yet, but I'd support any efforts.

**Comment by 0wnrepo** [comment]
I'll take a look and create an installer script for the app + plugins.

**Comment by 0wnrepo** [comment]
Created the installer. Now we need to decide the plugin location. Any thoughts ?

**Comment by hrrrsn** [comment]
Under `~/Library/Application Support`?

**Comment by gilbertpalau** [comment]
@0wnrepo I would suggest you create it outside of ~/Lib more in /Library/Application Support/BitBar

**Comment by matryer** [comment]
What if the 'system BitBar' menu items we hidden by default and only became visible when you hold the option key? That way;

a) normal users will never see them and,
b) even pro/dev users will have a neater experience

Thoughts?

**Comment by mm2270** [comment]
Option click to show the admin related menu items is OK, but I'd personally prefer a simple defaults write command that could enable/disable them. That would keep them a little more private than just an Option click on the menu, which could be easily discovered by someone.
Either way should be OK though, as long as we have some way of hiding those menu items. Just my 2¢. :)

**Comment by iosdeveloper** [comment]
Here is what I did (not requiring people create directories or making plugins executable):

1. I added a Copy Files Build Phase with Destination Executables to the app target and added the scripts I wanted to bundle.
2. I changed `pluginsDirectory` to default to the app's executables directory, preventing the initial prompt to create a plugins directory and pointing to the bundled scripts. People could still override this by setting a plugin folder in the app under Preferences.
3. Finally I had to filter out the app executable.

I'm happy to submit a PR or make further changes.

**Comment by gilbertpalau** [comment]
@matryer your idea would help but it still would allow tampering.  If you did something like VMWare does for deploying their app massively... It's pretty clean and it would work in this scenario... 

VMWare does an mpkg, within it has a folder called Deployment Items.  In that folder there is an xml called Deploy.ini that allows me to set certain settings

In the case of BitBar, you could do the same within the pkg, by adding an ini that allowed us to set some variables like:

[Plugin Location]
plugindir = /Library/Application Support/Bitbar/plugin

[UI Config]
remove preference menu = true
allow preference menu via alt key = false

[BitBar Config]
allow updates = false
launch bitbar without reboot = true

etc.
-----

This way we could bundle those settings on the app and just deploy the app invisibly to the user without letting the user know what it is or where... 

If the user clicks the bundle on the menu bar they can get whatever extra features are allowed per the script and if not it does nothing else.
