### ISSUE TITLE
 2.1 Southampton Crystal Palace: Wilfried Zaha nets winner for Eagles

### ISSUE THREAD

**Issue by yourfifa1** [matryer/bitbar#166]
Goals in each half from Joel Ward and Wilfried Zaha have been enough to secure victory against the opposition out of shape, whose only response came from Oriol Romeu.<a href="http://www.urfifa.com">cheap FIFA coins</a> corresponding to each platform has a comprehensive sales, the players do not miss.
Palacio, largely inspired by former Southampton striker Jason Puncheon scored the first goal in the 29th minute. Puncheon former teammate Steven Davis dispossessed in midfield, dribbled to give from the center line of the penalty area and the armies of the square, a living routine ends just outside the door.
Low confidence of Southampton began clearly deteriorate further and director Ronald Koeman responded tirelessly introducing surprise Dusan Tadic and Juanmi for Maya Yoshida and Davis, back from a back from five to four.
His reply was almost instantaneous. If Sadio Mane tested Wayne Hennessey with a header 51 minutes, Romeu said to recovery, and produces a narrow range of routine to even finish.
Playing with more conviction, the hosts looked the more likely winner until 68 minutes, Palace won the leadership and victory thus closed.This may affect the FIFA 16 game on sale at a certain extent, the impact of <a href="http://www.urfifa.com">cheap FIFA 16 coins</a> sales.

**Comment by matryer** [comment]
Bollocks.
