### ISSUE TITLE
contributor list doesn't have my name and plugin

### ISSUE THREAD

**Issue by gautamkrishnar** [matryer/bitbar#168]
https://github.com/matryer/bitbar/pull/54

page:
https://getbitbar.com/contributors

**Comment by matryer** [comment]
Have you added [metadata](https://github.com/matryer/bitbar/blob/master/README.md#metadata) to your plugin?

**Comment by matryer** [comment]
Looks like you're missing some of the metadata fields - if you add your github username, you'll show up in the contributors list.

**Comment by gautamkrishnar** [comment]
It has my name as a comment. If its not how can i add that?

**Comment by matryer** [comment]
see this link: https://github.com/matryer/bitbar/blob/master/README.md#metadata

**Comment by matryer** [comment]
over the past few days - more supported metadata has been added

**Comment by gautamkrishnar** [comment]
Thanks :smile: Will create a new pull request soon.
