### ISSUE TITLE
Output sometimes doubled

### ISSUE THREAD

**Issue by colindean** [matryer/bitbar#171]
I'm using the brew outdated script, with a modification to the output text and I'm running it far less frequently. It will sometimes show twice in the bar.

![screen shot 2016-01-12 at 14 34 56](https://cloud.githubusercontent.com/assets/197224/12274612/ae595a1e-b939-11e5-8660-de7de5fb8915.png)

I can't really explain it.

My version:

```
#!/bin/bash

####
# List available updates from Homebrew (OS X)
###

exit_with_error() {
  echo "err | color=red";
  exit 1;
}

/usr/local/bin/brew update > /dev/null || exit_with_error;

UPDATES=`/usr/local/bin/brew outdated --verbose`;

UPDATE_COUNT=`echo "$UPDATES" | grep -v ^$ | wc -l | sed -e 's/^[[:space:]]*//'`;

if [ $UPDATE_COUNT -gt 0 ]; then
  echo "🍺🆙${UPDATE_COUNT}"
fi
echo "---";
#echo 'Run upgrade | bash="/usr/local/bin/brew upgrade" terminal="true"'
echo "$UPDATES";

```

**Comment by taylorzane** [comment]
We've actually got a pretty long conversation going on about this in #21.

**Comment by colindean** [comment]
Ha! I didn't search for "duplicate", just "doubled". 

Need more :coffee:
