### ISSUE TITLE
Too much resource used

### ISSUE THREAD

**Issue by Hurray0** [matryer/bitbar#18]
I wrote a bash code like this, and it runs with too much resource. CPU 10%~20%, memory(1.08G/8G). I don't think it should use so much resource.

172-10-23-204:msg hurray$ cat msg.5d.sh 
#!/bin/bash
echo "Hello | color=#FF0000"
echo "Hello | color=#FF7F00"
echo "Hello | color=#FFFF00"
echo "Hello | color=#00FF00"
echo "Hello | color=#00FFFF"
echo "Hello | color=#0000FF"
echo "Hello | color=#8B00FF"
echo "Hello | color=#FF00FF"

**Comment by Hurray0** [comment]
It seems to be the cache problem. Echo sentence is loop all the time, and my update time (5d) is too long. I restart the program and the problem solved. I will change 5d to 1h and have a try.

**Comment by matryer** [comment]
Is this still an issue?

**Comment by daturkel** [comment]
Running Spotify.10s and Clipboard.10s plugins on a mac mini with 2.6 GHz core i5, 8gb ram. Seeing 7-15% CPU idle for bitbar 91.5 uncompressed memory usage. The latter seems fine to me, but the former is still a little concerning.

**Comment by matryer** [comment]
@daturkel do you have experience with these kinds of optimisations?

**Comment by daturkel** [comment]
I don't, sorry.

**Comment by guido4000** [comment]
On a (slow) MacBook I see less than 1% CPU for Spotify.10s.

**Comment by webstone-ro** [comment]
Just to add to this, I'm looking at ~20% CPU on a 2011 MacBook Pro after a while (over night), when running 3 scripts set at 5m, 1h and 5h. Quit/restart solves the problem and usage is around 0.4%. I'll post back if anyone's interested, I've only been using BitBar for a couple of days.

Cool app, by the way! Right now I'm using it to tail some log files and find errors, to check the status of various servers and as a currency rate checker.
