### ISSUE TITLE
Change menubar color

### ISSUE THREAD

**Issue by rasiquiz** [matryer/bitbar#183]
An option to change the color of the text displayed in the menubar

**Comment by matryer** [comment]
You can - see the [plugin API](https://github.com/matryer/bitbar#plugin-api)

**Comment by rasiquiz** [comment]
Not the dropdown text. The text displayed in the menubar

**Comment by matryer** [comment]
That works too - see https://getbitbar.com/plugins/Finance/gfinance.5m.py for an example
