### ISSUE TITLE
Send Notifications from Plugin

### ISSUE THREAD

**Issue by NeilBetham** [matryer/bitbar#186]
We it be possible to allow plugins to send notifications to notification center? Say for instance if a ping times out or a disk is past a certain percentage of usage.

**Comment by JayBrown** [comment]
https://github.com/julienXX/terminal-notifier

$ brew install terminal-notifier

Copy the .app to /Applications/Utilities and run it from scripts e.g. like this (lots of other options):

/Applications/Utilities/terminal-notifier.app/Contents/MacOS/terminal-notifier \
	-title "TITLE" \
	-subtitle "SUBTITLE" \
	-message "MESSAGE" \
	-appIcon /path/to/IconFile.icns \
	-execute "SHELLCOMMAND OPTIONS"
	>/dev/null

**Comment by NeilBetham** [comment]
Yeah, i've used that utility before, was just curious if it would be possible to add that functionality to BitBar.

**Comment by jontelang** [comment]
Like a normal OSX notification?

Wouldn't `osascript -e 'display notification "woho" with title "thisis title';` work? (not tested it)

**Comment by NeilBetham** [comment]
Nah, the same style notification you would receive for something like and email or a message. Terminal Notifier achieves what I want but it's be nice to not have my plugins dependent on both apps.

**Comment by NeilBetham** [comment]
Ahhh cool, that works. I didn't realize you could send notifications via osa scripts.
