### ISSUE TITLE
Plugins folder situation in repo could be better

### ISSUE THREAD

**Issue by WillEccles** [matryer/bitbar#187]
It seems to me that the "Plugins" folder is useless, and having someone go there just to find that they have to go somewhere else seems odd. It might be advisable to add the link to the plugins repo in the main README and then remove the Plugins directory. This could be improved upon further by moving the plugin creation information to a space in the wiki, thus removing a lot of clutter and making finding the link to the plugins repo easier. Plus, many users who may not want to make a plugin themselves may find all that information overwhelming.

**Comment by JayBrown** [comment]
In the end the best thing imho would be a real preferences window for BitBar, with tabs, one "general" tab (with start at login, set/change plugin folder location or display default location), and with a plugins tab that gets a list from a remote "official" repository plus the ability of the user to download single plugins (or all) from that repo, add plugins locally (Finder "where is it" open window), enable/disable/delete plugins, open plugins folder, open plugin script in > select: TextEdit, BBEdit etc., refresh remote plugin list (automatic schedule, manual), notify of repo or individual script updates (OS X notification center), setting: download updates automatically yes/no, activate & refresh automatically yes/no, with the plugin list having two sections, one "official" (from the BitBar repo), one "user scripts"… and then one "About" tab with Github link, Support link (this Issues section), the official website, the manual. Make it "real" Mac application. But that should really be a no-brainer, right?

**Comment by matryer** [comment]
I agree with both of you. For now, I'll delete the plugin folder. The preferences thing is going to take a bit more work.
