### ISSUE TITLE
Add a gitter.im or slack channel

### ISSUE THREAD

**Issue by JaredVogt** [matryer/bitbar#188]
So all of us building plugins can exchange information and get help. Gitter would be my preference.

**Comment by matryer** [comment]
Played with Glitter - seems a little clunky (the UI) right now. How's your experience been?

**Comment by JaredVogt** [comment]
Well truth be told, I like Slack interface/UX better (I have come to depend on it). However... finding public Slack channels is really hard (haven't found any decent search/curated directories). It looks like gitter.im has gained pretty good momentum around github projects. The trend I see is... you want to chat about a github project, check gitter to see if it has been set up. All of that said... I am fairly new to gitter, a lot of that is based on initial impressions...

**Comment by matryer** [comment]
You have to be invited to Slack channels, which is a shame.

**Comment by iosdeveloper** [comment]
We could use [Slackin](http://rauchg.com/slackin/).

**Comment by iosdeveloper** [comment]
We now have a Slack channel: [![Slack Status](https://getbitbar.herokuapp.com/badge.svg)](https://getbitbar.herokuapp.com/)
