### ISSUE TITLE
launch path not accessible

### ISSUE THREAD

**Issue by SteveEdson** [matryer/bitbar#189]
Just updated to the latest version and I'm getting 'launch path not accessible' errors in my status bar. There is one for each file in my plugins folder. These files are not scripts, but are included and used by the other plugins.

Previously, Bitbar just ignored these files (maybe because they didn't have the `{name}.{time}.{ext}`) format?)

Is there a way for bitbar to ignore these files? Or can we put them in a sub-dir that will be ignored?

Thanks

**Comment by matryer** [comment]
BitBar ignores files prefixed with `.` dots. Can you try that and let me know if it works?

**Comment by SteveEdson** [comment]
Thanks, it does work, however it would be better if it ignored files that aren't in the right format. Also, the files didn't have the execute permissions, but it was still trying them anyway.

I'm writing a PHP formatter for bitbar, and it would be useful to have composers `vendor/` directory for SDKs etc, however this might cause a big issue when the folder is full of hundreds of files.

Thanks for Bitbar btw, its awesome.

**Comment by matryer** [comment]
Thanks.

Right now - a plugin being a single file is the best/simplest way to do it - but there are discussions about evolving the way plugins work.

The trouble with ignoring plugin filenames it doesn't understand is that it will fail silently if someone makes a mistake - rather than reporting the error.

**Comment by SteveEdson** [comment]
I'm wanting a core file that can be used by all my plugins, so that I can do thinks like:

```
$bb = new Bitbar();

$line = $bb->newLine();

$line
    ->setText('Hello World')
    ->setColour('yellow')
    ->setUrl('http://google.com')
    ->setLength('3')
    ->show();
```

etc.

The current usage of putting it in a `.directory` works for me, but it wouldn't work if I wanted to open source it and allow people to pull it in to their directories. Hopefully this can change in future.

Alternatively, the warning messages might be better hidden under a subdirectory of preferences, rather than going directly in the status bar.

Thanks

**Comment by matryer** [comment]
see https://github.com/matryer/bitbar/issues/112 too

**Comment by dressler18** [comment]
Not entirely related, but wanted to post this in case it helps anyone with a similar issue. I got the same error "launch path not accessible" on a fresh install on Sierra. I searched and only found this thread. By default my plugin folder was my Documents folder. Sierra moves Documents out to iCloud which makes them inaccessible to some programs. My solution was to change my Plugin folder to a non iCloud folder.

**Comment by jemus42** [comment]
I still have this issue, my bitbar plugins dir is `~/bitbar`, so I don't think iCloud is an issue. I can't get any plugin to work :(

**Comment by BradleyJohnson** [comment]
@jemus42 Try `chmod +x plugin_name`

**Comment by amywtlin** [comment]
@BradleyJohnson I tried the solution you mentioned but it doesn't work... I'm still seeing this:
![screen shot 2018-01-04 at 3 28 45 pm](https://user-images.githubusercontent.com/11730007/34553713-026f15d0-f164-11e7-98b7-d491878cb2db.png)

Any idea how to resolve this?

**Comment by madxcream** [comment]
I'm getting the "launch path not accessible" also on fresh install. Mac OS 10.13.3. Tried everything mentioned.

**Comment by jamesshapiro** [comment]
chmod +x did NOT solve the issue for me. The script runs fine every time...

**Comment by matryer** [comment]
Try moving your bitbar plugin folder, some places are protected in recent
macOS updates. Does this help?

Mat

**Comment by jamesshapiro** [comment]
Hi Mat,

It was an unrelated issue having to do with the Python shebang in one of my
scripts that has now been resolved. I edited my post to make a note of it.
Thanks!

James
