### ISSUE TITLE
Separating menu items for positioning purposes

### ISSUE THREAD

**Issue by alesf** [matryer/bitbar#194]
Would it be possible to separate menu items?
Bartender application offers repositioning of menu items and BitBar plugins stick together.

If this is not possible it would be nice to set order of BitBar items as they seem to order randomly at the moment.

**Comment by JaredVogt** [comment]
A hack. I don't think its random - it sorts alphanumerically from right. If you prefix your plugins `1plug.30s.sh`, `1anotherplug.30s.sh`, you can control display order. BTW, don't use a `.` or it will ignore the subsequent refresh value (`1.plug.3s.sh` does not work correctly).

**Comment by matryer** [comment]
Should we add this tip to the docs somewhere?

**Comment by alesf** [comment]
I think many would find it useful.

@matryer How hard would it be to separate menu items?
![bitbar-dragdrop](https://cloud.githubusercontent.com/assets/1148574/12778258/1bea983e-ca62-11e5-9211-619cbac233ed.gif)

**Comment by matryer** [comment]
I don't know, but I do like the idea.

**Comment by iosdeveloper** [comment]
This is quite similar to #158.
