### ISSUE TITLE
Phishing Email Scam

### ISSUE THREAD

**Issue by ProLoser** [matryer/bitbar#197]
So I realize this is a bit of an unusual issue to open, but I reported this to Github and marked it as phishing on my email client and thought I'd just let others know. I've occasionally been receiving what I believe to be phishing scams or social hacking. I have had no interactions with this repo before now other than starring the repo. Note that the sender's reply email domain is blank and does not match the website he links to.

<img width="945" alt="screen shot 2016-01-26 at 10 34 51 am" src="https://cloud.githubusercontent.com/assets/67395/12590713/29a42156-c419-11e5-9e3d-978b7411e077.png">

**Comment by mbilker** [comment]
I have the same email in my email.

**Comment by 0wnrepo** [comment]
Every commit will also have your e-mail.
git log --all --format='%aN <%cE>' | sort -u
on all public repositories.

**Comment by mbilker** [comment]
I didn't commit to this repository. I only starred this repository. It seems this attacker is very smart.
