### ISSUE TITLE
Deploying Bitbar in an environment

### ISSUE THREAD

**Issue by gilbertpalau** [matryer/bitbar#198]
#164 

I have been using bitter for quite some time and its something I would like to deploy as part of our images, so that the IP is present on the menu bar for all users.

I have been able to deploy bitbar, and create a folder for the plugins and the location, but I have not been able by script or otherwise, to activate bitbar and tell it to use the plugin directory I assigned for it.

Is there a way to add these settings by command-line ? or is this something that would need to get added to bitbar ?

**Comment by keithamus** [comment]
@gilbertpalau there is indeed a way to do this:

```sh
# Will open BitBar if it is in the /Applications/ directory (or ~/Applications, maybe some other places too)
open -a "BitBar"

# Sets the pluginsDirectory to read from
defaults read com.matryer.bitbar pluginsDirectory "~/.bitbar/plugins"

# Kills BitBar!
killall BitBar
```

Hopefully that solves your issue :smile:

**Comment by gilbertpalau** [comment]
@keithamus Something I noticed today was that some systems I deployed this to, the scripts lost the "executable" attributes and I would get the Triangle-Warning-of-Death up in the menu bar.  Do you have a ny suggesting for preventing this from happening?

**Comment by matryer** [comment]
I don’t know why that would happen but they can be re-enbaled by doing `chmod +x *.sh` inside the plugin directory (assuming they’re all `.sh` files).

The ‘Managed BitBar’ thing keeps coming up, and I think it deserves closer attention. I.e. a way to package and deliver (easily) a BitBar configuration to users and remove some of the system menu items etc.

**Comment by matryer** [comment]
see https://github.com/matryer/bitbar/issues/180
