### ISSUE TITLE
Memory leakage

### ISSUE THREAD

**Issue by torkelsson** [matryer/bitbar#203]
Hi,

Running 1.5beta.

It looks like there are some kind of memory leakage in Bitbar. It starts at using around 6 MBs, but the used memory is slowly growing over time, especially when doing some suspend/resume cycles. Don't know if it is in Bitbar or any of the plugins. I'm using the Spotify, lock-screen, caffeinate and brew-updates plugins.

**Comment by mcchrish** [comment]
Noticed this too. It's slow but noticeable. I tend to restart Bitbar after a day or two when it reaches around 100MB+.

**Comment by 0wnrepo** [comment]
In Xcode run command+I and select memory leaks + zombies. Select objective-c calls and see what's wrong :-)

**Comment by matryer** [comment]
working on this

**Comment by mm2270** [comment]
Just wanted to comment that I also see this. Currently running the 1.5.1 release. At start, its < 10 MBs, but slowly creeps up. I've had mine running now about 2 days, and Activity Monitor shows the usage now  at ~125 MBs.

**Comment by matryer** [comment]
I think this depends on plugins… with some basic ones, I don’t see the memory climbing.

**Comment by mm2270** [comment]
@matryer Perhaps, but just to note, none of my plug-ins are using `curl` which was previously thought of as a culprit. They are doing plenty of other things, but not curl'ing against any sites. I _am_ doing a dscl query against an AD domain, so that may be something for me to look at. I'll play with it and see.

**Comment by iosdeveloper** [comment]
This should be fixed as well by bfb47b3 and c352e7e.
