### ISSUE TITLE
Minimum system requirements are not specified

### ISSUE THREAD

**Issue by splorp** [matryer/bitbar#204]
What are the minimum system requirements for BitBar? Nowhere in the repo or on the BitBar website are they mentioned. Specifically, I’m trying to determine if this can be installed under Mac OS X 10.6 Snow Leopard.

**Comment by iosdeveloper** [comment]
Deployment target is indeed 10.6, although I haven't checked if any newer APIs are used.

**Comment by splorp** [comment]
Ok, thanks.

I’m performing a bunch of tests under 10.6.8 today and will let you know if I stumble across any gotchas.

**Comment by splorp** [comment]
+1

**Comment by matryer** [comment]
See top line of readme: https://github.com/matryer/bitbar
