### ISSUE TITLE
sshpass issues

### ISSUE THREAD

**Issue by YKSing** [matryer/bitbar#205]
When use sshpass, it shows command not found
http://sourceforge.net/projects/sshpass/

**Comment by gordonrgw** [comment]
is sshpass in your path, or have you used the full path to sshpass?

**Comment by YKSing** [comment]
When I use full path, it shows another error:
`Failed to run command: No such file or directory`

Here is the full command:
`/usr/local/bin/sshpass -p "password" ssh-copy-id -i ~/.ssh/id_rsa.pub root@192.168.1.250`

**Comment by YKSing** [comment]
Oh I found that ssh-copy-id needs full path too, sorry about the mistake
`/usr/local/bin/sshpass -p "password" /usr/local/bin/ssh-copy-id -i ~/.ssh/id_rsa.pub root@192.168.1.250`
