### ISSUE TITLE
BitBar cannot find programs installed by brew

### ISSUE THREAD

**Issue by carc1n0gen** [matryer/bitbar#207]
I'm trying to use ansiweather with BitBar.  I wrote a script containing

```
#!/bin/bash

exec ansiweather -l Waterloo,CA -a false -f 1
```

`ansiweather` is a tool installed with `brew install ansiweather`.  The script works when I manually run it, but I get a `exec: ansiweather: not found` from BitBar

**Comment by alexrockt** [comment]
BitBar doesn't run in the same environment the Terminal applications runs in.

Replace ansiweather with /usr/local/bin/ansiweather and it should work.

**Comment by carc1n0gen** [comment]
ansiweather depends on other utility commands installed by brew so this
will still fail

**Comment by JayBrown** [comment]
Maybe you can solve the problem by changing the contents of /private/etc/paths to (in this order):
/usr/local/bin
/usr/bin
/bin
/usr/local/sbin
/usr/sbin
/sbin

**Comment by carc1n0gen** [comment]
@JayBrown I've tried this, and it still does not work.  Brew installs ansiweather to /usr/local/bin which was already in that file at the top.  I still did change the contents of that file to your suggestion and nothing changed.

**Comment by carc1n0gen** [comment]
Ended up fixing this issue by setting the path within the script:

```
PATH=/usr/local/bin:$PATH
```

**Comment by bfred-it** [comment]
That seems a stopgap solution though. Can bitbar use bash' `PATH`? Plugins would have to be manually modified depending on the environment setup otherwise, while they could use the existing `PATH` configuration
