### ISSUE TITLE
Crash when using terminal=false

### ISSUE THREAD

**Issue by mwallace582** [matryer/bitbar#208]
I just saw this project on HN, and I love it so far. Thanks for putting it together!

Unfortunately, I'm hitting an issue where my script crashes when I set the terminal variable to false.
I have created the following basic script which demonstrates the issue:
```
   #!/bin/bash
   echo "title"
   echo "---"
   echo "test | bash=\"echo hello world\" terminal=false"
```

Whenever I click on the "test" item in the menubar, bitbar crashes completely. Please let me know if I am doing something wrong.

Thanks,
Matthew

**Comment by matryer** [comment]
see if this format works for you? https://github.com/matryer/bitbar-plugins/blob/cf3196ef60658625e602872ebe7b914a417eaec1/Music/spotify.10s.sh#L27

**Comment by mwallace582** [comment]
Thanks for the suggestion. I just tried that, and I'm getting the same result. I'm on El Capitan (10.11.2) if that matters at all.

```
   #!/bin/bash
   echo "title"
   echo "---"
   echo "test | bash=echo param1=hello_world terminal=false"
```

**Comment by matryer** [comment]
Which BitBar version are you running?

**Comment by mwallace582** [comment]
I was using v1.5 beta 1. I just tried v1.4, and it looks like this one is not crashing.

But even though it's not crashing, the script doesn't seem to be running. I have tried the following script to test if the command had an effect:
```
#!/bin/bash
  echo "title"
  echo "---"
  echo "test | bash=touch param1=/tmp/hello terminal=false"
  echo "test2 | bash=\"touch /tmp/hello\" terminal=false"
```

I tried both of these buttons, and neither of them created /tmp/hello.

**Comment by matryer** [comment]
How strange. Do you have Xcode? I wonder if you cloned the project you could see what the crash is?

Apologies, extremely busy this week.

**Comment by mwallace582** [comment]
I do have Xcode, and know a bit of objective-c. I'll look into it further tonight and let you know if I come up with anything.

Thanks for your help!

**Comment by matryer** [comment]
Thanks for reporting it.

**Comment by willyt** [comment]
I'm seeing this too with 1.5beta

**Comment by mwallace582** [comment]
I just cloned and built the latest version, and it looks like the crash was fixed in the next commit after the beta release (fc33e602).

I was also able to fix my problem with the script failing to run. It turns out that I was misinterpreting the purpose of the "bash" keyword. I thought it meant "run the following in bash", but it is really "define the path to your preferred shell". The "param" keywords are actually what gets run.

I was able to get this script to work:
```
#!/bin/bash
echo "title"
echo "---"
echo "test | bash=/bin/bash param1=\"-c\" param2=\"touch /tmp/hello\" terminal=false"
```

I think it would be nice if the "/bin/bash -c" portion of the command were added implicitly. If someone wanted to change to a different shell, it could be configured with a new parameter like "shell_cmd" or something.

I have tested and verified that both of the following work:
```
#!/bin/bash
echo "title"
echo "---"
echo "testscript1 | bash=\"/tmp/test.sh\" terminal=false"
echo "testscript2 | bash=/bin/bash param1=\"-c\" param2=\"/tmp/test2.sh\" terminal=false"
```
"testscript1" follows the convention laid out in the README. Scripts are run directly as executables, which is why they work without the "/bin/bash -c". Note that this only works if the shell is defined at the top of the script. "testscript2" verifies that adding the "/bin/bash -c" works for both scripts and inline bash. 

I would be happy to do the work to make this change and file a pull request, but I'm sure that it would break somebody's use-case. Let me know what you think.

**Comment by willyt** [comment]
Ah!! OK. Its working fine for me now that I know that the params need to be specified separately. This is not explained on the home page so its maybe a documentation bug. 

Also in reply to mwallace582 above, I think strictly speaking the `bash` parameter is absolute path to the executable and the params are arguments to that executable. If you `chmod +x` your bash script you wouldn't need to specify `bash=/bin/bash` as the shebang at the top of your file would do this for you.

**Comment by matryer** [comment]
I would appreciate a PR to improve docs? And I’ll do another BETA release today.

**Comment by matryer** [comment]
Here's 1.5 beta 2 release: https://github.com/matryer/bitbar/releases/tag/v1.5.0-beta2

**Comment by mwallace582** [comment]
Sure. I'll file a pull request to improve the docs tonight.

**Comment by mwallace582** [comment]
Looks like willyt fixed the docs already. I'll close this now.
