### ISSUE TITLE
Run script when pressing menubar item itself

### ISSUE THREAD

**Issue by mvberkum** [matryer/bitbar#210]
Starting to use Bitbar today, great idea. Was searching for a way to run a script when pressing (part) of the menubar item itself. Use case for example; I want to have a simple menu bar item where I can pause/continue iTunes with 1 click instead of 2 (1 to open the menubar item, 1 to click inside the menu).

**Comment by iosdeveloper** [comment]
You could possibly use HTML plugin with JS, although those are not documented at all.

Example: https://gist.github.com/muhqu/8891318/6c3a5d987e2e2753de9e154cc98d43ea0d6ddde0#file-htmlplugin-peity-demo-html-L40
Found in #4.

**Comment by matryer** [comment]
The reason that's not documented is because I'm not 100% sure about it.

**Comment by iosdeveloper** [comment]
Happy to implement once we agreed on the specifics i.e. does it run the script when `bash` is specified instead of showing the menu or does it do both?

**Comment by sarim** [comment]
This would be very useful, also should have option to have run different commands for different clicks, like Right-Click, Cmd+Click, Opt+Click etc...

It seems like for now it can be done using that html/webview, but how to run system commands from html file?
