### ISSUE TITLE
Font family and size set, no changes.

### ISSUE THREAD

**Issue by alesf** [matryer/bitbar#22]
Example:
something | color=#ff0000 size=10 font=Tahoma
something | color=#ff0000 size=10
something | color=#ff0000 font=Tahoma

Color is set correctly, but size and font attributes do nothing.
I've read that something changed in method fontWithName:size: in Yosemite or it got deprecated. Maybe that's the case.

**Comment by majodev** [comment]
+1 - Also doesn't work in El Capitan.

**Comment by LaurentFough** [comment]
+1 Tried several different methods.
No luck.

**Comment by matryer** [comment]
It seems like more recent Mac OS X versions don't support this.

**Comment by taylorzane** [comment]
Try wrapping your font in quotes. I was able to get version 1.4beta working on OS X 10.10.5 (Yosemite).

This still sounds like a bug with the setup of the `fontWithName:size:` method, though.

**Comment by alesf** [comment]
It works in latest master version (1.4) on El Capitan.
Quotes are logically only needed when there is a space in font name.

Additionally I've made a PR for font validation that checks if font exists on the system.

**Comment by rrggrr** [comment]
Could be because I'm calling it before executing a python script, but cannot specify any font. Without fixed-width font its difficult (impossible) to display tabular data.

**Comment by dzg** [comment]
So any way currently to use mono font with python script?
