### ISSUE TITLE
PluginTest is broken

### ISSUE THREAD

**Issue by iosdeveloper** [matryer/bitbar#220]
https://github.com/matryer/bitbar/blob/b301e2a688908b90017d5941f63be0aa195cbf95/App/BitBarTests/PluginTest.m#L196 throws
> Property `allContentLinesAfterBreak` not found on object of type `Plugin *`

**Comment by vogonistic** [comment]
I see these thing as well:
- The tests starts the app, but are only testing logic
- They rely on a hardcoded path to find the tests
- The tests seem to have not been updated as behavior has changed

Any interest in a PR or is someone working on this already?

**Comment by matryer** [comment]
Would love a PR on this.

**Comment by iosdeveloper** [comment]
Thanks @vogonistic!
