### ISSUE TITLE
Refresh separately?

### ISSUE THREAD

**Issue by hanwentao** [matryer/bitbar#221]
Currently bitbar refreshes all enabled plugins simultaneously.  Is it possible to support refreshing an individual plugin?

**Comment by mm2270** [comment]
Its possible to do this now using the `refresh=true` syntax within the plug-in. For example, I have a plug-in that has the following line at the end of the `echo` that creates the menu items.

```
---
Refresh information | refresh=true
```
That shows up in the menu at the end as "Refresh information" When that's selected, it refreshes the information for only that plug-in but leaves others as is. The menu title or icon will temporarily change to the words "Updating..." but again, only for that one plug-in, not others that are loaded.

OTOH, if you choose the **Refresh** command in the Preferences submenu, that reloads all plug-ins. That appears to be a global "refresh" command.
