### ISSUE TITLE
"Open in BitBar" button

### ISSUE THREAD

**Issue by iosdeveloper** [matryer/bitbar#222]
What are your thoughts on adding an "Open in BitBar" button to each plugin on the homepage that passes the URL of the plugin to the app via a custom URL scheme. The app would then download the plugin, write it to the plugins directory, ensure it is executable and refresh the app. Since all listings go through an audit process this should be safe and convenient at the same time. GitHub uses a similar setup to open the GitHub Desktop app from a repository and pull it: `github-mac://openRepo/https://github.com/matryer/bitbar`.

**Comment by iosdeveloper** [comment]
As outlined above, #224 adds the custom url scheme `bitbar://openPlugin/https://github.com/matryer/bitbar-plugins/raw/master/..`.

![screenshot](https://cloud.githubusercontent.com/assets/655921/13036764/8b9f5fa4-d370-11e5-86e5-4fc8eb6a7150.png)

If the plugin is at [matryer/bitbar-plugins](https://github.com/matryer/bitbar-plugins) only the filename appears in the prompt else the full URL.

**Comment by matryer** [comment]
I love this, will have a proper look ASAP.

**Comment by matryer** [comment]
Minor thing, could the URL be like this: `bitbar://openPlugin?src= https://github.com/matryer/bitbar-plugins/raw/master...`? Feels more correct to me, and also avoids/clears up any escaping issues that might arise?

**Comment by iosdeveloper** [comment]
:+1:
