### ISSUE TITLE
where is the bitbar plugin folder and what is the easiest way to integrate the plugins repo with it

### ISSUE THREAD

**Issue by oshai** [matryer/bitbar#225]
It would be nice if there is a page to explain that, couldn't find such.

**Comment by iosdeveloper** [comment]
https://github.com/matryer/bitbar/blob/b301e2a688908b90017d5941f63be0aa195cbf95/READ
E.md#using-symlinks

**Comment by oshai** [comment]
SO the example says: cd Plugins/Enabled
Is this from the home dir or where exactly?

**Comment by iosdeveloper** [comment]
From your clone of the plugins repo.

**Comment by oshai** [comment]
how is bitbar knows where I cloned the plugins repo?

**Comment by iosdeveloper** [comment]
Preferences > Change Plugin Folder.

**Comment by oshai** [comment]
Thanks, got it. just had to run bitbar somehow then it asked me for the
plugin folder.
