### ISSUE TITLE
Bash scripts not running

### ISSUE THREAD

**Issue by axeloz** [matryer/bitbar#228]
Hello, 

I'm trying to create my own plugin for vagrant (attached). 
The menu works well among its items. It lists the vagrant VMs and for each VM, its status. Depending on the status, you may start, stop, resume, reload or suspend. 

**I'm using Perl** (I had to rename the file as txt as Github refuses the pl attachments). If called without any argument, it shows the menu. If called with arguments (action and vagrant environment path), it runs the action. When I call the script from my terminal with the arguments (ie: ./vagrant.2m.pl up /Users/axel/vagrant, the VM boots. But when I click the "Start" menu item, nothing happens. 

When I call my script from terminal without argument, it shows the menu with the right menu items:
axel$ ./vagrant.2m.pl
Vagrant [0]
🚫 Machine 3ff357e is stopped | size=14 color=red
▶️ Start 3ff357e | size=12 bash="/Users/axel/Documents/BitBar/vagrant.2m.pl" param1=up param2="/Users/axel/Sites/vagrant" terminal=false refresh=true

I must mention that the scripts are working when "terminal=true" only if the Terminal app is not launched OR if it is launched with an opened window. 
However, if Terminal is launched but I closed the Terminal window (without closing the app), the scripts don't work again. Also, the refresh doesn't work.

I'm sure I do something wrong but I can't figure out what. If you have any idea?
Thanks a lot,

Axel
[vagrant.2m.txt](https://github.com/matryer/bitbar/files/132912/vagrant.2m.txt)

**Comment by axeloz** [comment]
When debugging in XCode, I'm close to a solution. At least, I get the error. Message is:

> Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.

I just have to figure out how to call the Vagrant binary to make it locate the VBoxmanage. 
Any idea?

Thanks

**Comment by morgrowe** [comment]
Have you tried updated your PATH variable? Not sure how you'd do this in Perl, but you do it by adding this line to the start of a BASH script:

PATH=$PATH:/usr/local/bin/

Morgan

**Comment by axeloz** [comment]
Hello @morgrowe,

Thanks, yes I tried to :
`my $PATH = $ENV{PATH}`
and 
`system("export PATH=$path && ...")` when runnnig the action

I have also tried:
`system("echo PATH>/Users/axel/Desktop/test.txt && cd $ARGV[1] && $vagrant $ARGV[0]");`
The text file is created and contains the correct PATH. So this is strange Vagrant can't locate VBoxManage.

**Comment by axeloz** [comment]
I got it working. At last !!
For some reason, when running the main script (displaying the menu bar), my PATH was:

`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
But when launching an action, my PATH was:
`/usr/bin:/bin:/usr/sbin:/sbin`

So that could not work as "VBoxManage" is stored into /usr/local/bin. So I had to rebuild the PATH and export it. 

Thanks @morgrowe 
I update the script on Github and start a pull request.

Kind regards,

Axel
