### ISSUE TITLE
Potential leak?

### ISSUE THREAD

**Issue by matryer** [matryer/bitbar#235]
<img width="763" alt="screen shot 2016-02-17 at 11 14 22" src="https://cloud.githubusercontent.com/assets/101659/13107855/b3b497b8-d567-11e5-9c69-8c678ad8d0c7.png">

**Comment by matryer** [comment]
Running Analyze on the project pops this up.

**Comment by iosdeveloper** [comment]
Fix is here: #227

**Comment by iosdeveloper** [comment]
@ksuther Do you want to submit a PR pointing the submodule to your fork?

**Comment by ksuther** [comment]
@iosdeveloper Done.
