### ISSUE TITLE
Advanced items should be hidden behind Option key

### ISSUE THREAD

**Issue by matryer** [matryer/bitbar#236]
The advanced items should only be visible when option+clicking the BitBar menu item.

Everything under the system separator should otherwise be invisible:

<img width="250" alt="screen shot 2016-02-17 at 11 25 07" src="https://cloud.githubusercontent.com/assets/101659/13108136/35af8f4c-d569-11e5-9232-37be10ef64e4.png">

**Comment by iosdeveloper** [comment]
Fix is here: #227

**Comment by iosdeveloper** [comment]
I'm not sure about this one. Preferences are already hard to find (#225). Why make it harder? Instead I suggest a defaults flag that can be set from the command line for deployment.

**Comment by mm2270** [comment]
I'm in agreement with @iosdeveloper. I think a defaults flag to the bitbar plist would make more sense for this. As was already mentioned in #180 by @morgrowe its trivial to discover the Option key trick. I'd rather be able to hide the advanced items menu with a defaults setting myself. This would allow regular users of BitBar to be able to set this themselves if they'd rather not see the advanced menu items, and allow Mac administrators to set this programmatically at deployment time.
This could potentially even be "managed" with a custom Configuration Profile so it can't be easily overridden.
