### ISSUE TITLE
Refresh doesn't work when also using bash

### ISSUE THREAD

**Issue by SCdF** [matryer/bitbar#244]
Clicking the result of this output:
```
echo "Refresh | refresh=true 
```
Will re-run the script and refresh the content. Clicking the result of this output:
```
echo "Refresh | refresh=true bash=echo param1=hello";
```
Will run `echo hello` in bash and not re-run and refresh the content.

It would be really useful if this worked. Specifically, if the refresh occurred after the bash command had completed. This would allow (for example) the brew update checking script to clear itself back to zero once you've updated.

**Comment by iosdeveloper** [comment]
This is a known issue (#216). Try with `terminal=false`.
