### ISSUE TITLE
BitBar crashes with unhandled exception NSInvalidArgumentException

### ISSUE THREAD

**Issue by coodix** [matryer/bitbar#246]
BitBar launches normally without ant plugins but after I add any of them it crashes right after launch.

Here is error message from Console:

19/02/16 12:22:24,224 BitBar[65570]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSURLResponse statusCode]: unrecognized selector sent to instance 0x1042005b0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff9d2f8ae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff9ce2ef7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9d2fbb9d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff9d234601 ___forwarding___ + 1009
	4   CoreFoundation                      0x00007fff9d234188 _CF_forwarding_prep_0 + 120
	5   BitBar                              0x00000001000157b9 -[AHProxySettings autoDetectedProxies] + 475
	6   BitBar                              0x000000010001669b -[AHProxySettings proxyForType:] + 807
	7   BitBar                              0x0000000100015d7f -[AHProxySettings taskDictionary] + 95
	8   BitBar                              0x0000000100006b3f -[NSTask(useSystemProxies) useSystemProxiesForDestination:] + 117
	9   BitBar                              0x0000000100005647 -[ExecutablePlugin refreshContentByExecutingCommand] + 284
	10  BitBar                              0x0000000100005b0c __27-[ExecutablePlugin refresh]_block_invoke + 29
	11  libdispatch.dylib                   0x00007fff9a699871 _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x00007fff9a68e33f _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x00007fff9a6921cf _dispatch_root_queue_drain + 1890
	14  libdispatch.dylib                   0x00007fff9a691a34 _dispatch_worker_thread3 + 91
	15  libsystem_pthread.dylib             0x00007fff8e42b68f _pthread_wqthread + 1129
	16  libsystem_pthread.dylib             0x00007fff8e429365 start_wqthread + 13
)

**Comment by iosdeveloper** [comment]
Which version of OS X are you running?

**Comment by matryer** [comment]
Which plugin did you add?

**Comment by coodix** [comment]
Version 10.11.3 El Capitan

**Comment by iosdeveloper** [comment]
This is an issue in our dependency `AHProxySettings`. Can you please open an issue there too? https://github.com/eahrold/AHProxySettings/issues
In your case `resp` isn't of `NS*HTTP*URLResponse` therefore doesn't respond to statusCode and throws this exception. https://github.com/eahrold/AHProxySettings/blob/56eac25826832370fa112a28476df6b188b0618c/AHProxySettings/AHProxySettings.m#L107-L110

**Comment by coodix** [comment]
@matryer , I've tried https://getbitbar.com/plugins/System/Battery/battery_cycles.12h.sh and https://getbitbar.com/plugins/System/lock-screen.10h.sh. It seems that there is an issue outside from the plugins.

@iosdeveloper , thanks! Is it possible to bypass this issue by using special version of AHProxySettings or any other ways?

**Comment by iosdeveloper** [comment]
@coodix My PR was merged. Can you try building from source until we provide an updated release?

**Comment by coodix** [comment]
Cloned and initiated submodules:

➜  Work  git clone https://github.com/matryer/bitbar.git
Cloning into 'bitbar'...
remote: Counting objects: 2594, done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 2594 (delta 31), reused 1 (delta 1), pack-reused 2537
Receiving objects: 100% (2594/2594), 3.35 MiB | 1.86 MiB/s, done.
Resolving deltas: 100% (1474/1474), done.
Checking connectivity... done.
➜  Work  cd bitbar
➜  bitbar git:(master) git submodule init && git submodule update
Submodule 'App/Vendor/AHProxySettings' (https://github.com/eahrold/AHProxySettings.git) registered for path 'App/Vendor/AHProxySettings'
Submodule 'App/Vendor/DateTools' (https://github.com/MatthewYork/DateTools.git) registered for path 'App/Vendor/DateTools'
Submodule 'App/Vendor/LaunchAtLoginController' (https://github.com/mralexgray/LaunchAtLoginController--with-ARC-.git) registered for path 'App/Vendor/LaunchAtLoginController'
Submodule 'App/Vendor/STPrivilegedTask' (https://github.com/sveinbjornt/STPrivilegedTask.git) registered for path 'App/Vendor/STPrivilegedTask'
Cloning into 'App/Vendor/AHProxySettings'...
remote: Counting objects: 55, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 55 (delta 0), reused 0 (delta 0), pack-reused 50
Unpacking objects: 100% (55/55), done.
Checking connectivity... done.
Submodule path 'App/Vendor/AHProxySettings': checked out 'ac09acc27e2f38c6079081a5d5bd151c6ebb0b46'
Cloning into 'App/Vendor/DateTools'...
remote: Counting objects: 1494, done.
remote: Total 1494 (delta 0), reused 0 (delta 0), pack-reused 1494
Receiving objects: 100% (1494/1494), 305.60 KiB | 428.00 KiB/s, done.
Resolving deltas: 100% (866/866), done.
Checking connectivity... done.
Submodule path 'App/Vendor/DateTools': checked out 'bf49844aaf49d6d0eeebcdf4b1bb2c56439c30fd'
Cloning into 'App/Vendor/LaunchAtLoginController'...
remote: Counting objects: 20, done.
remote: Total 20 (delta 0), reused 0 (delta 0), pack-reused 20
Unpacking objects: 100% (20/20), done.
Checking connectivity... done.
Submodule path 'App/Vendor/LaunchAtLoginController': checked out '6c3fed3d512b48ed7bdf48bc50710bc7165f0e3f'
Cloning into 'App/Vendor/STPrivilegedTask'...
remote: Counting objects: 144, done.
remote: Total 144 (delta 0), reused 0 (delta 0), pack-reused 144
Receiving objects: 100% (144/144), 82.74 KiB | 0 bytes/s, done.
Resolving deltas: 100% (56/56), done.
Checking connectivity... done.
Submodule path 'App/Vendor/STPrivilegedTask': checked out 'e5920d30f31184b1a6d30e64507e554388cf1d56'

Compile&run:

2016-02-20 10:59:31.675 BitBar[68301:24790594] -[NSURLResponse statusCode]: unrecognized selector sent to instance 0x618000000af0
2016-02-20 10:59:31.676 BitBar[68301:24790594] An uncaught exception was raised
2016-02-20 10:59:31.676 BitBar[68301:24790594] -[NSURLResponse statusCode]: unrecognized selector sent to instance 0x618000000af0
2016-02-20 10:59:31.676 BitBar[68301:24790594] (
	0   CoreFoundation                      0x00007fff9d2f8ae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff9ce2ef7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9d2fbb9d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff9d234601 ___forwarding___ + 1009
	4   CoreFoundation                      0x00007fff9d234188 _CF_forwarding_prep_0 + 120
	5   BitBar                              0x0000000100015811 -[AHProxySettings autoDetectedProxies] + 475
	6   BitBar                              0x00000001000166f3 -[AHProxySettings proxyForType:] + 807
	7   BitBar                              0x0000000100015dd7 -[AHProxySettings taskDictionary] + 95
	8   BitBar                              0x0000000100006cb7 -[NSTask(useSystemProxies) useSystemProxiesForDestination:] + 117
	9   BitBar                              0x00000001000057bf -[ExecutablePlugin refreshContentByExecutingCommand] + 284
	10  BitBar                              0x0000000100005c84 __27-[ExecutablePlugin refresh]_block_invoke + 29
	11  libdispatch.dylib                   0x0000000100085fa4 _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x0000000100078bf9 _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x000000010007d38b _dispatch_root_queue_drain + 2934
	14  libdispatch.dylib                   0x000000010007c7d9 _dispatch_worker_thread3 + 106
	15  libsystem_pthread.dylib             0x00000001000db458 _pthread_wqthread + 1129
	16  libsystem_pthread.dylib             0x00000001000d8fad start_wqthread + 13
)
2016-02-20 10:59:31.722 BitBar[68301:24790594] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSURLResponse statusCode]: unrecognized selector sent to instance 0x618000000af0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff9d2f8ae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff9ce2ef7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9d2fbb9d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff9d234601 ___forwarding___ + 1009
	4   CoreFoundation                      0x00007fff9d234188 _CF_forwarding_prep_0 + 120
	5   BitBar                              0x0000000100015811 -[AHProxySettings autoDetectedProxies] + 475
	6   BitBar                              0x00000001000166f3 -[AHProxySettings proxyForType:] + 807
	7   BitBar                              0x0000000100015dd7 -[AHProxySettings taskDictionary] + 95
	8   BitBar                              0x0000000100006cb7 -[NSTask(useSystemProxies) useSystemProxiesForDestination:] + 117
	9   BitBar                              0x00000001000057bf -[ExecutablePlugin refreshContentByExecutingCommand] + 284
	10  BitBar                              0x0000000100005c84 __27-[ExecutablePlugin refresh]_block_invoke + 29
	11  libdispatch.dylib                   0x0000000100085fa4 _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x0000000100078bf9 _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x000000010007d38b _dispatch_root_queue_drain + 2934
	14  libdispatch.dylib                   0x000000010007c7d9 _dispatch_worker_thread3 + 106
	15  libsystem_pthread.dylib             0x00000001000db458 _pthread_wqthread + 1129
	16  libsystem_pthread.dylib             0x00000001000d8fad start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by coodix** [comment]
Looks like submodule AHProxySettings submodule pulled old version.

**Comment by iosdeveloper** [comment]
Indeed.

Submodule path 'App/Vendor/AHProxySettings': checked out 'ac09acc27e2f38c6079081a5d5bd151c6ebb0b46'

Should be

'5277c9f786afa38dd6f4e680f054bbbec3715139'

**Comment by coodix** [comment]
It's working now. Just updated submodule.

**Comment by iosdeveloper** [comment]
v1.6.0 fixes this.
