### ISSUE TITLE
Run in Terminal doesn't handle paths with spaces

### ISSUE THREAD

**Issue by ohmantics** [matryer/bitbar#253]
I tried putting my plugins under ~/Library/Application Support/BitBar.

**Comment by tresni** [comment]
@iosdeveloper You may want to look at #130 which was inappropriately closed.  The "just double backslash" could still lead to issues with other characters.  Telling to use the [POSIX path](https://github.com/tresni/bitbar/commit/a847f43) should alleviate both the space and other possible "bad character" issues (e.g. question marks, backslashes, etc.)

**Comment by iosdeveloper** [comment]
@tresni Do you want to submit a PR?
