### ISSUE TITLE
Doesn't run command line if Terminal not open on 10.10.5

### ISSUE THREAD

**Issue by sylvainbaronnet** [matryer/bitbar#255]
If the terminal is not open, command line are not executed. If I open it before, it works correctly

bitbar version 1.6

**Comment by iosdeveloper** [comment]
I saw this too. If we are fine with not running the command in a new window, we can use the same code as "Run in Terminal" which doesn't have this issue.

**Comment by sylvainbaronnet** [comment]
Actually there's a case where it should open a new window : if the previous command line is not done. 
For example a Gulp watch command. If I launch this command, next commands doesn't work. So currently I don't use it.

I don't know technical possibilities but the best behaviour IMO is :
- Terminal not open -> open Terminal with new window
- Terminal open with no window open -> open a new window
- Terminal open with a command line running -> open a new window
- Terminal open with a window and no command line running -> use this window

**Comment by iosdeveloper** [comment]
Do you know if this is possible? The code uses AppleScript.

**Comment by iosdeveloper** [comment]
https://github.com/matryer/bitbar/blob/master/App/BitBar/Plugin.m#L205-L211

**Comment by sylvainbaronnet** [comment]
I don't know AppleScript very well but I'm almost certain that it's not possible to detect if a bash script is running.

I will think about it, I let you know if I have an idea

**Comment by iosdeveloper** [comment]
Maybe we should always open a new window as this seems to cover most cases.

**Comment by sylvainbaronnet** [comment]
yes seems the best option.

On the plugin side it's still possible at the end of a command line to close the window (exit) or even the terminal (osascript -e 'quit app ...).
