### ISSUE TITLE
Python script says module is missing but when run in terminal its fine

### ISSUE THREAD

**Issue by digitalfiz** [matryer/bitbar#256]
So I had to reinstall boto at one point in time and it seems to have broken bitbar but even after restarts and refreshes it doesn't work in bitbar but when I tell it to run from terminal its fine.

Is there some kind of caching I don't understand going on?

here is a screenshot: [http://i.imgur.com/j8PfBYe.png](http://i.imgur.com/j8PfBYe.png)

The terminal version was initiated via "Run in terminal" from bitbar.

**Comment by tresni** [comment]
Any chance you are using Homebrew or Macports?  I'm betting it's a $PATH issue...  Bitbar is getting system path/system python, terminal is getting your set path/python.

**Comment by digitalfiz** [comment]
Yeah it was Homebrew. Guess it was dumb luck that it was fine before the reinstall of boto. I pointed the script to /usr/local/bin/python which is symlinked to ../Cellar/python/2.7.11/bin/python and it fixed it.

I was using env to determine the python location. Thanks lol
