### ISSUE TITLE
Run in Terminal not escaping paths

### ISSUE THREAD

**Issue by smathieson** [matryer/bitbar#265]
There is a small bug with the "Run in Terminal..." command. When the path to the directory contains a space (and I imagine other special characters) these are not escaped and the command is not executed.

Typical output is:
/Users/samuel/Documents/BitBar Plugins/updates.1h.sh
-bash: /Users/samuel/Documents/BitBar: No such file or directory

Needs a small fix.

Thanks for a great app!

**Comment by iosdeveloper** [comment]
This has been fixed on master already. See #253

**Comment by smathieson** [comment]
Oh, thanks, sorry. Will dl master.

**Comment by jonaswouters** [comment]
Actually special characters is not fixed with that change. 
Having the configuration folder in a dropbox for business folder will not work.
For example `homefolder/Dropbox (Company Inc)/BitBar`
