### ISSUE TITLE
Image parameters do not work in v1.6.0 release

### ISSUE THREAD

**Issue by myhd** [matryer/bitbar#267]
Newly added parameters _templateImage=.._ and _image=.._ for items do not work in the 1.6.0 release. I tested this in OSX 10.9.5. and 10.11.3. However, they are referenced in the documentation at https://github.com/matryer/bitbar. Could you release a new version?

**Comment by iosdeveloper** [comment]
This is expected. master is ahead of v1.6.0.

**Comment by crcastle** [comment]
Any thoughts on when a new release will happen? Thanks for all your work on this! I love the simplicity of bitbar.

**Comment by myhd** [comment]
@iosdeveloper Bitbar is so great! I could not wait for the next release, so I <i>git clone</i>d the current master and tried to build it in XCode (Both 10.9 and 10.10) — could not get it to compile. Any ideas what one (non-developer) would need for a successful build to happen?

**Comment by iosdeveloper** [comment]
@myhd What is the error? You probably forgot to `git submodule init && git submodule update` (I wonder why this keeps coming up...).

**Comment by myhd** [comment]
@iosdeveloper You are so right. Thank you for the direction.

I must say I did not see the build info in the README, probably because it is under _Contributing_, and I did not want to contribute, but just build — or _get_ — the newest version. Perhaps it is worth considering to put the build info somewhere else?
