### ISSUE TITLE
Vertical text alignment is off on 10.9.5

### ISSUE THREAD

**Issue by myhd** [matryer/bitbar#268]
Menu bar item text (not icon positioning) is off by one pixel / 4.8% on OSX 10.9.5. Please see screenshot.

![off_by_one_10_9_5](https://cloud.githubusercontent.com/assets/1010447/13697972/6a7ac3e4-e771-11e5-9763-713c80620f08.png)

**Comment by iosdeveloper** [comment]
See #105

**Comment by matryer** [comment]
Thanks for the report - this bugs me too... anyone fancy taking a look at a fix?

**Comment by matryer** [comment]
Duplicate of #105
