### ISSUE TITLE
Add support for `:emoji:` syntax

### ISSUE THREAD

**Issue by vogonistic** [matryer/bitbar#269]
It'd be neat to support `:emoji:` to unicode translation. There are projects that extends NSString to add the functionality, so it's just about integrating it.

If you think it's a good idea. I can prepare a PR.

https://github.com/diy/nsstringemojize

**Comment by iosdeveloper** [comment]
What is the use case? You can just output the unicode character.

**Comment by vogonistic** [comment]
I show data from github and gitlab which sometimes they contain emoji references. I also think they are easier to write in that syntax rather than looking through the emoji lists.

**Comment by vogonistic** [comment]
It could also be implemented as something that needs to be turned on by a parameter.

**Comment by iosdeveloper** [comment]
I think this should be implemented by the plugins if needed to avoid any unwanted side effects.

**Comment by iosdeveloper** [comment]
Could be enabled per line by a parameter like `:emoji: | emojize=true`.

**Comment by vogonistic** [comment]
I think that would work pretty well. Would be nice to enable once for a whole plugin, but as far as I can tell  that kind of functionality doesn't exist.

**Comment by matryer** [comment]
Why not _always_ do this? Rather than asking plugin developers to have to enable it?

**Comment by iosdeveloper** [comment]
I kind of agree with @matryer. Too many options over complicate things. Maybe we just do without. Same for #272.

**Comment by vogonistic** [comment]
I've changed it so it's always on now, with a parameter `emojize=false` in case someone needs to have it turned off.

I could move that to a list of more obscure parameters so it doesn't overwhelm the list with important parameters.
