### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by matryer** [matryer/bitbar#27]
@mralexgray - after merging your changes, my BitBar build is broken. Probably something trivial, so I thought I'd ask before digging too deeply into it.

<img width="1072" alt="brokenbitbar" src="https://cloud.githubusercontent.com/assets/101659/12062507/c82abe9a-af95-11e5-813a-74332d9810ef.png">

**Comment by matryer** [comment]
Any help or advice would be much appreciated.

**Comment by jcaille** [comment]
It seems that removing the .pch files did not play nice with the Submodule. However, @mralexgray has updated the reference. It should be a simple matter of running 

`git submodule update --remote --merge`
