### ISSUE TITLE
Bug? Dividers --- in submenus?

### ISSUE THREAD

**Issue by JayBrown** [matryer/bitbar#281]
First of all: Thank you for the submenu function. It's wonderful.

Question: Is there a way to add a divider with $ echo "---" into a submenu and sub-submenu, as in other standard OS X menu items?

I tried a couple of different echos in this regard, but it only messes up the menu. But maybe I missed something. (?) If it's not implemented yet, I guess BitBar only needs to check if a line $ echo "---" is between two submenus or sub-submenus, i.e. either between two instances of $ echo "--TEXT" or between two instances of $ echo "----TEXT".

PS: There might be a bug when combining (sub-) submenus with alternate=true-lines. Will check and post about it later.

**Comment by iosdeveloper** [comment]
Currently separators are always added to the main menu. I'm not sure about the right syntax for separators in submenus. It is not as simple as "only needs to check if it is between submenus" because the parser currently doesn't have this context. What do you think about prefixing `---` with `--` per level?

**Comment by JayBrown** [comment]
That's one of the things I've tried, but it messed up the menu. That could be rectified, I assume, but to my knowledge it would also mean that BitBar might interpret $ echo "-----" (5 dashes) wrongly: it might not see it as a 3+2, i.e. as an echo for a divider in the first-level submenu, but as 1 dash (to be echoed out) in the second-level submenu, i.e. as a 2+2+1. (?)

**Comment by iosdeveloper** [comment]
Currently `-----` results in an item with the text `---` in a first-level submenu. It depends on how we implement it.

**Comment by JayBrown** [comment]
Okay. I don't (and probably everyone else doesn't) need dividers in the second-level, so I would be fine with $ echo "-----".

**Comment by JayBrown** [comment]
Addendum: in my case ----- only results in one dash (-) in the second-level submenu.

I would also check how the submenu function works together with alternate=true-lines. I'm using lots of menus and submenus, each with alternate=true, even one alternate=true in a 2nd-level-submenu. It's probably important, where you enter the divider, either between the main and the alternate line, or after the alternate line.

By the way: There's also a bug, namely that the arrows pointing to the submenus disappear when you press [ALT] to call the alternate=true-lines. And you have to navigate into the submenu first before you can click [ALT]. You can't click [ALT] and only _then_ navigate into a submenu.

**Comment by iosdeveloper** [comment]
I think the documentation is pretty clear that an `alternate=true` line affects the line directly above it. So separators should come **after** it. If you see different results please let us know.

**Comment by JayBrown** [comment]
Well, it's a funny thing with alternate=true. I have to put a submenu-echo (and its alternate) _between_ the main and the alternate line of the parent-menu, otherwise that submenu will only appear when I press [ALT], which is a nice functionality, by the way; I don't see it as a bug. But that behavior might have to be taken into account when working on separators for submenus.

**Comment by iosdeveloper** [comment]
I guess you mean something like
```
Main menu
Main menu alt | alternate=true
--Submenu
```
only shows the submenu when you press alt, so you had to use something like
```
Main menu
--Submenu
Main menu alt | alternate=true
```
Right?

**Comment by JayBrown** [comment]
Correct. So my setup is (mostly) like this:

```
Main menu | href=
--Submenu | href=
----Subsubmenu | href=
----Subsubmenu alt | alternate=true bash=
--Submenu alt | alternate=true bash=
Main menu alt | alternate=true bash=
```

**Comment by iosdeveloper** [comment]
I don't know if this should be declared a bug or a feature but a submenu attaches to the item directly above it, so to always show the submenu something like this should work:
```
Main menu
--Submenu
Main menu alt | alternate=true
--Submenu
```

**Comment by JayBrown** [comment]
That's fine. It's just a couple of extra lines.

**Comment by JayBrown** [comment]
It would then also get rid of the missing arrow thing. All the user has to do is to copy the whole submenu- and subsubmenu-echos and paste them after the master-parent alternate line. (!)

**Comment by iosdeveloper** [comment]
You could assign your submenu to a variable in your script and just output it twice or don't use `alternate=true`. ;)

**Comment by JayBrown** [comment]
:D Well, the alternate=true bit is only temporary. I'm running an auxiliary script so the user can input search terms, which are then sent to the browser (search.php on a website). For that I need the ALT. The default line is just a href to a webpage, and the ALT is searching for a string on that webpage. So when one day BitBar includes a native search option, alternate=true will go out the window for sure. Until then I have to use a workaround.

**Comment by iosdeveloper** [comment]
Added with 93bd073

**Comment by matryer** [comment]
We OK to close this?
