### ISSUE TITLE
Check for latest version

### ISSUE THREAD

**Issue by iosdeveloper** [matryer/bitbar#283]
Indicate a newer release in the version menu item and link to the release.

https://api.github.com/repos/matryer/bitbar/releases/latest

**Comment by mm2270** [comment]
Curious, but will these updates show up if `userConfigDisabled` is set to `true` in the plist? I'm hoping the answer is no in this case.

**Comment by iosdeveloper** [comment]
@mm2270 No. :)

**Comment by mm2270** [comment]
@iosdeveloper OK, great, thanks! And thanks for the continued work on improving BitBar. I'm really loving all the latest enhancements! :)
