### ISSUE TITLE
Multiple instances of a single script

### ISSUE THREAD

**Issue by johnflan** [matryer/bitbar#289]
Occasionally bitbar has two instances of my script in the icon tray. I suspect this is related to the computer been put to sleep and waking.

<img width="242" alt="screen shot 2016-03-18 at 01 05 38" src="https://cloud.githubusercontent.com/assets/410657/13865671/af94a0e2-eca5-11e5-923d-4e63b4bbc458.png">

The script is called something like xxx.5m.sh and contains
`#!/bin/bash
/usr/local/bin/wget -q -O- www.some-website.com | grep "a string" | cut -c149-154`

**Comment by iosdeveloper** [comment]
Which version of BitBar did you use (you can find the version under "Preferences").

**Comment by johnflan** [comment]
1.6, from brew cask -- will try upgrading, thanks
