### ISSUE TITLE
New user - can't get past first base [HELP]

### ISSUE THREAD

**Issue by SchmyeBubbula** [matryer/bitbar#290]
I tried BitBar for the first time with a couple of simple Bitcoin price plugins, and I can't get any of them to appear in my menu bar; only an ellipsis icon ("..."). I made sure that my plugins folder was declared, no subfolders within, and made sure that my plugins had their _execute_ flag set for my Owner home account, Group _staff_, and _Everyone_.

Maybe the clue to my problem is, when I did BitBar's _Run in Terminal,_ I got:

`#: bad interpreter: No such file or directorys/Bitstamp_last_price.1m.sh: /bin/bash`

What are some common problems that would cause this?
Mac OS X 10.6.8

**Comment by alesf** [comment]
The script is using `bash` in directory `/bin/` but you don't seem to have it there for some reason.
Run `which bash` in terminal and in the .sh file replace `/bin/bash` from the first line with what `which bash` command returned.

**Comment by SchmyeBubbula** [comment]
Thanks for the reply, **alesf.** This is what I show:

> Last login: Thu Mar 17 15:02:45 on ttys000
> Schmye-Bubbulas-Computer:~ schmye$ which -a bash
> /bin/bash
> Schmye-Bubbulas-Computer:~ schmye$

So I do seem to have _bash_ where it belongs. However, I **_have_** applied the third-party [bash vulnerability update for Mac OS X 10.6.8 Snow Leopard by TenFourFox Development](http://tenfourfox.blogspot.com/2014/09/bashing-bash-one-more-time-updated.html?showComment=1412021577609); maybe that's the problem. Do you by chance know anything about that? Or any other candidates for what's causing my problem?

**Comment by alesf** [comment]
Maybe you corrupted your copy of bash in the process. I don't really know.
What happens if you run `/bin/bash`?
Try to replace `/bin/bash` in the script with `/usr/bin/env bash` (notice the space).

**Comment by SchmyeBubbula** [comment]
What do you mean by, "run /bin/bash"? Do you mean to enter "/bin/bash" in Terminal? I did, and Terminal gave me the prompt:

> bash-4.3$

Also, I replaced in the script's first shebang line your "/usr/bin/env bash" substitution, _to wit:_

> #!/usr/bin/env bash

...and still only get the ellipsis in Bitbar's menu.... When I did BitBar's _Run in Terminal,_ I got:

> Last login: Fri Mar 18 15:30:38 on ttys000
> Schmye-Bubbulas-Computer:~ schmye$ /Users/schmye/Utilities/BitBar/plugins/Bitcoin_Coinbase_spotrate.1m.sh
> env: bash\r\r: No such file or directory
> Schmye-Bubbulas-Computer:~ schmye$

Now what?

**Comment by alesf** [comment]
Those two `\r\r` are peculiar.
/bin/bash is apparently working normally for you so I guess there was no need to change it with /usr/bin/env bash.

What happens when you run `/bin/bash /Users/schmye/Utilities/BitBar/plugins/Bitcoin_Coinbase_spotrate.1m.sh` from Terminal?

**Comment by SchmyeBubbula** [comment]
> Last login: Fri Mar 18 15:34:45 on ttys001
> Schmye-Bubbulas-Computer:~ schmye$ /bin/bash /Users/schmye/Utilities/BitBar/plugins/Bitcoin_Coinbase_spotrate.1m.sh
> Schmye-Bubbulas-Computer:~ schmye$

?? If it worked, was _echo_ supposed to display something in Terminal?

**Comment by SchmyeBubbula** [comment]
> Last login: Fri Mar 18 16:22:27 on ttys000
> Schmye-Bubbulas-Computer:~ schmye$ /bin/bash /Users/schmye/Utilities/BitBar/plugins/Bitcoin_Coinbase_spotrate.1m.sh
> Schmye-Bubbulas-Computer:~ schmye$

?? If it were working, was _echo_ supposed to display something in Terminal? Funny, no error messages.

**Comment by alesf** [comment]
Mine works flawlessly:
```
$ /bin/bash ~/BitBarPlugins/spotrate.10s.sh
BTC: $407.23
$
```

It seems that your bash also works, it's just that the script does not output anything.
Can you even open https://coinbase.com in browser?
What file does this link download for you - [https://coinbase.com/api/v1/prices/spot_rate?currency=USD](https://coinbase.com/api/v1/prices/spot_rate?currency=USD)?

**Comment by SchmyeBubbula** [comment]
Yes, https://coinbase.com opens in Firefox just fine.

https://coinbase.com/api/v1/prices/spot_rate?currency=USD
downloads the file, _response.json_ with contents:

> {"amount":"407.09","currency":"USD"}

Off to inspect my Little Snitch reverse firewall for any entries with which I may be thwarting myself. Stay tuned...

**Comment by SchmyeBubbula** [comment]
Nothing dubious in Little Snitch... which task itself was dubious in the first place, for my _No such file or directory_ errors mean that BitBar isn't even getting so far as to run my scripts, so the question doesn't arise.

I dunno' what next troubleshooting step to take, except soliciting anybody reading this who has gotten BitBar to work in Mac OS X 10.6.8 to confirm, ruling-out some incompatibility.

**Comment by iosdeveloper** [comment]
OS X 10.6 is no longer supported, sorry. What stops you from updating?

**Comment by SchmyeBubbula** [comment]
We understand completely that Apple has made it very hard for developers to support all but the very latest versions of OS X, but this isn't a question of us being too lazy to upgrade, or legacy apps. Rather, it's that Apple has thrown us under the bus, beginning with 10.7, in terms of usability, functionality, and the user-friendly GUI to which we'd become accustomed. Snow Leopard is the Windows XP of Apple: the last OS worth a damn.

For this reason, Snow Leopard's installed base is still greater than that of Lion and Mountain Lion:

https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0

Look at all the other developers who continue to release Snow Leopard-compatible titles every single day!

http://download.cnet.com/mac/3151-20_4-0.html?osNamesExact=Mac+OS+X+10.6

Please reconsider: keep the old Xcode & SDKs around and go to the extra trouble of maintaining Snow Leopard support!

https://www.fastcodesign.com/3053406/how-apple-is-giving-design-a-bad-name

http://www.sciencefriday.com/segments/does-apple-deserve-its-reputation-for-good-design/

http://rixstep.com/2/2/20150910,00.shtml

http://www.mcelhearn.com/apples-software-problems-are-eroding-confidence-in-the-brand/

http://www.cbsnews.com/news/apple-software-quality-keeps-taking-a-hammering/

http://www.mondaynote.com/2015/01/18/apple-software-quality-questions/

http://mjtsai.com/blog/2015/01/06/apples-software-quality-continued/

**Comment by iosdeveloper** [comment]
While I disagree to expose yourself to security vulnerabilities of an OS that old, this is off topic and not the right place to discuss this as we made the decision in #282. I also think you are exaggerating here.

**Comment by SchmyeBubbula** [comment]
> I also think you are exaggerating here.

https://www.youtube.com/watch?v=fLrpBLDWyCI

**Comment by chrisidefix** [comment]
@SchmyeBubbula, is it save to assume that the reason you are not upgrading is that Apple dropped support for the Mac you own and those other "arguments" (regarding bad design decisions) may or may not be true, but in the end, you would have to buy a new Mac? Continuing to support a 7 year old OS that isn't even maintained by Apple any longer, is not a wise decision. Under these circumstances, your better off installing linux on there and moving on from Mac OS X, if you really can't see any benefit in the 5 major releases following OS X 10.6.

I sincerely hope Apple will do better in the future and judging from their recent releases, they have been supporting the same install base for a number of years now, but their decisions did "force" me to upgrade two of my machines, which were (and still are) in perfect working condition.

Either way, I think there are BitBar releases available right here that will continue to work for a while. Ok, they don't get the latest features, but you can still use Bitbar on 10.6 and nobody is going to stop you from doing that, right?

*Alternatively, since this is an OpenSource project - you could also branch off and try to maintain a 10.6 compatible version yourself - yes, it's not easy - but it's not easy for these guys to keep maintaining 10.6 either. If you really think there is a huge demand for 10.6 support, I would recommend to find those people and fork off to continue development.*

**Comment by SchmyeBubbula** [comment]
> 
• "arguments" (regarding bad design decisions)
• your better off installing linux
• you could also branch off and try to maintain a 10.6 compatible version yourself

You profoundly fail grasp the significance of (what once was) the way of the Macintosh platform.
#GUI #UX #UI #GrandmaTest
