### ISSUE TITLE
External refresh command? BitBar listening on localhost UDP port?

### ISSUE THREAD

**Issue by JayBrown** [matryer/bitbar#291]
Maybe I've overlooked something, but I've gotten to the point where I need a non-BitBar process to send a refresh command to a specific BitBar script. To be more precise, I'm using a non-BitBar process to write variables into an sqlite database table, which is also accessed by the BitBar script. However, when that happens, the BitBar script doesn't yet know that the database was updated, so I need the other app to tell the BitBar script that it needs to refresh. Is this already possible? If not, this would be great to have.

In that respect take a look at the AnyBar plugin: https://github.com/tonsky/AnyBar … you can run several AnyBar instances side by side, and each of them listens on its own localhost UDP port. If this were implemented in BitBar, with one port for every script, the user could easily send an external refresh command, something like:

`echo -n "refresh" | nc -4u -w0 localhost 2047`

In the BitBar script you would then only need a way to set the localhost UDP port for that script from the script itself.

This all presupposes that BitBar doesn't have an external-refresh option yet. But as I said, I couldn't find anything.

**Comment by JayBrown** [comment]
Or is this the one? https://github.com/matryer/bitbar/pull/247

**Comment by iosdeveloper** [comment]
https://github.com/matryer/bitbar/raw/master/Docs/#refreshplugin

**Comment by iosdeveloper** [comment]
https://github.com/matryer/bitbar/blob/master/Docs/URLScheme.md#refreshplugin
