### ISSUE TITLE
Bitbar Crashing

### ISSUE THREAD

**Issue by SynVisions** [matryer/bitbar#294]
Not sure if this is related to using Bitbar with Bartender, but Bitbar (v1.8) seems to crash occasionally. I've attached a crash report for anyone to have a look at.

3/19/16 8:48:08.557 AM com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000047.BitBar[21860]) Service exited due to signal: Segmentation fault: 11

[BitBar_2016-03-19-084812_seanmb.crash.zip](https://github.com/matryer/bitbar/files/180879/BitBar_2016-03-19-084812_seanmb.crash.zip)

**Comment by tresni** [comment]
We found a couple issues in the 1.8 release that can lead to crashes in different situations.  The Distro version basically won't really run at all.  We have fixes for all known crashes in place for the next release.  Your crash is addressed.
