### ISSUE TITLE
Bug? Menu lines with color text that contain a submenu don't turn white text on black on highlight

### ISSUE THREAD

**Issue by mm2270** [matryer/bitbar#296]
Hi. I seem to have run into a bug of sorts. I noticed today when building a new menu plug-in that if I colorize text in a menu line and add any submenus to the line, on highlight, the main text does not reverse color. The behavior is correct on non-colored lines, colored lines with NO sub-menu, lines with images attached and all other instances I have tested. The only time the issue above surfaces is with menu lines that have a submenu attached to them AND have a color applied to the text.

Here are some screenshots to show the issue:

This is a normal uncolored line with a submenu. It changes to white text on a dark menu line when selected as it should:
<img width="480" alt="screen shot 2016-03-22 at 1 13 14 am" src="https://cloud.githubusercontent.com/assets/3653600/13942827/e1d887ce-efcc-11e5-817d-fa6158d08862.png">

This is a colored line with a submenu. As you can see, it does not change (reverse) the text color when selected:
<img width="480" alt="screen shot 2016-03-22 at 1 13 17 am" src="https://cloud.githubusercontent.com/assets/3653600/13942843/12509630-efcd-11e5-8d92-fa634faf056c.png">

I thought initially it had something to do with images on the line, but as you can see here, even with no image, but a color applied, if it has a submenu it doesn't change the color when selected:
<img width="480" alt="screen shot 2016-03-22 at 1 13 21 am" src="https://cloud.githubusercontent.com/assets/3653600/13942848/3605c118-efcd-11e5-83e6-139a08b2f5da.png">

I am using the latest version 1.9.0 built from the Xcode project.

**Comment by iosdeveloper** [comment]
Thanks for reporting this! 97d5739 should fix it.

Before submenus were added, the color parameter would only be removed on highlight if an action (`href`, bash`, `refresh`) was set (because otherwise the item was disabled and not highlighted anyway).
