### ISSUE TITLE
Add to homebrew

### ISSUE THREAD

**Issue by sammcj** [matryer/bitbar#30]
It would be great if Bitbar could be added to Homebrew!

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md

**Comment by ekarulf** [comment]
This is already present in Caskroom
https://github.com/caskroom/homebrew-cask/blob/master/Casks/bitbar.rb

I installed it using:
```bash
$ brew cask install bitbar
```

**Comment by sammcj** [comment]
Oh right - didn't think to check for a Cask.

Sorry :/

**Comment by palmerabollo** [comment]
I am getting this error when installing bitbar with brew. Can anyone reproduce it?

```
$ brew cask install bitbar
==> brew cask install Caskroom/cask/bitbar
Error: Cask 'bitbar' definition is invalid: Bad header line: parse failed
```
