### ISSUE TITLE
Possible bug regarding menu bar icon: switching between template image and emoji

### ISSUE THREAD

**Issue by JayBrown** [matryer/bitbar#300]
As a menu bar icon, using a template image works fine. Emoji works fine as well. But combining the two is apparently buggy: I have a script that checks for the status of a website at first; when the site is up, you see the standard icon (templateImage), when the website is offline, I use a big red warning emoji. (Needless to say, the script checks the online/offline status before echoing the menu bar icon.) Now to the bug: when the website was online before, and when it then goes offline, the warning emoji is actually added to the menu bar _alongside_ the default icon, instead of replacing it. The standard (website online) code is:
`echo "| templateImage=$ICON dropdown=false"`
with $ICON defined a couple of lines before (long line of base64). The alternate warning (website offline) code is:
`echo "$WARNING| color=red dropdown=false"`
with $WARNING defined earlier:
`WARNING="❌"`
Maybe there's something wrong with my commands, but I fear that it's more than that. Or is it necessary to add a refresh=true parameter in these cases?

**Comment by iosdeveloper** [comment]
Thanks for reporting this! fb599dd should fix it.

When an image was set once, it was never removed from the status item when the parameter was no longer set.
