### ISSUE TITLE
Can't get BitBar or BitBarDistro versions 1.8.0 or 1.9.0 to work on pre OS X 10.10 if a plist exists

### ISSUE THREAD

**Issue by mm2270** [matryer/bitbar#302]
So, I hate to open this issue, but I've been unable to get BitBar or its BitBarDistro cousin to run on any Macs under 10.7.x or 10.8.x. The issue is that if I use a preconfigured `com.matryer.BitBar.plist`, either located in the root `/Library/Preferences/` directory, or even in `~/Library/Preferences/`, the app launches, shows `...` in the menubar and then closes down. If I delete all references to `com.matryer.BitBar.plist` from the Mac, and launch the app, I get prompted to select my plug-ins directory, which I do, and everything works fine. Meaning, there is nothing wrong with the directory itself or the plug-ins in them. The problem is the app simply won't recognize and honor a plist file made in advance of launching the app and the app creating it on first run.
I had dumped everything and tried using the BitBarDistro version (both 1.8.0 and 1.9.0), copied my plug-ins into the executable directory and it does the same thing. In fact, since its the distro version, I can't even get it to prompt for a directory location. It just crashes.

So you know, I've tried a ton of troubleshooting with this, and absolutely nothing has worked, other than allowing the application to create its own property list on first launch. This doesn't happen on 10.10 or 10.11, and I believe its OK on 10.9 as well, although I still need to check on that.

This is a showstopper for me since I was planning on deploying this to a small number of Macs still on 10.7.x and 10.8.x, but preconfigured to have the `userConfigDisabled` option enabled and a plug-ins directory already set.

Any thoughts on what's going on? I'm puzzled why it won't honor the plist that's already there. I've made sure to even match the owner/group and POSIX permissions on the file as to how the app creates it, as I thought it might be a permissions issue, but its not.
In fact as part of troubleshooting, I simply copied the application created plist into `/Library/Preferences/` and modified the perms slightly so it was readable by all accounts, deleted the original from `~/Library/Preferences/` and launched BitBar - crash. Other than adjusting the permissions, its the exact same plist the app created. I don't get why its not working.

Any help would be greatly appreciated.

**Comment by mm2270** [comment]
Just to add even more weirdness to this, get this one.
I deleted all references to the plist. Launched BitBar, it prompted me to select my Plug-ins Directory. I do and the menu shows up. So far so good. I simply quit BitBar, make no changes to anything else and launch BitBar again, it crashes! WTF? How can it work on first launch but not after? Something is really broken...

**Comment by iosdeveloper** [comment]
Please check if any crash reports are saved under `~/Library/Logs/DiagnosticReports` or similar location on the OS X versions you use.

**Comment by mm2270** [comment]
Will do. I'm doing additional testing to see if I can narrow down the issue a little further for you. As soon as I grab some logs I will post them here.

**Comment by vogonistic** [comment]
Does it also fail if you use `defaults` in the terminal to create the plist file for you? Like this:

```
defaults write com.matryer.BitBar pluginsDirectory /tmp
defaults write com.matryer.BitBar appHasRun -int 1
```

**Comment by mm2270** [comment]
Yes, in fact that's how I'm creating the plist in the first place. Essentially, its being created as part of a postflight script that includes the BitBar.app and plug-ins folder deployed to a system. I'm not copying the plist from a Mac and including it in the pkg. Its creating the plist new with several defaults commands.

I just ran a test on a plain vanilla 10.8.4 system, local account, not joined to a domain or any of the other stuff our Macs typically have on it to rule out anything we may be installing on them. It launches and asks for a plug-in directory, and I select it, but if I quit and relaunch it, it crashes. Crash log is attached here.

[BitBar_2016-03-25-114239_MacBook-Air.crash.zip](https://github.com/matryer/bitbar/files/189756/BitBar_2016-03-25-114239_MacBook-Air.crash.zip)

**Comment by mm2270** [comment]
I edited the title to be more accurate of the issue. Sadly, I'm seeing it also crash (same uncaught exception error) on 10.9.5, so it seems to affect everything pre - 10.10.x, at least for me.

I'm curious if anyone else who may be using it on older OSes is seeing this as well?

**Comment by iosdeveloper** [comment]
From the crash report this looks like you actually set a plugins directory and it contained a plugin. It crashes here:

```
5   BitBar                              0x00000001059ccb3f -[Plugin buildMenuItemWithParams:] + 1184
```

with

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString containsString:]: unrecognized selector sent to instance 0x7fb6998585f0'
``

**Comment by mm2270** [comment]
@iosdeveloper OK, I'm not understanding what you mean. Yes, the dir I selected has at least one plug-in within it. Is it not supposed to? Isn't that what it means to 'select the plug-ins directory'?

And what doesn't make sense is, its fine upon initial selection with no plist present, running on a Mac that I've never run BitBar on. The app runs, plug-in displays OK in the menubar. Its only if I quit and relaunch it that it crashes. I'm not sure I get what that would have to do with selecting a plugins directory and it contained a plugin. If I'm just being dense, please explain it further.

**Comment by iosdeveloper** [comment]
Can you pinpoint it to a specific plugin or does any plugin crash it?

**Comment by mm2270** [comment]
I've tried two different plug-ins that I've built myself that work OK on 10.10/10.11. I'll pull in one of the plug-ins in the repo to see if the behavior is different and let you know.

**Comment by iosdeveloper** [comment]
I found the error. @vogonistic's ANSI code parser uses a method that is only available on OS X 10.10 and later: https://github.com/matryer/bitbar/blob/master/App/BitBar/NSString%2BANSI.m#L111

**Comment by mm2270** [comment]
Well, that was quick. I removed any of my custom plug-ins. BitBar was closed. Went to the repo and installed the external-ip plug-in directly from the repo (got the pop up asking to install the plug-in) It launched BitBar where it displayed `...` for a few seconds, then crashed.

**Comment by iosdeveloper** [comment]
47eda9e should fix it. Can you build from source and test it?

**Comment by mm2270** [comment]
Yes! Working now from the latest source! Awesome sauce! Thank you so much for the quick response. :) I still need to go back and test on 10.8 and 10.7, but its working on the 10.9 system I have here. I suspect it'll work on those as well.
