### ISSUE TITLE
BitBar app is unsigned and therefore will not be executed.

### ISSUE THREAD

**Issue by chrisidefix** [matryer/bitbar#304]
BitBar releases are unsigned. Checking with `codesign -dv BitBar.app` returns: `BitBar.app: code object is not signed at all`. Of course many people can compile this themselves, but the question should be raised if you expect **everyone** to compile this themselves?

It looks like with the latest OS X upgrade to 10.11.4 Apple may have made it harder to execute unsigned code. *It used to be possible to just* **Right-Click + Open** *any app, which would then ask if you are sure you want to execute this downloaded application, but this didn't work for some reason when I installed the latest BitBar.app. I only got this Console output now when trying to start BitBar:*

```
28/03/2016 10:55:13.000 AM kernel[0]: OSTIARIUS: /Applications/BitBar.app/Contents/MacOS/BitBar is from the internet & is unsigned -> BLOCKING!
28/03/2016 10:55:13.187 AM com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x1000001a.BitBar[32020]) Service exited due to signal: Killed: 9
```

The way to fix it was to go into the `BitBar.app/Contents/MacOS` package folder and do the **Right Click + Open** *trick* on the executable right there. I then had to do this *again* on the `BitBar.app` to be able to run it. This seems a little complicated for average users and I was wondering if BitBar should be released with  **signed code**?

I am not 100% sure about Apple's signing process, but I know you can get a certificate without paying for the developer program. You can sign apps without paying the annual fee to Apple, but I am not sure if those signatures then count as "identified developers". It wouldn't be complicated to do, though (just add the signature when you build the release in Xcode).

**Comment by iosdeveloper** [comment]
We just started automating our builds using Travis CI, so we would need to look into codesigning there. FWIW, I didn't run into any issues with our release builds so far, so I'm interested to hear if this is a common problem now.

**Comment by matryer** [comment]
If you right click the app and choose Open, it lets you run it.

**Comment by matryer** [comment]
Currently, BitBar's audience is developers - so the right click, Open trick seems to work but I would like to get it signed if possible. I have a developer program account, so can provide the necessary certificate. @iosdeveloper let's look into this.

**Comment by iosdeveloper** [comment]
The [latest release](https://github.com/matryer/bitbar/releases/latest) is codesigned. :)
