### ISSUE TITLE
BitBar crashes with NSInvalidArgumentException when adding plugins

### ISSUE THREAD

**Issue by dklem** [matryer/bitbar#305]
When adding any plugin to BitBar, it briefly shows the "..." graphic in the menubar, and then crashes. Attached is the crash report. I'm running OS X 10.9.5 on this machine, which I know is a bit older, but haven't had a chance to try it on an El Capitan machine yet.

------------

Process:         BitBar [8135]
Path:            /Applications/BitBar.app/Contents/MacOS/BitBar
Identifier:      com.matryer.BitBar
Version:         1.9 (1.9.0)
Code Type:       X86-64 (Native)
Parent Process:  launchd [154]
Responsible:     BitBar [8135]
User ID:         501

Date/Time:       2016-03-27 22:16:13.324 -0400
OS Version:      Mac OS X 10.9.5 (13F1712)
Report Version:  11
Anonymous UUID:  127E0393-EFBD-A45E-A678-2BF9DACF4D57

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString containsString:]: unrecognized selector sent to instance 0x6080000375c0'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff8cd2325c __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x00007fff8df0be75 objc_exception_throw + 43
2   CoreFoundation                      0x00007fff8cd2612d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
3   CoreFoundation                      0x00007fff8cc81272 ___forwarding___ + 1010
4   CoreFoundation                      0x00007fff8cc80df8 _CF_forwarding_prep_0 + 120
5   BitBar                              0x0000000107ca1b3f -[Plugin buildMenuItemWithParams:] + 1184
6   BitBar                              0x0000000107ca2744 -[Plugin buildMenuItemForLine:] + 57
7   BitBar                              0x0000000107ca3b85 -[Plugin rebuildMenuForStatusItem:] + 1544
8   BitBar                              0x0000000107c95f51 __27-[ExecutablePlugin refresh]_block_invoke_2 + 157
9   libdispatch.dylib                   0x00007fff8bcc628d _dispatch_client_callout + 8
10  libdispatch.dylib                   0x00007fff8bcceb66 _dispatch_barrier_sync_f_slow_invoke + 46
11  libdispatch.dylib                   0x00007fff8bcc628d _dispatch_client_callout + 8
12  libdispatch.dylib                   0x00007fff8bccdef0 _dispatch_main_queue_callback_4CF + 333
13  CoreFoundation                      0x00007fff8cc8a4f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
14  CoreFoundation                      0x00007fff8cc45714 __CFRunLoopRun + 1636
15  CoreFoundation                      0x00007fff8cc44e75 CFRunLoopRunSpecific + 309
16  HIToolbox                           0x00007fff881e2a0d RunCurrentEventLoopInMode + 226
17  HIToolbox                           0x00007fff881e27b7 ReceiveNextEventCommon + 479
18  HIToolbox                           0x00007fff881e25bc _BlockUntilNextEventMatchingListInModeWithFilter + 65
19  AppKit                              0x00007fff8bdae24e _DPSNextEvent + 1434
20  AppKit                              0x00007fff8bdad89b -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
21  AppKit                              0x00007fff8bda199c -[NSApplication run] + 553
22  AppKit                              0x00007fff8bd8c783 NSApplicationMain + 940
23  BitBar                              0x0000000107c8bad4 start + 52
24  ???                                 0x0000000000000001 0x0 + 1

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff8d43c866 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff8b01135c pthread_kill + 92
2   libsystem_c.dylib             	0x00007fff8b480b2e abort + 125
3   libc++abi.dylib               	0x00007fff8436df31 abort_message + 257
4   libc++abi.dylib               	0x00007fff84393952 default_terminate_handler() + 264
5   libobjc.A.dylib               	0x00007fff8df0c30d _objc_terminate() + 103
6   libc++abi.dylib               	0x00007fff843911d1 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff84391246 std::terminate() + 54
8   libobjc.A.dylib               	0x00007fff8df0c0b0 objc_terminate + 9
9   libdispatch.dylib             	0x00007fff8bcc62a1 _dispatch_client_callout + 28
10  libdispatch.dylib             	0x00007fff8bcceb66 _dispatch_barrier_sync_f_slow_invoke + 46
11  libdispatch.dylib             	0x00007fff8bcc628d _dispatch_client_callout + 8
12  libdispatch.dylib             	0x00007fff8bccdef0 _dispatch_main_queue_callback_4CF + 333
13  com.apple.CoreFoundation      	0x00007fff8cc8a4f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
14  com.apple.CoreFoundation      	0x00007fff8cc45714 __CFRunLoopRun + 1636
15  com.apple.CoreFoundation      	0x00007fff8cc44e75 CFRunLoopRunSpecific + 309
16  com.apple.HIToolbox           	0x00007fff881e2a0d RunCurrentEventLoopInMode + 226
17  com.apple.HIToolbox           	0x00007fff881e27b7 ReceiveNextEventCommon + 479
18  com.apple.HIToolbox           	0x00007fff881e25bc _BlockUntilNextEventMatchingListInModeWithFilter + 65
19  com.apple.AppKit              	0x00007fff8bdae24e _DPSNextEvent + 1434
20  com.apple.AppKit              	0x00007fff8bdad89b -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
21  com.apple.AppKit              	0x00007fff8bda199c -[NSApplication run] + 553
22  com.apple.AppKit              	0x00007fff8bd8c783 NSApplicationMain + 940
23  com.matryer.BitBar            	0x0000000107c8bad4 start + 52

Thread 1:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib        	0x00007fff8d43d662 kevent64 + 10
1   libdispatch.dylib             	0x00007fff8bcc8421 _dispatch_mgr_invoke + 239
2   libdispatch.dylib             	0x00007fff8bcc8136 _dispatch_mgr_thread + 52

Thread 2:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	0x00007fff8d438a1a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff8d437d18 mach_msg + 64
2   com.apple.CoreFoundation      	0x00007fff8cc45f15 __CFRunLoopServiceMachPort + 181
3   com.apple.CoreFoundation      	0x00007fff8cc45539 __CFRunLoopRun + 1161
4   com.apple.CoreFoundation      	0x00007fff8cc44e75 CFRunLoopRunSpecific + 309
5   com.apple.Foundation          	0x00007fff84a4ef87 +[NSURLConnection(Loader) _resourceLoadLoop:] + 348
6   com.apple.Foundation          	0x00007fff84a4ed8b __NSThread__main__ + 1318
7   libsystem_pthread.dylib       	0x00007fff8b010899 _pthread_body + 138
8   libsystem_pthread.dylib       	0x00007fff8b01072a _pthread_start + 137
9   libsystem_pthread.dylib       	0x00007fff8b014fc9 thread_start + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff8d438a1a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff8d437d18 mach_msg + 64
2   com.apple.CoreFoundation      	0x00007fff8cc45f15 __CFRunLoopServiceMachPort + 181
3   com.apple.CoreFoundation      	0x00007fff8cc45539 __CFRunLoopRun + 1161
4   com.apple.CoreFoundation      	0x00007fff8cc44e75 CFRunLoopRunSpecific + 309
5   com.apple.AppKit              	0x00007fff8bf4e05e _NSEventThread + 144
6   libsystem_pthread.dylib       	0x00007fff8b010899 _pthread_body + 138
7   libsystem_pthread.dylib       	0x00007fff8b01072a _pthread_start + 137
8   libsystem_pthread.dylib       	0x00007fff8b014fc9 thread_start + 13

Thread 4:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	0x00007fff8d43c9aa __select + 10
1   com.apple.CoreFoundation      	0x00007fff8cc91a03 __CFSocketManager + 867
2   libsystem_pthread.dylib       	0x00007fff8b010899 _pthread_body + 138
3   libsystem_pthread.dylib       	0x00007fff8b01072a _pthread_start + 137
4   libsystem_pthread.dylib       	0x00007fff8b014fc9 thread_start + 13

Thread 5:: Dispatch queue: com.apple.root.default-priority
0   libsystem_kernel.dylib        	0x00007fff8d438a56 semaphore_wait_trap + 10
1   libsystem_platform.dylib      	0x00007fff81abf451 _os_semaphore_wait + 16
2   libdispatch.dylib             	0x00007fff8bccc982 _dispatch_barrier_sync_f_slow + 310
3   com.matryer.BitBar            	0x0000000107c95ea1 __27-[ExecutablePlugin refresh]_block_invoke + 155
4   libdispatch.dylib             	0x00007fff8bcc91bb _dispatch_call_block_and_release + 12
5   libdispatch.dylib             	0x00007fff8bcc628d _dispatch_client_callout + 8
6   libdispatch.dylib             	0x00007fff8bcc8082 _dispatch_root_queue_drain + 326
7   libdispatch.dylib             	0x00007fff8bcc9177 _dispatch_worker_thread2 + 40
8   libsystem_pthread.dylib       	0x00007fff8b011ef8 _pthread_wqthread + 314
9   libsystem_pthread.dylib       	0x00007fff8b014fb9 start_wqthread + 13

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff8d43ce6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8b011f08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff8b014fb9 start_wqthread + 13

Thread 7:
0   libsystem_kernel.dylib        	0x00007fff8d43ce6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8b011f08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff8b014fb9 start_wqthread + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007fff726e0310  rcx: 0x00007fff57f73e38  rdx: 0x0000000000000000
  rdi: 0x0000000000000707  rsi: 0x0000000000000006  rbp: 0x00007fff57f73e60  rsp: 0x00007fff57f73e38
   r8: 0x00007fff84394959   r9: 0x00007fff8b4a88d0  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x00007fff57f73fc0  r13: 0x00007fff57f744d0  r14: 0x0000000000000006  r15: 0x00007fff57f73ea0
  rip: 0x00007fff8d43c866  rfl: 0x0000000000000206  cr2: 0x00000001094e6000
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

**Comment by mm2270** [comment]
HI @dklem I had the same issue. Please see #302 There's a fix in place for this posted by @iosdeveloper, but its not in the compiled 1.9.0 version yet. For the moment, you'll need to pull down the master source and build it yourself. I use the GitHub Desktop application to pull it down and have never had an issue building it FWIW.
