### ISSUE TITLE
Make donations possible

### ISSUE THREAD

**Issue by oliviernt** [matryer/bitbar#307]
I'm using & loving BitBar a lot and found myself searching for a donation button on the website but didn't find one.

My guess would be that most people using BitBar are quite happy with it and would be willing to/interested in sending some money your way!

Any plans on something like that?

Best,
Olivier

**Comment by matryer** [comment]
Very kind of you. There is a note in the README :) https://github.com/matryer/bitbar#its-free-so-please-donate

Any Bitcoin will be shared among the main core contributors.

**Comment by oliviernt** [comment]
:+1: Awesome! I missed that in the readme :)
