### ISSUE TITLE
brew cask checksum error

### ISSUE THREAD

**Issue by vikeri** [matryer/bitbar#309]
I get the following when trying to update with `brew cask install bitbar` to bitbar 1.9.1

```
Error: sha256 mismatch
Expected: 86f255d4f426159ec5b184dfdc27c06d6aa1a11ed3ce16cf08b5289115967467
Actual: 72350013b295ef1fa4beb1374bd3d2bdc5a7335c42666e8592b574799f9ced65

```

**Comment by iosdeveloper** [comment]
We re-released v1.9.1 with Developer ID signed builds. The cask needs to be [updated](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

**Comment by vikeri** [comment]
Ok, do I have to do that or are you?

**Comment by iosdeveloper** [comment]
The cask is usually maintained by the community.

**Comment by vikeri** [comment]
Done! https://github.com/caskroom/homebrew-cask/pull/20143

**Comment by iosdeveloper** [comment]
Thanks! 👍
