### ISSUE TITLE
Bitbar renders images at "non-retina" resolution

### ISSUE THREAD

**Issue by SCdF** [matryer/bitbar#316]
So apologies if I've got this horribly wrong, but I *think* Bitbar doesn't correctly support retina-quality images. Here:

```js
var TWITCH_ICON_16 = "AAABAAEAEBAAAAAAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAQAQAAAAAAAAAAAAAAAAA" +
    "AAAAAAD///8B////Af///wH///8B////AaVBZP+lQWT/pUFk/6VBZE////8B////Af///wH///8B" +
// <snip>
console.log('|image="'+ TWITCH_ICON_16 + '"');
```

…is me using a 16x16 favicon, rendered on a normal dpi display:

![image](https://cloud.githubusercontent.com/assets/583851/14395156/0593d2f0-fdc8-11e5-827d-7ae8c96434f4.png)
_(emoji for scale)_
Which looks great! Here is the same situation rendered a retina display:

![image](https://cloud.githubusercontent.com/assets/583851/14395299/b5333b9c-fdc8-11e5-969d-66412506b6f4.png)

Blocky, as expected. It looks like 16:16 images are (roughly) the right non-retina size for the tray, which would imply doubling the res would be the correct retina resolution.

For funzies:

![image](https://cloud.githubusercontent.com/assets/583851/14395473/dab5c262-fdc9-11e5-8174-53891124c1b0.png)

It also looks the same on my retina display:

![image](https://cloud.githubusercontent.com/assets/583851/14395530/21620c7a-fdca-11e5-8d5e-69dcdbf22586.png)

So from this it looks like to me that Bitbar renders image at "standard" resolution, as opposed (or not as well as) the doubled retina resolution.

If you want to fix this, I'm not exactly sure what the correct fix for this would be (I haven't really dealt with retina vs. non-retina before). I guess you could have an `image=` and a `retinaImage=` base64 parameter, or just change `image` to render at retina resolution.

**Comment by iosdeveloper** [comment]
Don't double the size, double the resolution (see #314).

**Comment by SCdF** [comment]
Ahh cool, thanks. Apologies, I should have searched closed tickets!

**Comment by iosdeveloper** [comment]
No worries. We should really mention this somewhere.

**Comment by mm2270** [comment]
Yeah, it probably should get mentioned somewhere in the plugin development documentation.
