### ISSUE TITLE
Ability to set icon

### ISSUE THREAD

**Issue by manojlds** [matryer/bitbar#32]
Ability to set an icon for the menu bar item would be really great. Most of the menu bar items work this way, and having text feels out-of-place.

**Comment by chrisshroba** [comment]
+1

**Comment by matryer** [comment]
You can try using symbols for now? Like this: https://github.com/matryer/bitbar/pull/34

**Comment by manojlds** [comment]
@matryer for now, yeah. Not very familiar with OS X apps, but will see if I can send a PR for this.

**Comment by matryer** [comment]
I mean without any changes, would echoing a symbol in the plugin work?

**Comment by manojlds** [comment]
@matryer - what I meant was symbols are a workaround we can do right now. Not everything is available though right. Like, if for #34 I wanted spotify icon, I can't do that right?

**Comment by matryer** [comment]
Correct, that would be impossible. It’s a nice feature request.

**Comment by chrisshroba** [comment]
I love the idea of being able to use icons, as then users could emulate almost any GUI-less menubar application. That would be amazing!!

**Comment by matryer** [comment]
A plugin currently doesn't have any official 'supporting' files - would this be needed in order to bundle the artwork with the plugin? Or is there a simple way to do it.

**Comment by manojlds** [comment]
@matryer most likely the assets needs to be bundled with the plugin

**Comment by thomasbachem** [comment]
For now you can at least use Emojis.

**Comment by manojlds** [comment]
The following are the only available ones right?

😃😇😍😜😸🙈🐺🐰👽🐉
💰🏡🎅🍪🍕🚀🚻💩📷📦
1⃣2⃣3⃣4⃣5⃣6⃣7⃣8⃣9⃣0⃣

**Comment by keithamus** [comment]
To keep plugins as simple scripts, BitBar could handle Base64 images, this way plugins are still just one single file. base64 urls could work as params, this way plugins could also be kept backwards compatible. Something like:

```bash
#!/usr/bin/env sh
echo "MyPlugin | icon=data:image/png;base64,...."
echo "---"
echo "Menu item"
```
For older BitBar versions, it would display `MyPlugin`, for newer ones it would display the icon - perhaps with `MyPlugin` as a tooltip for when you hover over the icon?

**Comment by manojlds** [comment]
@keithamus - good suggestion, +1.

**Comment by thomasbachem** [comment]
There should also be a way to display text among the icon, so we'd need something like `icononly=true` to keep it backwards-compatible. I'm not sure that's necessary though. Just using `My Text | icon=...` (icon + text) or `| icon=...` (icon only) would be more intuitive.

**Comment by mm2270** [comment]
Just commenting on the above. I had a similar thought on this today. I agree that BitBar could possibly be updated to use Base64 images for menu icons. That's the way some other applications and processes do it, so I think simply dropping in Base64 encoded data as a variable for the menu icon should be possible. Not a developer myself, so I'm only speculating.

Anyway, I would love to see this feature implemented, since it would really allow for some very custom looking menu bar items. Emoji support is great, but emojis are limited and most often I can't locate something that really fits what I'm looking for.

**Comment by akx** [comment]
Support for SVG would be nice too. (Or at least [SVG path elements](https://www.w3.org/TR/SVG/paths.html)?) This looks useful: https://cocoapods.org/pods/PocketSVG

```shell
echo "| svg-path=M100,100L300,100L200,300z"
```

to render a triangle, etc. :)

**Comment by mm2270** [comment]
Another thought would be support for .icns files located on the system? Like set the icon to a path on the Mac that should exist (app icons, System level icons, etc) I don't know how difficult it would be to add support for reading these in and rendering them, so just throwing something out there. If this is highly impractical, then just ignore me. :)

**Comment by JayBrown** [comment]
With the menulet AnyBar you can add custom images: https://github.com/tonsky/AnyBar
So something like this shouldn't be a big deal to implement in BitBar.

**Comment by iosdeveloper** [comment]
@JayBrown Feel free to submit a PR if you have something in mind that works with no resource bundles. For AnyBar you specify a local path. That wouldn't work. In my opinion Base64 or remote URLs are good ideas. Base64 is less of a hassle on newer versions of OS X (>= 10.9).

**Comment by mm2270** [comment]
I'd love to see Base64 data for icons become a feature. I agree this would make the most sense, since it would be keeping in alignment with the goal of BitBar to use self contained single file plug-ins. As soon as we start making it rely on external support files on the system, things will begin to get complicated.
