### ISSUE TITLE
Find More Plugins... after `cask install bitter` does not work

### ISSUE THREAD

**Issue by mrjcleaver** [matryer/bitbar#333]
Link goes to https://github.com/matryer/bitbar/tree/master/Plugins

**Comment by iosdeveloper** [comment]
It seems you are running an old version of BitBar. The menu item is called "Get Plugins" in the current release and opens https://getbitbar.com. You can find your version under Preferences. The latest is v1.9.1.

**Comment by mrjcleaver** [comment]
Weird. Says when I install:

brew cask install bitbar
==> Downloading https://github.com/matryer/bitbar/releases/download/v1.9.1/BitBar-v1.9.1.zip
######################################################################## 100.0%
==> Verifying checksum for Cask bitbar
==> Moving App 'BitBar.app' to '/Applications/BitBar.app'
🍺  bitbar staged at '/opt/homebrew-cask/Caskroom/bitbar/1.9.1' (0B)

brew cask install bitbar --force
==> Downloading https://github.com/matryer/bitbar/releases/download/v1.9.1/BitBar-v1.9.1.zip
Already downloaded: /Library/Caches/Homebrew/bitbar-1.9.1.zip
==> Verifying checksum for Cask bitbar
==> Moving App 'BitBar.app' to '/Applications/BitBar.app'
🍺  bitbar staged at '/opt/homebrew-cask/Caskroom/bitbar/1.9.1' (0B)

Yet BitBar itself stubbornly keeps saying it is at 1.2

**Comment by iosdeveloper** [comment]
You probably have older versions under '/opt/homebrew-cask/Caskroom/bitbar'. Try deleting them first.

**Comment by mrjcleaver** [comment]
That fixed it, thanks.

$ rm -rf /opt/homebrew-cask/Caskroom/bitbar/1.2.0/
$ brew cask install bitbar --force
==> Downloading https://github.com/matryer/bitbar/releases/download/v1.9.1/BitBar-v1.9.1.zip
Already downloaded: /Library/Caches/Homebrew/bitbar-1.9.1.zip
==> Verifying checksum for Cask bitbar
==> It seems there is already an App at '/Applications/BitBar.app'; overwriting.
==> Removing App: '/Applications/BitBar.app'
==> Moving App 'BitBar.app' to '/Applications/BitBar.app'
🍺  bitbar staged at '/opt/homebrew-cask/Caskroom/bitbar/1.9.1' (0B)
$
