### ISSUE TITLE
BitBarDistro? too many issues on screen HELP!!!! there is no way to a setup this thing...

### ISSUE THREAD

**Issue by Schuif67** [matryer/bitbar#334]
I have BitBarDistro installed for my Pi-Hole, but there is (for me) no way to get it working correctly.
like a Big irritating menubar. is there enyone who can help me solve this or help me how to remove BitBarDistro. 
![schermafbeelding 2016-05-28 om 16 50 13](https://cloud.githubusercontent.com/assets/19566468/15628011/a8ffb4dc-24f5-11e6-99e4-4c9c3de14037.png)

TIA

**Comment by iosdeveloper** [comment]
Please check in Activity Monitor.app if you have multiple instances of BitBar or BitBarDistro running. You can quit them from there. If so, please make sure you don't have multiple copies of BitBar in different locations set to launch at login (under System Preferences -> Users).
It looks like your `pluginsDirectory` default is set to a folder with many scripts (a clone of the plugins repo?). Please consider creating an Enabled folder and linking the plugins you want to use there.
Check out the documention for the distributable version [Docs/DistributingBitBar.md](here).

**Comment by Schuif67** [comment]
thanks it works perfectly now!!!
