### ISSUE TITLE
Is it possible to refresh bitbar menu bar output on change of file?

### ISSUE THREAD

**Issue by nikitavoloboev** [matryer/bitbar#345]
I want to create a bitbar plugin that will display the content of a task I want to do that I will first pass into the clipboard and then write in the bitbar plugin. So for example I have a task 'reply to all emails' that I copied, I want to then pass this text and change my bitbar plugin that at first looked like this : 

```
#!/bin/bash

echo get ready to reply to emails
``` 

After I activate my script through [Keyboard Maestro](https://www.keyboardmaestro.com/main/) or something, it will pass the task I copied and change the file to this : 

```
#!/bin/bash

echo reply to all emails
``` 

I can make the text switching work already in KM like so : 

![2016-06-23 at 11 29](https://cloud.githubusercontent.com/assets/6391776/16298488/dfe5d89c-3935-11e6-9d9c-430a931c01d4.png)

However I wish to have my new change instantly seen in the menu bar. Is there a way to refresh the bitbar menu bars on file change? And if not how can I produce this behaviour in BitBar? I only see 'Refresh All' in the preferences of the menu bar when you click on the task but is there a way to activate the 'refresh all' globally?

Thank you for any help.

**Comment by iosdeveloper** [comment]
You could use the URL scheme: https://github.com/matryer/bitbar/blob/master/Docs/URLScheme.md#refreshplugin

**Comment by nikitavoloboev** [comment]
Hey, that was a quick reply, thank you.

I am not very familiar with calling URL schemes in osx. Is this how you do it?

![2016-06-23 at 11 36](https://cloud.githubusercontent.com/assets/6391776/16298663/e05900a0-3936-11e6-8173-d8e971bc04c1.png)

It says the command is not found.

**Comment by iosdeveloper** [comment]
Use `open` followed by the URL.

**Comment by nikitavoloboev** [comment]
I have just tried it multiple times and it doesn't seem to update.

```
open bitbar://refreshPlugin
``` 
Is this the correct command or do I have to follow it up with anything? It doesn't seem to refresh the plugins.

**Comment by nikitavoloboev** [comment]
From the example provided I figured I should use something like this to make it work : 

![2016-06-23 at 11 54](https://cloud.githubusercontent.com/assets/6391776/16299209/6caa1cc2-3939-11e6-9df2-52a44658a2a6.png)

What mistake did I make there? My plugin name is 'todo'.

**Comment by iosdeveloper** [comment]
Maybe you forgot the file extension?

**Comment by nikitavoloboev** [comment]
It doesn't have a file extension though 😕

**Comment by nikitavoloboev** [comment]
Here is what I get : 

![2016-06-23 at 12 04](https://cloud.githubusercontent.com/assets/6391776/16299456/b30f99b6-393a-11e6-8097-2bf96145dedc.png)

**Comment by iosdeveloper** [comment]
Try quoting the URL.

**Comment by nikitavoloboev** [comment]
That was the issue, thank you a lot for your help.

**Comment by frakman1** [comment]
@iosdeveloper 
It seems I messed up my `bitbar://` handler. It goes to a custom build of BitBar that I made with XCode. How do I restore it to the BitBar app? I tried re-installing BitBar but no luck.
I looked at the file `~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist` but it wasn't there. Any ideas?
