### ISSUE TITLE
Question on how to remove most (or all) of Preferences submenu

### ISSUE THREAD

**Issue by mm2270** [matryer/bitbar#347]
Hi. I'm sorry to open this as an Issue, but since there's no general discussion section, I didn't know how else to post this. Feel free to label this as a "Question"
This is going to sound odd and is admittedly an unorthodox request, but I'm looking for a way to remove almost all of the built in Preferences submenu that appears at the end of any BitBar plugin menu. I won't go in depth into the reasons for this, but suffice to say that the manner that I'm looking to use BitBar doesn't require the end user to be able to see things like the version string or the Quit menu line. I might want to keep the Refresh all in there as a failsafe in the event that a plugin gets stuck during a refresh from within the menu I've built.

Since this is obviously not something most people using BitBar would really want, I'm perfectly happy with using a custom build from Xcode to achieve this. I did some exploration in the Xcode project and I see the lines that generate most of the Preferences submenu, in the PluginManager.m file. The problem is, not being a developer, I'm not certain on the best approach to removing these without messing up BitBar's functionality. Also, as mentioned, i'd like to keep just the "Refresh all" line and remove the others from it if possible.

Can anyone provide a quick guide on what would need to be commented out from that file to remove those sections without breaking it completely?

Thanks in advance for any help with this.

**Comment by matryer** [comment]
Check this out: https://github.com/matryer/bitbar/blob/master/Docs/DistributingBitBar.md

**Comment by mm2270** [comment]
Thanks. But, unless something has changed very recently, the BitBar distro version still shows those additional items under Preferences. I'm already using the plist key to disable advanced user settings with BitBar, which is great, but there are still "Refresh all", "Version" and "Quit" items under it. I don't care too much about the version string, but I would like to remove the Quit function from it. Basically, I don't want our users to quit it, either accidentally or on purpose.
To combat that, I already have a separate app (script wrapped as an executable) which will look to see if BitBar is running, and if not, launches it when its double clicked, or exits silently if it is running already. Its a "launcher" of sorts, since its possible for someone to quit it and not know exactly how to re-open it. I'm doing this because we're planning on putting BitBar into a normally hidden location on the system as part of the deployment.

**Comment by matryer** [comment]
Sounds a bit suspicious to me :D

The best place to discuss this is our Slack channel: https://getbitbar.herokuapp.com

**Comment by mm2270** [comment]
Hmm. OK, I can understand why you might think that, but I assure you this is not some attempt to push malware or spyware onto users. I'm simply trying to make our plugin appear as much like a regular menu item as possible, and not like a separate application. I did state this was a little unorthodox right up front so I'm not looking for any built in functionality to be put into the product. Just wanted to see if there was a simple way to do this within the project code.

Anyway, thanks for the slack channel link - I wasn't aware there was one. I'll join up to be part of the discussions.

**Comment by matryer** [comment]
I was just kidding :) 

One option is to fork the project and delete the code that adds those items. But if it’s something others might want, then perhaps making them configurable is a good idea.

**Comment by mm2270** [comment]
Yeah, I actually already got the Quit menu removed just now with the project. Its simple enough actually. I wasn't certain it would work, but it compiled perfectly and is running without the Quit item in it.

I'm not totally certain how useful this might be for others, but I guess I could float the idea on the Slack channel to see what others think. My only reservation with removing the whole of the Preferences submenu is that, I've seen an odd case or two of a machine waking from sleep and the plugin refreshes getting permanently stuck in a refresh state and never rendering. In those cases, the only thing that shows up is that Preferences submenu since its not tied to the plugin itself. When that's happened, the Refresh all or even the Quit has come in handy to force a refresh or kill it and then relaunch it.

I guess its something to ponder about whether its worth the risk of removing it altogether.
