### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by joelmccracken** [matryer/bitbar#349]
First off, let me say, I LOVE bitbar! thank you so much for working on it!!! I had plans to make something just like it because I wanted it, and the way yinz designed everything is just great. 

I noticed an issue with memory: right now, it looks like BitBar is using more memory than I would expect it to:

<img width="862" alt="screen shot 2016-07-21 at 9 22 18 am" src="https://cloud.githubusercontent.com/assets/10936/17024126/a8670940-4f24-11e6-863f-36d769c02cb6.png">

The plugins I am using are here:

https://github.com/joelmccracken/real-dotfiles/tree/master/bitbar

I wrote the one named "status.5s", so there might be some random issues with that. Here is a screenshot of its typical output: 

<img width="614" alt="screen shot 2016-07-21 at 9 29 56 am" src="https://cloud.githubusercontent.com/assets/10936/17024395/c180ab38-4f25-11e6-961c-c7647cf4ef12.png">

It is just outputting the contents of a report that is created by another process that runs in the background somewhere else.

I am using version 1.4, which seems to be the most up-to-date version.

I looked at https://github.com/matryer/bitbar/issues/203 and https://github.com/matryer/bitbar/issues/18, although I haven't dug too deeply into them to know if they are likely the issue.

**Comment by iosdeveloper** [comment]
The latest release is [https://github.com/matryer/bitbar/releases/latest](v1.9.1).

**Comment by joelmccracken** [comment]
Oh, weird. I could have sworn that I had just checked to see if there is a new version. I just updated, and I will re-open if I still have a problem.
