### ISSUE TITLE
bash command doesn't support spaces in path

### ISSUE THREAD

**Issue by jtokoph** [matryer/bitbar#35]
I've tried escaping but it seems like the app doesn't support parsing escaped spaces when splitting the string.

`echo "test me | bash=/some/pa\ th/with/a\ space\ or\ two param1=foo"`

**Comment by ADeeds** [comment]
I sent in a PR that fixed this for me (had to change how things were getting tokenized)

**Comment by jcaille** [comment]
I'm currently working on a slightly improved tokeniser (Pull request #50) that allows syntax such as 
`Hello | key="space separated value"`

That should make it easier to execute bash scripts with numerous parameters :
`Say something | bash="say Hello world"`

**Comment by matryer** [comment]
Spaces are now supported in `master` - once we've done some good testing after this flurry of activity, we can release an update.
