### ISSUE TITLE
Double-click, too?

### ISSUE THREAD

**Issue by irstacks** [matryer/bitbar#351]
It'd be great to be able to differentiate a double-click-input from a single click on any given selection, too.

**Comment by iosdeveloper** [comment]
Why? Can you give an example of a (system) app that uses this pattern?

**Comment by irstacks** [comment]
1. Run a script/visit link OR copy literal script/link contents to the clipboard (eg AKAlias run script or copy to clipboard).
2. Visit link A OR visit link B (eg Github notifications view or mark-as-read).

**Comment by iosdeveloper** [comment]
Are you aware of the `alternate` parameter? Tutorial: https://getbitbar.com/plugins/Tutorial/alternate_options.sh
