### ISSUE TITLE
Run task with root privilege

### ISSUE THREAD

**Issue by BeWe11** [matryer/bitbar#352]
I want to execute a script that needs root privilege in a
`echo "text | bash=path/to/script.sh terminal=false"` line.
I tried using osascript to get a password prompt like this
`echo "text | bash=osascript param1=-e param2="do shell script \"path/to/script\" with administrator privileges"`
but BitBar parses the second parameter as just the word "do", I cannot make
BitBar accept a string argument.

I saw that there is an undocumented "root=true" option, but I'm not sure what
this does or if this even works. I saw no apparent changes when I used it.

Is there a way to run a script with root privileges without opening a terminal?

**Comment by iosdeveloper** [comment]
Looking at examples in matryer/bitbar-plugins, to work with parameters that contain whitespace use something like this:

```
if [ "$1" = action ]; then
  osascript -e "do shell script \"path/to/script\" with administrator privileges"
  return
fi

echo "text | bash=$0 param1=action"
```

`root=true` uses sveinbjornt/STPrivilegedTask instead of NSTask to run the script.

**Comment by glowinthedark** [comment]
This works on Mojave:

```bash
echo "Disable sleep on battery | bash=/usr/bin/sudo param1=/usr/bin/pmset param2=-a param3=disablesleep param4=1 terminal=false refresh="
```

...but apparently not working on Catalina
