### ISSUE TITLE
plugin: packagemanager fails on npm

### ISSUE THREAD

**Issue by plessbd** [matryer/bitbar#353]
So when running the package-manager plugin I was annoyed that npm was not working because it could not find node

As far as I can tell this all relates back to the fact that javascript needs to have a different #!

It seems to be that the PATH variable that BitBar has when it runs does not contain /usr/local/bin, this is a security issue as far as apple is concerned.

To "fix" this you can add the file ~/Library/LaunchAgents/com.matryer.BitBar.plist with contents

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.matryer.BitBar</string>
  <key>ProgramArguments</key>
  <array>
    <string>sh</string>
    <string>-c</string>
    <string>launchctl setenv PATH /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
```

The caveats with this is that BitBar will have to be restarted if it is set to start at login for the path to work, and it will have to be started with spotlight.

I have found mention that you should be able to modify the Info.plist and add an LSEnvironment key with a dictionary for the path (https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/20001431-106825) however this does not work for me.

and atom https://github.com/atom/atom/issues/3018#issuecomment-98617790 seems to have the option of starting with the command line and somehow pushing the $PATH to the app.

**Comment by tresni** [comment]
Duplicates #36
