### ISSUE TITLE
v2 beta 8: base64 icons stopped working

### ISSUE THREAD

**Issue by JayBrown** [matryer/bitbar#357]
Just updated, and the base64-encoded menu bar icons don't show anymore; the menus are still there, but sans icons. Anyone else with this problem?

**Comment by iosdeveloper** [comment]
The image parameters indeed changed in v2-beta8 (you can pass URLs now). Which plugin doesn't work anymore?

**Comment by JayBrown** [comment]
My own plugins, e.g. one with
```
TEMPL="iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAQAAABLCVATAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAqklEQVR4nGL4z0AdSCVj4AZBqH8sMOF/ogz/Of4CRXjhIpxQEUm4CCNUlybcBITB/zhB1F9DJBEpsCYJhMhfE7AIO0LkZRjYDFQ3YvqXOBGCipR/Uckgqrlo1KBRg0YNGjVo1KBRg0aoQT8CEQL/uEAUSiNCGkQhNyL+mIJFOBAi0EYEUFABqokJJvdPCNqI4YKLsENFRBEOgepSxnQhBZBqBgEAAAD//wMA7zsOXl0uqHMAAAAASUVORK5CYII="

echo "| templateImage=$TEMPL dropdown=false"

echo "---"
```

**Comment by iosdeveloper** [comment]
Fixed in [v2 beta 9](https://github.com/matryer/bitbar/releases/tag/v2.0.0-beta9).
