### ISSUE TITLE
Crashes when font name has wrong capitalization

### ISSUE THREAD

**Issue by fregante** [matryer/bitbar#360]
Minor, given that the solution is to fix the font name.
## Working example

``` sh
#!/bin/bash
echo 'Hello | font=ArialMT'
```
## Bug example

``` sh
#!/bin/bash
echo 'Hello | font=Arialmt'
```

Note: likely because of font name aliasing, both `Helvetica` and `helvetica` work

Maybe related to https://github.com/matryer/bitbar/pull/132?

**Comment by iosdeveloper** [comment]
@alesf

**Comment by iosdeveloper** [comment]
@alesf Please review #361

**Comment by alesf** [comment]
@iosdeveloper This was fast! The code seems ok to me. Didn't check if it works.

**Comment by iosdeveloper** [comment]
The culprit was the missing brackets surrounding the first if-else-shorthand, that actually predate your commit, so the second if-else-shorthand never caught the first one being nil.

**Comment by iosdeveloper** [comment]
Although #361 fixes the crash, maybe we want to actually use the font name returned by your `-[NSFontDescriptor matchingFontDescriptorWithMandatoryKeys:]` for non-exact matches (so a wrong `Arialmt` would result in `ArialMT` instead of the system font). Thoughts?

**Comment by alesf** [comment]
Yeah, nice. The method should just take the first match if there are any. Will you do it as you are more experienced objC developer :)

**Comment by iosdeveloper** [comment]
Sure, thanks for the feedback! :)

**Comment by iosdeveloper** [comment]
Should be fixed in [v2 beta 10](https://github.com/matryer/bitbar/releases/tag/v2.0.0-beta10).

**Comment by fregante** [comment]
Closing old issue. Glad to hear that a fix has been written
