### ISSUE TITLE
Menu image blink with `v2 beta 9`

### ISSUE THREAD

**Issue by sylvainbaronnet** [matryer/bitbar#362]
See : https://www.youtube.com/watch?v=p60QizGXImk

~~Sometimes images doesn't appear at all.~~

~~I don't have this issue with `beta 8`~~

Update : 

Actually, with `beta 8` images  doesn't appear at all.

I don't have these issues with `beta 7`

**Comment by iosdeveloper** [comment]
Base64 images were broken in beta 8 (see #357). Beta 10 should fix the "blinking".

**Comment by sylvainbaronnet** [comment]
great, thank you

**Comment by iosdeveloper** [comment]
Should be fixed in [v2 beta 10](https://github.com/matryer/bitbar/releases/tag/v2.0.0-beta10).

**Comment by sylvainbaronnet** [comment]
perfect 👍
