### ISSUE TITLE
SystemUIServer memory usage grows throughout the day

### ISSUE THREAD

**Issue by colindean** [matryer/bitbar#365]
I've noticed when I come home from work for the past few days that my menu bar is white and my machine is sluggish. When I open Activity Monitor, I observe the SystemUIServer is consuming approximately 2+ GB of memory. I didn't use my computer one night, and the next night it was around 3.5 GB.

I have a theory that BitBar is the culprit, as it's the newest addition to my menu bar that includes Keybase, Mjolnir, Flux, Alfred, Dropbox, Google Music Uploader, and indicators for some other apps.

I have the Coinbase Bitcoin price monitor and the Homebrew monitor on it. My source is here: https://gist.github.com/colindean/91c324f2a04d18e1d2933805a7e0abc0

I just updated to v1.9.2 just before filing this, so it's possible (likely, even) that something in the version I was running was awry. I'll close this if the problem goes away.

**Comment by iosdeveloper** [comment]
Which version did you use before updating to v1.9.2?

**Comment by colindean** [comment]
I unfortunately don’t know. I did a `brew cask install bitter —force` and overwrote what was installed.

**Comment by iosdeveloper** [comment]
Please reopen if you see this again in the latest release.

**Comment by colindean** [comment]
Still seeing it. Came home to a whited-out bar and SystemUIServer at 2.06 GB of memory, 998.3 MB compressed.

**Comment by colindean** [comment]
I didn't kill the process. I'll leave it open in case there are some investigation steps you'd like for me to take.

**Comment by colindean** [comment]
Sitting at 5.57 GB, 3.98 GB compressed...

And in the time it took for me to run sample and write this sentence, the compressed jumped to 4.18 GB.

**Comment by colindean** [comment]
Restarting Bitbar seems not to have an effect.

**Comment by colindean** [comment]
Trying an experiment in which I've quit Bitbar and restarted SystemUIServer. That will hopefully indicate as to whether or not Bitbar is the culprit!

**Comment by colindean** [comment]
Came back today and memory consumption was a little less than I expected, but not appreciably. I've killed Keybase next and we'll see how it fares overnight. I'll close this for now, because I'm less confident that Bitbar is the culprit here.

**Comment by colindean** [comment]
I returned this evening to a 500 MB SystemUIServer. It's not Keybase!

A friend [suggested](https://twitter.com/drquuxum/status/772566300258361344) that Dropbox may be the culprit. I've reinstalled it and will see how the memory usage changes overnight.

I'll close this, but hopefully it'll be of use to someone.
