### ISSUE TITLE
Pipe "|" in script confusing script

### ISSUE THREAD

**Issue by BrokenFlows** [matryer/bitbar#366]
I'm trying to adapt a bash script I found online to work with BitBar. To format dates and times it uses code that looks like this:
`isspd1=$(cat /tmp/issp.json | jq -r '.response[0].duration')`
This works fine in the shell but I think since the | can be used as a modifier (not sure about wording) in BitBar that the | is getting mistaken and thus the rest of the line rendered non-functional.

I'm mostly wondering if this seems possible to you and if so what a solution may be. Is there a way to escape the | and use it in a literal Bash sense for example?

Thanks,
BrokenFlows

**Comment by iosdeveloper** [comment]
BitBar renders what you write to stdout, i.e. the output of your script when running in Terminal.

**Comment by BrokenFlows** [comment]
This wasn't being put to stdout as the snippet above was the only code on those lines but lines with ` | jq`, which are frequent, don't work, even if not trying to output

**Comment by iosdeveloper** [comment]
Did you install `jq` through Homebrew? You might want to add to `$PATH` as per the [README](https://github.com/matryer/bitbar/blob/master/README.md#useful-tips) like this:

```
export PATH='/usr/local/bin:/usr/bin:$PATH'`
```

**Comment by BrokenFlows** [comment]
@iosdeveloper I did install through HomeBrew. I just added `export PATH='/usr/local/bin:/usr/bin:$PATH'` below the shebang in the script and the jq issue is gone but now on those same lines it complains about `cat`, from the beginning of those lines.

**Comment by iosdeveloper** [comment]
What does the shebang (at the top) of the script look like?

**Comment by BrokenFlows** [comment]
@iosdeveloper `#!/bin/bash` Is that correct or do I need to change it?

**Comment by iosdeveloper** [comment]
I don't know, looking at [other bash plugins](https://github.com/matryer/bitbar-plugins/blob/master/Time/pomodoro.1s.sh) `cat` should just work. Maybe join us on Slack and ask somebody else.

**Comment by BrokenFlows** [comment]
@iosdeveloper I think I will thank you. Which slack channel is best for this thread to continue in?

**Comment by iosdeveloper** [comment]
#plugins?

**Comment by BrokenFlows** [comment]
@iosdeveloper what I did with path was exactly 
`export PATH='/usr/local/bin:/usr/bin:$PATH'`
was that correct or should there have been another directory path there?

**Comment by skl** [comment]
This looks old but you might need double-quotes here: `export PATH="/usr/local/bin:/usr/bin:$PATH"`
