### ISSUE TITLE
Plugin duplicating in the bar

### ISSUE THREAD

**Issue by digitalfiz** [matryer/bitbar#367]
This plugin seems to duplicate itself and I havent pinned down why.

```
# <bitbar.title>Weather</bitbar.title>
# <bitbar.version>v2.0.4</bitbar.version>
# <bitbar.author>Daniel Seripap</bitbar.author>
# <bitbar.author.github>seripap</bitbar.author.github>
# <bitbar.desc>Detailed weather plugin powered by forecast.io with auto location lookup. Supports metric and imperial units. Needs API key from http://developer.forecast.io.</bitbar.desc>
# <bitbar.image>https://daniel.seripap.com/content/images/2016/01/bb-weather_v1-3-5-1.png</bitbar.image>
# <bitbar.dependencies>python</bitbar.dependencies>
```

![screen_shot_2016-09-06_at_4_52_25_pm](https://cloud.githubusercontent.com/assets/157699/18290771/cde8d916-7452-11e6-846d-4209e52f4917.png)

**Comment by iosdeveloper** [comment]
Which version of BitBar do you use (you can check under Preferences)?

**Comment by digitalfiz** [comment]
I was on 1.5beta and I just noticed there is an update to 1.9. Trying that to see if it fixes it. It usually takes a day or so to happen.

**Comment by iosdeveloper** [comment]
v1.5 is really old. Please update.

**Comment by fenhl** [comment]
I am having this issue with BitBar 1.9.2.

**Comment by tresni** [comment]
I am seeing this as well..  I can reproduce on my Macbook Air pretty reliably.  It happens whenever an icon gets hidden due to the application window taking up too much space.  When I switch to an application with a smaller menubar footprint, then I have a second icon for whatever was hidden.  It's as if Bitbar thinks it was destroyed, re-creates it when it's told the menubar has visibility.

**Comment by digitalfiz** [comment]
This stopped when I updated to the latest version and hasn't happened since.

**Comment by tresni** [comment]
I wonder if you were hitting #21 .  Sounds like @fenhl and I may be having a different issue then you then.
