### ISSUE TITLE
How to pass an argument to the current script through a click?

### ISSUE THREAD

**Issue by DonSchado** [matryer/bitbar#368]
Hey! :)

Is it possible to have an clickable item, that refreshes the script with a given argument?
And how to access it inside of the script? 

So for example in *Ruby* it would be enough for me if the argument would be available in `ARGV` or `ENV`.

I think I don't understand the documentation, how to achieve that with the `bash` or `param` options.

**Comment by iosdeveloper** [comment]
You pass the absolute path to the script to `bash=..` and `param1=..`, `param2..` and so on are the arguments. Maybe look at one of the Ruby examples in matryer/bitbar-plugins.

**Comment by DonSchado** [comment]
hey, thanks for the quick response! :)

even after reading all the example plugins... (and trying a couple)
I don't get the argument into the script output to show it again in the plugin menu.
Even in the examples.

The interesting thing is that I see the arguments in the terminal (when I use `terminal=true`), but they are not available in the script.

so maybe I'm holding it wrong? 

```
#!/usr/bin/env ruby

puts [
  'test',
  '---',
  "click me | bash=#{$0} param1=foo param2=bar terminal=false",
  '---',
  "script: #{$0}",
  "ARGV: #{ARGV.inspect}"
]
```

- (terminal=false) ARGV is always an empty array
- (terminal=true) ARGV is empty in the menu, but `["foo", "bar"]` in the terminal


bitbar version is 1.9.2

**Comment by iosdeveloper** [comment]
Relates #323. This seems to be a common misunderstanding...

**Comment by DonSchado** [comment]
ah, my bad. was already expecting something like that. 

So the only way would be a tmp file that keeps the output?

**Comment by iosdeveloper** [comment]
Yeah, I believe this is a common solution.
