### ISSUE TITLE
OSX Sierra has trouble running plugins

### ISSUE THREAD

**Issue by dotwaffle** [matryer/bitbar#370]
I have a plugin executable that works when run from console, but when inserted in BitBar causes a `Couldn't posix_spawn: error 88` message. The plugin is a "Go" executable, named `myapp.5s.cgo` -- there is no bash involved which seems to be the problem with other issues.

This occurs with both v1.9.2 and the beta10 pre-release.

**Comment by dotwaffle** [comment]
<img width="263" alt="screen shot 2016-09-26 at 14 35 47" src="https://cloud.githubusercontent.com/assets/17210/18836140/8fd810ac-83f6-11e6-9cbf-2c78d4004aaf.png">

A quick screenshot, for context.

**Comment by dotwaffle** [comment]
It turns out that there is a Go update addressing Sierra compatibility.

Closing as not bitbar related -- upgrade to Go 1.7.1 when you compile your executable if you hit this bug!

**Comment by frakman1** [comment]
I am running into this with a `python` script that I wrote. It works when run from the console but doesn't work when run as a plugin. I get the same error but with error code 2:

![screen shot 2017-06-23 at 11 36 53 pm](https://user-images.githubusercontent.com/5826484/27505405-f51e8b9e-586c-11e7-9440-563e94898d7c.png)

I am using Sierra 10.12.5
Python version 2.7.10

**Comment by robertyu** [comment]
@frakman1 
Maybe you can check python path by "which python" and make sure the shebang is correct

**Comment by frakman1** [comment]
@mullender. This is an awesome tip that I really wish was in the README.md

**Comment by matryer** [comment]
Please submit a PR to add it to the README, and @ me…  I’ll merge it asap.
