### ISSUE TITLE
Multiply icons in menu bar on sleep when script has file extension (i.e timer.1h.js)

### ISSUE THREAD

**Issue by oleander** [matryer/bitbar#379]
Just found this bug. Here's some info how to produce and fix it.

## Reproduce

1. Add code below to `timer.1h.js` and place it in your plugins folder.
2. Run `chmod +x timer.1h.js`.
2. Start Bitbar `2-beta10` in OS X 10.12.1.
3. Put Mac to sleep, i.e by closing lid.
4. Wake up.

## Result

<img width="167" alt="aa983e22-ac82-11e5-8422-ea6c9ac88deb" src="https://cloud.githubusercontent.com/assets/220827/19917625/1688fe82-a0c5-11e6-99d5-2db7d85b9fdc.png">

## Expected

<img width="167" alt="aa983e22-ac82-11e5-8422-ea6c9ac88deb" src="https://cloud.githubusercontent.com/assets/220827/19917636/3651b57e-a0c5-11e6-9ea3-99f98e88476a.png">

## Fix

1. Rename `timer.1h.js` to `timer.1h`.
2. Run `chmod +x timer.1h`.
3. Restart Bitbar.

## Example file

``` javascript
#!/usr/bin/env node

setTimeout(function() {}, 10000);
```

Hope that helps :)

**Comment by oleander** [comment]
Already fixed in `oleander/bitbar`.

**Comment by warmup72** [comment]
It´s the same an 1.9.2 with a Bash-Skript
Symbolic-Link myDMSBar.4h.sh leads to 2 Icons after waking up my MBP
Chancing the ln-Name to  myDMSBar.4h seems to fix the problem.
