### ISSUE TITLE
Refreshing Resets Location

### ISSUE THREAD

**Issue by moshed** [matryer/bitbar#387]
refreshing resets the location. any way to stop this?

**Comment by rpunkfu** [comment]
I don't think so unfortunately, you can only change order within bitbar's icon group

**Comment by moshed** [comment]
you can originally set the order to wherever you want though. are you nat able to do that?

**Comment by rpunkfu** [comment]
I'm not, I can set order of apps within bitbar's icon group by naming them properly:

![naming](https://cl.ly/120K3W3H112m/Image%202017-01-03%20at%204.24.13%20PM.png)

Although I can't set whole group's position :( It always go back to last position on menubar:

![menubar](https://cl.ly/2I1U2R2X0o06/Image%202017-01-03%20at%204.25.48%20PM.png)

And I want this:

![menubar-correct](https://cl.ly/0Q07043g330R/Image%202017-01-03%20at%204.26.15%20PM.png)

**Comment by moshed** [comment]
you can ⌘ + drag the icons to move them (on sierra only i think) if thats what you want. however, refreshing resets the location to the last in the menubar which is why i opened this issue

**Comment by rpunkfu** [comment]
I know that, and that's exactly what I mean. I'm aware of cmd + drag of icons, but refresh / going back from sleep resets it

**Comment by moshed** [comment]
oh ok miscommunication then.  we both have the same issue. 😢

**Comment by jeremiahwright** [comment]
Same

**Comment by moshed** [comment]
yeah its a super annoying bug this issue wasnt marked as anything so i dunno if theyre planning on addressing it...

**Comment by xindi-dumbledore** [comment]
agree on having a option to stop refreshing after waking up~ is there any way to tackle this?

**Comment by gingerbeardman** [comment]
See code change in #502
