### ISSUE TITLE
HDD Wake during Sleep

### ISSUE THREAD

**Issue by darkenvy** [matryer/bitbar#392]
Running mdf.1m.sh . The app periodically querys HDD's and therefore wakes up my external HDD about once a minute. I woke up to it spinning up and down repeatedly. Any way to configure script refresh rate individually? And not allow scripts to run when sleeping?

**Comment by alexrockt** [comment]
Change the 1m to 30m or 2h or 1d ([see here](https://github.com/matryer/bitbar#configure-the-refresh-time))

**Comment by darkenvy** [comment]
Oh. Well that was easy. 

Would still be nice to not have it run when OSX is sleeping. It does for some reason which is peculiar.

**Comment by alexrockt** [comment]
Maybe have a look at the Energy Saver settings - could it be that Power Nap is preventing your laptop from "real" sleeping?

**Comment by darkenvy** [comment]
I can't be sure if my computer is still waking from sleep. I set the script to run bi-hourly. Thats 4 times a night at most so I'm okay with that. 

PS: It wasn't power nap. Thanks guys for the help!
