### ISSUE TITLE
When's a new release coming up?

### ISSUE THREAD

**Issue by phaistonian** [matryer/bitbar#406]
Silly question, still I think 2-beta10 could use some love :)

**Comment by frakman1** [comment]
Yes, I am ready.

**Comment by mm2270** [comment]
The last full release was over a year ago (Aug 30, 2016). Is development dead on this? The beta has been in beta for a long time. It would be nice to see a new full release. Any update on this?

**Comment by tiagoad** [comment]
Any updates on this issue?

**Comment by gingerbeardman** [comment]
Any update will be released when it is ready.

If something is not working for you, please file an issue.
