### ISSUE TITLE
param with spaces and quotes is not behaving as expected in python.

### ISSUE THREAD

**Issue by syllogismos** [matryer/bitbar#407]
I'm trying to do a simple script that gets all my ec2 instances and when I click on a name of the machine it copys the ssh command to clip board, I'm not able to figure out how to copy to clipboard in python.

`item` is of the form `(machine1, 119.30.52.12)` and etc, all I'm trying to do is when I click on `machine` I want the ssh command to get copied to clipboard.

so I'm using the pip package pyperclip that makes copying to clipboard straightforward.
so on bash if you type `python -c 'import pyperclip;pyperclip.copy("Copy me to Clipboard")'` it gets copied to clipboard. I want the command `ssh -i key.pem ubuntu@ipaddress` to be copied to clipboard.

```
sorted_by_name = [('machine1', 'ipaddress')]
for item in sorted_by_name:
    copy_command = '"ssh -i ~/.ssh/key.pem ubuntu@%s"' % (item[1])
    param2 = "\'import pyperclip; pyperclip.copy(%s)\'" % copy_command
    python_command = 'python param1=-c param2=%s' % param2
    print "%s | bash=%s terminal=false" % (item[0], python_command)
    print "---"
```

using this script if I do `run in terminal` this gets printed in shell
```
machine1 | bash=python param1=-c param2='import pyperclip; pyperclip.copy("ssh -i ~/.ssh/key.pem ubuntu@ipaddress")'
---
```

but when I actually click on the bitbar name, its not working.

**Comment by syllogismos** [comment]
basically, how to copy something to clipboard in a python plugin.

**Comment by syllogismos** [comment]
```
sorted_by_name = [('machine1', 'ipaddress')]
for item in sorted_by_name:
    copy_command = '"ssh -i ~/.ssh/key.pem ubuntu@%s"' % (item[1])
    # param2 = "\'import pyperclip; pyperclip.copy(%s)\'" % copy_command
    # python_command = 'python param1=-c param2=%s' % param2
    bash_command = "echo param1=%s param2=| param3=pbcopy" % copy_command
    print "%s | bash=%s terminal=false" % (item[0], copy_command)
    print "---"
```

got it working using pbcopy like above

**Comment by syllogismos** [comment]
sorry I was mistaken, this didnot work, any help regarding sending something to clip board from python is appreciated.

**Comment by oleander** [comment]
You can't use `|´ as a parameter. Do something like `bash="/bin/bash" param1="-c" param2="'ls | pbcopy'"` where `ls` is your script.

**Comment by syllogismos** [comment]
```
#! /usr/bin/python
import random

print "TEST"
print "---"

def random_str():
    return ''.join([random.choice('abcdefghijklmnopqrstuvwxyz') for x in range(7)])
sorted_by_name = [{'key': random_str(), 'ip': random_str(), 'name': random_str()}
                  ,{'key': random_str(), 'ip': random_str(), 'name': random_str()}]

for item in sorted_by_name:
    copy_command = "echo ssh -i ~/.ssh/%s.pem ubuntu@%s | pbcopy" % (item['key'], item['ip'])
    print "%s | bash='%s' terminal=false" % (item['name'], copy_command)
    print item['ip']
    print "---"
```


The above plugin is working when terminal is true, but not when terminal is false, can you put the above script to a file called test.1m.py and put in your plugin folder, and see what I'm doing wrong? All I'm trying to do is when I click the ssh command gets into my clipboard, when terminal is true, it opens up a new terminal and executes the pbcopy command and copys my ssh command to clipboard, but when terminal is false, the clipboard doesn't get updated with the new ssh command.

**Comment by oleander** [comment]
You need to set `bash="/bin/bash"` and `param1="-c"`, then you can pass the script as normal in param2, i.e `param2="ssh server | pbcopy"`.

**Comment by syllogismos** [comment]
Thank you so much, its finally working.

Here is the final working code.

```
#! /usr/bin/python
import random

print "TEST"
print "---"

def random_str():
    return ''.join([random.choice('abcdefghijklmnopqrstuvwxyz') for x in range(7)])
sorted_by_name = [{'key': random_str(), 'ip': random_str(), 'name': random_str()}
                  ,{'key': random_str(), 'ip': random_str(), 'name': random_str()}]

for item in sorted_by_name:
    copy_command = "echo ssh -i ~/.ssh/%s.pem ubuntu@%s | pbcopy" % (item['key'], item['ip'])
    print "%s | bash='/bin/bash' param1='-c' param2='%s' terminal=false" % (item['name'], copy_command)
    print item['ip']
    print "---"
```
