### ISSUE TITLE
Node: Permission denied on filesystem via Bitbar, Works in Terminal

### ISSUE THREAD

**Issue by pReya** [matryer/bitbar#411]
I have a Node.js plugin, that reads and writes from/to the filesystem, using something like this:
`fs.writeFileSync('example.txt', 'Test123');`

When I make the plugin executable and run it on the terminal, everything works fine. However when I want to run it as a Bitbar plugin (no changes, exactly the same file), i get 

`ERROR: ACCES: permission denied, open 'example.txt'`

Yes, the directory in which the plugin is located has write privileges for all users. Any other ideas, where this might come from?

**Comment by oleander** [comment]
Can you post your script?

**Comment by pReya** [comment]
Sure thing @oleander. This is my test script:
`#!/usr/bin/env /usr/local/bin/node

var fs = require('fs');
const FILENAME = 'file.txt';
 

function writeToFile(high, low)
{
    fs.writeFileSync(FILENAME, "TEST");
    console.log('written');
}

writeExtremaToFile(0,0);
`

Running this in the command line via `node script.1m.js` works fine. However, running this as a Bitbar plugin will result in a `ERROR: EACCES: permission denied, open 'file.txt'`. I've tried all chmod settings, and even with 777 applied to both the directory and the file, I still get the same error.

**Comment by oleander** [comment]
Try replacing `FILENAME` with the absolute path to the file and see if you get the same error message.

**Comment by pReya** [comment]
@oleander Thank you so much! It's working now. I guess I could have tried that myself, seems to make sense.
