### ISSUE TITLE
add input textbox

### ISSUE THREAD

**Issue by reteps** [matryer/bitbar#413]
Way to input text?

**Comment by oleander** [comment]
Doesn't this already exist? 

``` 
Command 1|bash="cmd1"
Command 2|bash="cmd2"
```

**Comment by reteps** [comment]
I need to rephrase this. Is there a way to add a input textbox?

**Comment by reteps** [comment]
see #389 and #172

**Comment by reteps** [comment]
You cant do `Command 1|bash="cmd1"` b/c you need a script

**Comment by oleander** [comment]
Combine my first post with something like `osascript -e 'Tell application "System Events" to display dialog "Enter the project name:" default answer ""' -e 'text returned of result'`.

**Comment by reteps** [comment]
Wow! Thanks.

**Comment by bsell93** [comment]
I was looking for a simple yes/no dialog, and this helped issue helped me. In case anyone ends up doing the same here is what I ended up with. (Sorry for resurrecting this. :p)

```python
import subprocess
def get_yes_or_no_from_alert(alert_text):
    process=subprocess.Popen("""osascript -e 'display alert \"""" + alert_text + """\" buttons {"No", "Yes"}'""", shell=True, stdout=subprocess.PIPE)
    output=process.communicate()[0]
    if "yes" in str(output).lower():
        return True
    return False
```

This allowed for a basic yes/now with dynamic message.
