### ISSUE TITLE
Set hidden folder as plugin directory 

### ISSUE THREAD

**Issue by astropanic** [matryer/bitbar#414]
How I can set a hidden folder as plugin directory ?

For example ```~/.config/bitbar``` ?

Even I have show hidden folder enabled in Finder via ```defaults write com.apple.finder AppleShowAllFiles YES``` and seeing hidden folders, when I open bitbar and want choose the plugin directory, Finder opens, but don't display the hidden folders.

Any solution for that ?

**Comment by iosdeveloper** [comment]
See https://github.com/matryer/bitbar/blob/master/Docs/DistributingBitBar.md#settings
