### ISSUE TITLE
jq: command not found, even though installed on system?

### ISSUE THREAD

**Issue by reteps** [matryer/bitbar#415]
my code: 
```
echo -n "E:"; curl -s "https://api.gdax.com/products/ETH-USD/ticker" | jq -r '.bid'
```

```
which jq
/usr/local/bin/jq
```

**Comment by reteps** [comment]
When I run it from the terminal, it works fine! whats up?

**Comment by oleander** [comment]
Your environment isn't loaded. You need to run your script using `/bin/bash -c ...` or `/usr/bin/sudo -u you -i a-script.sh`.

**Comment by oleander** [comment]
More info can be found here https://github.com/oleander/bitbar/commit/9792c95805d1abc97d4afc2cdbbc460fc7a66539#commitcomment-22144737

**Comment by reteps** [comment]
what is the `...`? the script?

**Comment by oleander** [comment]
Yes.

**Comment by reteps** [comment]
hmm. still isn't working.
```
/bin/bash -c echo -n "E:"; curl -s "https://api.gdax.com/products/ETH-USD/ticker" | jq -r '.bid'
```
same "jq" not found error"

**Comment by oleander** [comment]
Bash requires a couple of extra params to work, `sudo` with the `-i` flag as shown above would be easier.

**Comment by reteps** [comment]
but then would I need a seperate file to run `myscript.sh`

**Comment by reteps** [comment]
Thanks for helping!!!

**Comment by oleander** [comment]
Aha, I missed your `|`. Try this `/usr/bin/sudo -u you -i bash -c 'echo -n "E:"; curl -s "https://api.gdax.com/products/ETH-USD/ticker" | jq -r ".bid"'`

**Comment by reteps** [comment]
perfect, thanks!

**Comment by YDundie** [comment]
> Aha, I missed your `|`. Try this `/usr/bin/sudo -u you -i bash -c 'echo -n "E:"; curl -s "https://api.gdax.com/products/ETH-USD/ticker" | jq -r ".bid"'`

Bruv you a lifesaver

**Comment by glowinthedark** [comment]
Provide the absolute path to `jq`:

`which -a jq` will show something like e.g.:

```python
>>> /usr/local/bin/jq
```

Now instead of `jq -r ".bid"'` use `/usr/local/bin/jq -r ".bid"`

**Comment by Dizlen** [comment]
> /usr/local/bin/jq...

Thank you! Pointing directly to the location of it fixed my issue.

**Comment by TOPWN** [comment]
> Provide the absolute path to `jq`:
> 
> `which -a jq` will show something like e.g.:
> 
> ```python
> >>> /usr/local/bin/jq
> ```
> 
> Now instead of `jq -r ".bid"'` use `/usr/local/bin/jq -r ".bid"`
> 
> ### Why should I use an absolute path?
> Because xbar/bitbar does not use your user's `$PATH` environment, and instead uses a restricted env that does not include `/usr/local/bin` in the `$PATH` (similar to the env `crontab` uses). If you do want to use your user's environment then do it explicitly at the top of the script with `source ~/.bashrc` (if using bash) or `source ~/.zshrc` (if using zsh) — but be aware that this might slow down your scripts depending on what you have in your shell config files. A better, safer and faster alternative would be to put at the top of your script
> 
> ```shell
> export PATH=/usr/local/bin:$PATH
> ```

you are a lifesaver!

**Comment by AshokkumarMuthukrishnan** [comment]
<img width="309" alt="Screenshot 2023-01-16 at 8 19 15 PM" src="https://user-images.githubusercontent.com/29630306/212706094-e93d8e03-909a-448f-be94-ea8f246b7b56.png">

Folks,
Can anyone help how to fix this one? In the GitLab pipeline, I'm getting this issue.
