### ISSUE TITLE
Text after embedded image won't display

### ISSUE THREAD

**Issue by frakman1** [matryer/bitbar#425]
(I am using python for a plugin and latest BitBar on Mac running Sierra 10.12.5)

Using the following code works:
```python
imsgicon="iVBORw0..."
print "|image="+str(imsgicon).encode("utf-8") 
```
and yields:
![image](https://user-images.githubusercontent.com/5826484/27661853-e44baeb2-5c29-11e7-8db8-5e70daf7a5c5.png)

But then I add some text after it and it won't show up. I get the exact same result as before. 

```python
imsgicon="iVBORw0..."
print "|image="+str(imsgicon).encode("utf-8") + "Text Here" 
```

**Where did the text go?**

**Comment by iosdeveloper** [comment]
ext before the `|`

**Comment by frakman1** [comment]
Interesting. 

> Put the text before the |

I would never have thought of that since that would imply that the text came first. But that worked! Thank you!

So, using this form:
```python
print "Text Here|image="+str(imsgicon).encode("utf-8") 
```
results in:

![image](https://user-images.githubusercontent.com/5826484/27668856-7a6c1f36-5c51-11e7-9b3d-5925132e3d6e.png)


Which seems backwards. However,

> or after a newline.

That definitely puts it on the next line which is not what the intent was. The desire (in this case) is to put the image first, with the text along side it.
Putting text after the new line like this:

```python
print "|image="+str(imsgicon).encode("utf-8") +"\n Text Here"
#is this what you meant?
```

results in:

![image](https://user-images.githubusercontent.com/5826484/27668911-d643383a-5c51-11e7-97f9-40a139eec7b8.png)



So how does this work? What if:
-  I wanted to put the image to the right of the text?
image <-> text
- I wanted to put the image to the right of the text with more text following it?
text <-> image <-> text 

The order things go in is not intuitive (at least not to me) and the instructions are not unambiguously clear.

**Comment by iosdeveloper** [comment]
Images can only appear to the left. You can use an icon font or emojis for inline.

**Comment by frakman1** [comment]
Ah. Thank you for clearing that up. That is definitely not documented.
