### ISSUE TITLE
Feature Request: Support `Underlined` text

### ISSUE THREAD

**Issue by frakman1** [matryer/bitbar#427]
Although `font`, `color` and `size` are all supported, I don't see a way to specify the underlining of text. Could this be added to BitBar as a new feature?

**Comment by iosdeveloper** [comment]
Should be straight forward to implement this using ANSI and `NSAttributedString` here: https://github.com/matryer/bitbar/blob/beta/App/BitBar/NSString%2BANSI.m#L37

**Comment by frakman1** [comment]
Thank you @iosdeveloper for pointing me to the code.

As I am a macOS objective-C newbie, I'm not sure what actual code change is needed in that file.

```objective-c
case 4: underlined
  self[NSUnderlineStyleAttributeName] = NSUnderlineStyleSingle; 
  break
```
Something like that?

**Comment by frakman1** [comment]
@iosdeveloper : Do you have some sample code I could try?

**Comment by iosdeveloper** [comment]
@frakman1 The example you provided earlier doesn't work?

**Comment by frakman1** [comment]
Sadly, No. That was a wild stab in the dark. I don't really know what I'm doing here I'm afraid.

![image](https://user-images.githubusercontent.com/5826484/28555703-8d79c32a-70cf-11e7-933b-43531ab7dbc3.png)

Some guidance would be greatly appreciated.

**Comment by frakman1** [comment]
**UPDATE**
@iosdeveloper 
Well I figured it out (eventually) 
```objective-c

      case 4: //underlined
        self[NSUnderlineStyleAttributeName] = [NSNumber numberWithInt:NSUnderlineStyleSingle];
        break;
```
Called using:
```python
    #UNDERLINE = '\033[4m'
    #END = '\033[0m'

print c.UNDERLINE + "Underlined " + c.END
```
Looks like this:

![image](https://user-images.githubusercontent.com/5826484/92006919-50900a00-ed13-11ea-8e38-4754637e23c6.png)

**Comment by frakman1** [comment]
I also added the crossed out attribute for fun. Too bad this project is no longer maintaned as I'd love to make a PR with these features:

![image](https://user-images.githubusercontent.com/5826484/92012242-31e14180-ed1a-11ea-88f2-a4ff6930d3c6.png)
