### ISSUE TITLE
Why is BitBar mounting any volume at start?

### ISSUE THREAD

**Issue by msztolcman** [matryer/bitbar#428]
Hi,

Few days ago I updated BitBar to version 1.9.2, previously used something like 1.5.x if I remember correctly. After upgrade, I realized that after every launch BitBar is mounting some volume (I have a software that shows me this kind of informations). This volume is not displayed in Finder, but `mount` in Terminal shows:

    /Applications/BitBar.app on /private/var/folders/d4/7xlcv4g14jg7vfr6dtm_n2qc0000gn/T/AppTranslocation/F4B8E8E8-939C-4424-947E-EFA060C826E6 (nullfs, local, nodev, nosuid, read-only, nobrowse, mounted by mysz)

After selecting Preferences -> Check for updates I got "Update Error!":
    
    BitBar can’t be updated when it’s running from a read-only volume like a disk image or an optical drive. Move BitBar to your Applications folder, relaunch it from there, and try again.

I am downloading BitBar from https://github.com/matryer/bitbar/releases/tag/v1.9.2, copying it to /Applications etc.

**Comment by therealbill** [comment]
This the MacOS App Translocation stuff Gatekeeper does. It is quarantining the app. It happens, for example, when you copy or move BitBar.app via command line. If you're still uncomfortable with that, you can do the following to make it stop:

1. Quit Bitbar
1. Verify it unmounts the app
1. run `xattr -dr  com.apple.quarantine /Applications/BitBar.app`
1. Start Bitbar

That should do it.

For more information on the quarantine bits, check out [this article](http://krypted.com/mac-security/app-translocation-services-os-x-10-12/).

**Comment by msztolcman** [comment]
@therealbill Oh, I spent a while because I was suspect Gatekeeper, but failed to find useful info about this... Article linked by you is great! Thanks!
