### ISSUE TITLE
Hidden content, be able to show on hover or click?

### ISSUE THREAD

**Issue by dimitrieh** [matryer/bitbar#441]
I wonder if it's possible for bitbar to contain hidden content and show it on hover or mouse click.

For example.. say you have a list of items and each list item contains a hidden description, we would be able to make that information visible without refreshing the script.

A simple animation which shows what i mean... (far too fancy of course)

![2017-09-27 15 16 23](https://user-images.githubusercontent.com/429659/30915410-0802695e-a397-11e7-8a80-602e17d2f88d.gif)

cc: @matryer

**Comment by matryer** [comment]
Have you considered submenus or the alternative feature?

**Comment by dimitrieh** [comment]
@matryer just found out ^^ closing! thanks!
