### ISSUE TITLE
How about click functions?

### ISSUE THREAD

**Issue by Hamburgle** [matryer/bitbar#459]
Am I allowed to request a feature? I would like to be able to use bitbar to be able to click on a menu item and in doing so launch a script (preferably Applescipt, but perhaps a shell script). My apologies if bitter already does this (I couldn't see how.)

**Comment by jacoblyw** [comment]
As of 2020, this is possible.

Bash.
Put this in your Bitbar folder as **doSomething.sh**:
```
#!/bin/bash
# <bitbar.title>Do Something</bitbar.title>
# <bitbar.version>v1.0</bitbar.version>
# <bitbar.author.github>Me</bitbar.author.github>
# <bitbar.author>JL</bitbar.author>
# <bitbar.desc>Do Something</bitbar.desc>


if [ "$1" = 'doSomething' ]; then
 # do something
  open .
fi


if [ "$1" = 'doSomethingElse' ]; then
 # do something
  open ~
fi

# build the menu, this is text with a cat icon
echo "Cat :smile_cat: | color='black'"
echo "---"
#menu entries, this one calls "doSomething" (above) without opening a terminal
echo "Click here to Do something      | color=#f23400 bash='$0' param1=doSomething     terminal=false"
echo "Click here to Do something else | color=#107F01 bash='$0' param1=doSomethingElse terminal=false"
```

Hope that helps.

**Comment by Hamburgle** [comment]
That's interesting, indeed exciting, but I don't see any downloadable version from 2020 on this page: https://github.com/matryer/bitbar/releases so which one do I download?

**Comment by franzuu** [comment]
Are clickable items possible with javascript also? 
I would like to call a function inside the script. I know it is possible with bash approach, but haven't found a way to do it with javascript. Any help or guidance is appreciated.

**Comment by gingerbeardman** [comment]
If you can call it on the command line, it's possible.

Taking inspiration from this stackoverflow answer: https://stackoverflow.com/a/64093383/28290

1. create `script.js`
    ```
    #!/usr/bin/env node
    console.log('Hello terminal');
    after that you must set executable permission:
    ```
3. `chmod +x script.js`
4. put it in a subfolder next to your xbar script and call it from your xbar script, [as in the example near the top of this issue](https://github.com/matryer/xbar/issues/459#issuecomment-595730309)
