### ISSUE TITLE
What is this？

### ISSUE THREAD

**Issue by wyfang** [matryer/bitbar#486]
![qq20180919-164502](https://user-images.githubusercontent.com/17900420/45741970-722d7f00-bc2b-11e8-844c-e06e8afcbc7f.png)

**Comment by gingerbeardman** [comment]
The plugin/script you're using is looking for Python in the wrong place. 

You'll need to charge the first line of the script to suit your system setup.

**Comment by wyfang** [comment]
Fine, I don't know much about these things, or thank you for your reply.
