### ISSUE TITLE
URLs in `href` can't contain & or '

### ISSUE THREAD

**Issue by garyking** [matryer/bitbar#487]
If they do, then the URL gets truncated to immediately before that character.

Does anyone know of a workaround for this? I tried escaping the character, replacing it with a URL encoded version, etc. but they don't work.

**Comment by garyking** [comment]
Problem seems to be related to another library I'm using.

**Comment by sindresorhus** [comment]
These characters are [valid unencoded in URLs](https://stackoverflow.com/a/41353282/64949). This is a BitBar issue.

**Comment by gingerbeardman** [comment]
Hey @sindresorhus of course they can be used in Bitbar as long as the programmer considers how to deal with these characters in their script. These characters (and others) can easily trip up programmers who are not experienced with shell scripting where they must be escaped quite strictly cc @garyking 

```
#!/bin/bash

echo "URLs"
echo "---"
echo "URL | href=http://www.example.com"
echo "URL+params | href=http://www.example.com/?punctuation='&candy_name=M&M"
```

I've reopened this but will close it upon your agreement. 👍

**Comment by garyking** [comment]
Alright thanks. I've forked the JS library and made my own changes to it to replace some of these characters.
