### ISSUE TITLE
Need to escape spaces twice in script paths

### ISSUE THREAD

**Issue by garyking** [matryer/bitbar#488]
This won't work. Running it in Bitbar runs the path as-is, so the full path is not passed as the first argument.

`Run script|bash="/usr/local/bin/node" param1="/space here/a.js"`

This works though: 

`Run script|bash="/usr/local/bin/node" param1="/space\\ here/a.js"`

So we have to double-escape spaces in paths. Please make it so this isn't necessary, thanks!

**Comment by gingerbeardman** [comment]
This sounds like a side-effect of not quoting params in your script? Please confirm.

**Comment by gingerbeardman** [comment]
See #489
