### ISSUE TITLE
Can't have spaces in params

### ISSUE THREAD

**Issue by garyking** [matryer/bitbar#489]
Please allow us to have spaces in params, so that they are then quoted together when passed to the script. 

So `Run script|bash="/usr/local/bin/node" param1="a.js" param2="a b"` would run as `/usr/local/bin/node a.js "a b"` rather than how it is now, `/usr/local/bin/node a.js a b`. Strangely enough, this seems to only be the case if `terminal=true`. If `false`, then the params are passed as if quoted.

**Comment by gingerbeardman** [comment]
have you tried quoting them in your script?
