### ISSUE TITLE
Vertical alignment of emoji seems off

### ISSUE THREAD

**Issue by jankeesvw** [matryer/bitbar#494]
I have a couple of Bitbar plugins, most of them show up as a Emoji in the status bar. The misalignment of them bothers me a bit. Is there a way to fix this?

![image](https://user-images.githubusercontent.com/167882/48476636-e5a0d680-e7ff-11e8-8108-d9a94551c656.png)

The 🐰 and the ✅ are Bitbar plugins.

**Comment by gingerbeardman** [comment]
The misalignment of BitBar entries is a known thing. There's a forked version of BitBar (the Swift rewrite) that may solve your for you, but it has its own issues.

**Comment by jankeesvw** [comment]
@gingerbeardman do you have a link for this Swift rewrite?

**Comment by gingerbeardman** [comment]
Look up to top of page > Fork (click number) > Network (left side bar) > scroll to second most popular fork (oleander)

https://github.com/oleander/bitbar

**Comment by lucaorio** [comment]
@gingerbeardman On Mojave, that version cannot be launched at login. It always trigger an _Unidentified Developer_ warning. :( 

Is there any chance to eventually have the vertical alignment fixed?

**Comment by gingerbeardman** [comment]
About "unidentified developer" https://www.macworld.co.uk/how-to/mac-software/mac-app-unidentified-developer-3669596/

**Comment by lucaorio** [comment]
@gingerbeardman I don't know if it's just me, but I already had the _Allowed From Anywhere_ option checked. I also went through the _Open Anyway_ process, but the alert pops up at every login.

**Comment by lucaorio** [comment]
@gingerbeardman I was kind of losing my mind on this haha I tried so many times, but I was still getting the error.

For whoever has my same, weird problem, try to run this. It worked perfectly! 🎉

`xattr -dr com.apple.quarantine "BitBar.app"`
Reference [here](https://apple.stackexchange.com/questions/202169/how-can-i-open-an-app-from-an-unidentified-developer-without-using-the-gui/202172)

**Comment by gingerbeardman** [comment]
Interesting you should need to do that. What did you use to extract the BitBar download?

**Comment by lucaorio** [comment]
Initially, I was downloading it with Vivaldi. I then tried both Safari and Chrome, but the error was still there.

However, now I have a slightly better aligned text but the app randomly crashes from time to time. 😭

**Comment by XanderLeaDaren** [comment]
Solved by @cedivad in #513 !
