### ISSUE TITLE
LOOKING FOR MAINTAINERS

### ISSUE THREAD

**Issue by austinbv** [matryer/bitbar#495]
Hey I am curious is this still maintained at all? Thanks!

**Comment by gingerbeardman** [comment]
Yes it is https://github.com/matryer/bitbar/commits/master

**Comment by m-cat** [comment]
PRs are being submitted but CI is failing and comments are being ignored. Example: https://github.com/matryer/bitbar/pull/474. No PR has been merged since May 7.

**Comment by gingerbeardman** [comment]
I'll look into CI

**Comment by gingerbeardman** [comment]
2016 release works just fine, but you are free to build the same binary today.

**Comment by ssbarnea** [comment]
I will give it a try. BTW, it would be nice to mention `brew cask install bitbar` as an alternative install method for those embracing the terminal.

**Comment by gingerbeardman** [comment]
@ssbarnea feel free to file a PR with that added to the docs, it is more than welcome

**Comment by xilopaint** [comment]
@gingerbeardman can we expect a stable release for v2 in the near future?

**Comment by gingerbeardman** [comment]
@xilopaint what is unstable for you?

**Comment by xilopaint** [comment]
> @xilopaint what is unstable for you?

Well, v2 was released as a beta.

**Comment by gingerbeardman** [comment]
What is in a name? Often in software development the final beta becomes the release version.

But seriously, if you have issues then please file bugs about them.

**Comment by xilopaint** [comment]
> What is in a name? Often in software development the final beta becomes the release version with no code changes other than the name.

The name is important since people can't be sure your software is stable or a "final beta" if you don't make it public. Like many people I've installed your software with Homebrew. That installed v1.9.2 which is considered the final version. If you think v2 beta 10 is mature enough to be released as final, please make it real so everyone will start to use it.

**Comment by gingerbeardman** [comment]
Oh, I see. Actually I use 1.9.2 myself so I see your point.

**Comment by nikolay** [comment]
@gingerbeardman `Check for Updates` fails, by the way.

**Comment by hdhurwitz** [comment]
> @gingerbeardman `Check for Updates` fails, by the way.

same for me

**Comment by pvegh** [comment]
> What is in a name? Often in software development the final beta becomes the release version with no code changes other than the name.
> 
> But seriously, if you have instability problems then please file issues about them.
> 
> If it works, then use it. 👍

Wow, kinda true and wrong at the same time.
Are you using Android beta? Or windows prerelease? The same one for years?
Beta means "warning", not for everyone, might break.
If it's stable release it.
_Release early, release often._

**Comment by xilopaint** [comment]
"Is this project dead?" is the title of this issue. And the answer is "yes". Unfortunately.

**Comment by gingerbeardman** [comment]
I do not agree with the above.

**Comment by xilopaint** [comment]
> I do not agree with the above.
> 
> The project is in a difficult position. But it's not dead, nor is it abandoned.

The last commit that changed the codebase dates from August 2016. There are 28 open pull requests, the vast majority are 3 years old. There's no code being written, there's no code being reviewed.

Sorry, but it feels like a dead project.

**Comment by gingerbeardman** [comment]
With all due respect, that view is from the outside. You have _no idea_ what is going on the other side.

https://medium.com/@fommil/the-open-source-entitlement-complex-bcb718e2326d

**Comment by ssbarnea** [comment]
Based on the thread on this ticket I would rename it to "looking for maintaiers". When a project is reaching a stage like this, what is constructive is to look for others that can take care of its maintenance.  

I do not think that @xilopaint was impolite and while he may have no idea about what is happening on the other side, his comments is also true.

One thing that I learned over the years of maintaining various open-source projects is that you should be realistic abotu what can you expect as an outcome: if you realise soon that you will never make money out of it and that you will reach a point where giving your "child" for adoption would be better for both, is ok. The fun part is that with code you don't have to give-up control completly,... the bad part is to get used to the idea that new maintaines may steer the project in a direction that may not be exactly what you are dreaming about. 

One thing is sure, we all get emotional about it...

**Comment by nikolay** [comment]
@gingerbeardman Submitting PRs, when there's nobody to review or merge them, is a waste of time. Not all OSS users are programmers and not all program on the platform of the OSS they use! OSS contributions are not only contributors of code, but also of feature requests, ideas, feedback, bug reports, etc. **We all contribute to this project** - like it or not, with or without PRs! So, easy on your patronizing attitude!

To me, the most basic signal that an OSS is dead is when the Update feature shows an error! And BitBar does!

**Comment by nikolay** [comment]
Also, the last commit in master is from May 7, 2018, i.e. more than one year ago, and it was a merged PR. This is far from a release, far from showing any vital signs!

**Comment by m-cat** [comment]
Agreed with these guys ^. We are not trying to be impolite Matt, but it is frustrating that the project has been dead for years and you can't even admit that. Why not pass on maintainership to another competent dev? There have been a lot of us who have made contributions here and who have long histories of maintaining open source projects. It certainly would be a better use of your time than posting random Medium articles without any explanation, and then closing the issue as if it's been resolved.

**Comment by gingerbeardman** [comment]
Just to clear a few things up: I am not the project owner, I'm just an interested guy that volunteered to help field issues. I'm the type that likes to act rather than discuss, so I sent a tweet and here we are.

https://twitter.com/gingerbeardman/status/992312705217265665

Any of you could have done the same, and can still do so: if you want to become a maintainer, then you need to contact the project owner @matryer (which, although we share a similar first name, is definitely not me).

**Comment by xilopaint** [comment]
> Also, the last commit in master is from May 7, 2018, i.e. more than one year ago, and it was a merged PR. This is far from a release, far from showing any vital signs!

This commit just updated README. The last commit that changed the code base is from August 2016.

**Comment by dimitrieh** [comment]
Related request for more transparency about continued development ;). I would love to see this project get a new boost or an official fork.

**Comment by matryer** [comment]
@austinbv @m-cat @ssbarnea 

Hey all, apologies for my radio silence, I've had a very busy year with a lot of demands on my focus and I haven't been able to give BitBar the love it deserves. 

However, I am *more than happy for others to join in to help maintain the project*. My reluctance comes from the fact that everybody wants BitBar to do something slightly different, and so the more maintainers we have, the more bloat the project will take on. But if we can agree a minimalistic approach to what gets added, and focus on bug fixing etc. in the short term, then pleeeeease let me know and I'll add you as a maintainer.

**Comment by matryer** [comment]
To bring the repo back to life, I propose we take the following action:

1. Close all stale PRs (heartbreaking for some, but a simple move like this will put everybody back on the same page)
1. Bring in the good fixes and improvements from the forks (the owners of the forks are welcome to become maintainers, there's no point dividing our efforts)
1. Release v2.0.0 as a major milestone marking the fresh start for the project

@gingerbeardman @austinbv @m-cat @ssbarnea What do you think?

**Comment by gingerbeardman** [comment]
Sounds good. 

I'd ask if we're going to be so bold about things, why not just move lock-stock to the Swift fork which should hopefully ensure a longer lifetime?

**Comment by m-cat** [comment]
> Close all stale PRs (heartbreaking for some, but a simple move like this will put everybody back on the same page)

From what I remember, some of the PRs were good, just waiting on CI issues to be resolved. I would consider ignoring CI and merging them, if there are no other issues. If there are issues with the PR, give the contributors one month to whip the PRs into shape.

I know 30 PRs is a lot to manage considering you have limited resources, but instead of closing them all, just punt them back to the contributors. If they're no longer active, then just close the PR.

I can help with some of the workload, though I'm thinking my rate would be reviewing one or two PRs every weekend. I was really excited to help, some time ago, because I love the project and wanted to polish up its rough edges. But I no longer have much time.

**Comment by austinbv** [comment]
I am happy to hop in and contribute too

**Comment by luckman212** [comment]
Happy new year! Here's hoping 2020 brings a revival of BitBar... 🎉

**Comment by fregante** [comment]
> Happy new year! Here's hoping 2020 brings a revival of BitBar... 🎉

BitBar 2.0.0 is the good news that 2020 needs

**Comment by exside** [comment]
Would be awesome if this jewel gets some new life on the dev side =)

**Comment by kdeldycke** [comment]
FTR, there is an alternative Swift-based project to BitBar, and seems to be actively maintained: https://github.com/swiftbar/SwiftBar

**Comment by gingerbeardman** [comment]
SwiftBar (above) is currently 10.15+ only

**Comment by matryer** [comment]
I made a proposal to bring the SwiftBar code into BitBar and blend the two projects together. I'd love to get all your views on the issue over at https://github.com/swiftbar/SwiftBar/issues/95.

**Comment by matryer** [comment]
Please see https://github.com/matryer/bitbar/issues/607
