### ISSUE TITLE
both Refresh?

### ISSUE THREAD

**Issue by ZCY01** [matryer/bitbar#497]
I have three plugins, eg:

> test.30s.py    vocabulary.py  weather.15m.py

I found that the three plugins have refresh at the same time every 30 seconds.
actually, I just want test.30s.py to refresh every 30 seconds. You knon, some plugins may take a long time to refresh.
How to fix it?

**Comment by gingerbeardman** [comment]
For those 3 scripts

Test (every 30 second refresh)
Vocabulary (default refresh, see inside plugin)
Weather (every 15 minutes refresh)

Are you seeing different to these times? 

If so please provide a log or capture of the behaviour you are seeing.
