### ISSUE TITLE
Only refresh script plugin on click

### ISSUE THREAD

**Issue by himat** [matryer/bitbar#515]
Is it possible, that instead of having the plugin refresh according to the time specified by the script name, that it can only refresh when I click on the menubar item?
I have a world clock script plugin that shows the times in the dropdown that opens when I click the menubar name. I don't usually need to look at the times in different time zones, so I feel like it's just wasting the CPU if I have the script run every 1 minute. I only need it to show the correct times when I click on the name to open the dropdown. Is this possible to do?

Or at least, is it possible to have it refresh on click IN ADDITION to every x sec/min/hours? 
This way, I could at least just have the file name be some super long refresh time like 300 days, but it would still refresh whenever I open the menu bar name, so that would work for me.

**Comment by gingerbeardman** [comment]
First, I would recommend to measure the CPU. Having it run every minute may not be that bad at all.

Your request is not currently possible, as you probably know. For the sake of docs here are some alternatives:

1. Or add an item to the bottom of the menu `echo "Refresh | refresh=true"` (or similar for the language of your plugin) which will allow you to refresh on demand. This will require a couple of extra clicks to open/refresh/open again. See: https://github.com/matryer/bitbar-plugins/blob/master/Tutorial/refresh.sh

2. You can add ` | refresh=true` to the end of the menu icon line, but it will prevent the menu opening. This may be acceptable in plugins that do not have a menu.
