### ISSUE TITLE
use of Run in Terminal

### ISSUE THREAD

**Issue by koddea** [matryer/bitbar#516]
Sorry if it is duplicate but I'm having difficulty to understand use of "Run in Terminal".

Could you please tell me the purpose of this menu item?

**Comment by gingerbeardman** [comment]
It will run pen Terminal and run the script there. Useful for debugging and some other things. Not so useful to non-technical end users.

The Distro version of BitBat does not have this menu if you'd rather not see it.

https://github.com/matryer/bitbar/blob/master/Docs/DistributingBitBar.md
