### ISSUE TITLE
bitbar can't read env variable in ruby

### ISSUE THREAD

**Issue by eldemcan** [matryer/bitbar#518]
I see in many plugins that bitbar is not able to read from env variable.

1.) set env variable export API_KEY="value"
2.) source terminal 
3.) in ruby `API_TOKEN = ENV.fetch('API_TOKEN')`

when I print API_TOKEN in bitbar it is empty. if I run the same script in terminal using `ruby <script>` I can see that it has access to ENV variable.

**Comment by gingerbeardman** [comment]
BitBar doesn't run in the same environment the Terminal applications runs in.

So you need to export the environment into your plugin.

Maybe this will help: https://github.com/matryer/bitbar/issues/75#issuecomment-239941497

**Comment by matryer** [comment]
Closing as it appears to be answered.
