### ISSUE TITLE
looking for help creating a plugin

### ISSUE THREAD

**Issue by C4Wiz** [matryer/bitbar#524]
i am trying to parse info from a url, http://ip:port/api/info
the following is the returned data:

```
data: {"type":"bridgeInfo","data":{"uptime":520.456924575,"heap":12571936,"osInfo":"Linux x64, Release 4.19.73-Unraid","hbVersion":"0.4.50"}}

data: {"type":"bridgeUpdateAvailable","data":{"updateAvailable":false,"latestVersion":"0.4.50"}}
```
the following is the documentation from the source being polled:

Usage

homebridge-info acts as an EventSource which can be subscribed under /api/info:

var eventSource = new EventSource('http://ip:port/api/info');
where ip is the IP address of your homebridge server and port is the port configured for hombridge-info.

To receive events, add a listener to eventSource:

eventSource.addEventListener('message', function(e) {
    var result = JSON.parse(e.data);
    console.log("got message: " + JSON.stringify(result));
}, false);
result is a JSON object with two properties:

type: either bridgeInfo or bridgeUpdateAvailable
data:
for type === "bridgeInfo":
uptime - uptime of the homebridge process
heap - heap memory used by the homebridge process
osInfo - info about the host
hbVersion - The version of the hombridge instance

for type === "bridgeUpdateAvailable": updateAvailable
true, if the installed version of homebridge is older than the latest release
false, if not
"unknown", if either the running or latest version could not be determined
latestVersion - either "unknown" or the version number of the latest homebridge release

**Comment by matryer** [comment]
Sorry, we can't offer plugin support at this time.
