### ISSUE TITLE
Bitbar doesn't play nicely with menu hiders

### ISSUE THREAD

**Issue by expelledboy** [matryer/bitbar#527]
Do to menu items being re-created in bitbar menu bar hiders such as [Dozer](https://github.com/Mortennn/Dozer/issues/47) can not manage them. I have useful bitbar plugins, which I want visible at all time, finding their way to the end of the menubar list (which is inside the hidden area of Dozer).

Would it be possible to prevent bitbar from dynamically re-creating the menu items, until you explicitly click on a reload button?

**Comment by gingerbeardman** [comment]
Use this version of BitBar https://github.com/matryer/bitbar/pull/502 to avoid refreshes messing up order.

I use it personally with Dozer.

**Comment by dylanrossmurphy** [comment]
Hi. I also have the same problem which is when I wake the system the menu bar icon always moves. How do I fix this?

**Comment by gingerbeardman** [comment]
@dylanrossmurphy did you try the solution in the comment above yours?

**Comment by dylanrossmurphy** [comment]
What was the solution. I didn’t understand

**Comment by dylanrossmurphy** [comment]
I use the current bit bar version

**Comment by dylanrossmurphy** [comment]
How do I download version #502 ?

**Comment by gingerbeardman** [comment]
@dylanrossmurphy I've added an (unsigned) build to #502

https://github.com/matryer/bitbar/pull/502#issuecomment-597561941
