### ISSUE TITLE
where is the plugins directory?

### ISSUE THREAD

**Issue by pswenson** [matryer/bitbar#528]
I have a locked down (Jamf) Mac, so I need to instal the plugins directly in the plugins directory.  Where is it? 

I see a lot of doc about the plugins directory, but no doc on where it is.  It didn't prompt me for a location when it started.

**Comment by gingerbeardman** [comment]
BitBar.app > Menu Item > Preferences > Open Plugin Folder...

**Comment by pswenson** [comment]
OK, deal is that I was using the BitBar distro, not the Bitbar.... not sure what distro is for but when I switched to Bitbar it's obvious :). thanks!
