### ISSUE TITLE
macOS Catalina and Documents folder security

### ISSUE THREAD

**Issue by welby12** [matryer/bitbar#529]
I'm having trouble granting permissions for Bitbar to view my ~/Documents folder on a clean install of the Catalina GM

At first Bitbar didn't even show up in Security & Privacy -> Privacy -> File and Folders, until I changed my Plugin folder to ~/Downloads, and saw a prompt to grant it access to it. 

When I change the Plugin folder to ~/Documents, it still doesn't have an option to grant it access. I'm suspecting this is the reason I'm having trouble loading a plugin from that path at the moment. 

https://i.ibb.co/n39hwNG/bitbar.png

**Comment by zendraxl** [comment]
Any luck with this?

**Comment by zendraxl** [comment]
@gingerbeardman @matryer any help with this?

**Comment by gingerbeardman** [comment]
I'm not going to Catalina in the foreseeable future so I myself can't help with this, sorry.

**Comment by zendraxl** [comment]
Shame. Hopefully someone will figure it out or the app might get an update for this.

**Comment by matryer** [comment]
@zendraxl this is strange, I don't know how the new permissions are supposed to work in macOS Catalina but I'm running Bitbar with no problem.

**Comment by zendraxl** [comment]
@matryer I have same issues as described by @welby12 so I guess no one is able to run it on Catalina. Any chance you might fix it?

**Comment by welby12** [comment]
One great thing on Mac is that you can easily boot to an external hard drive, so you can install Catalina there. You can even make a snapshot with <code>tmutil</code>, so you can always go back to a pristine install easily. 

I haven't had time to look into this lately, but from what I could tell Bitbar isn't working on a clean install of Catalina.

**Comment by gingerbeardman** [comment]
> I haven't had time to look into this

Me neither, time is most my valuable asset.

**Comment by matryer** [comment]
I just tried this and it worked for me. I set my plugin folder to something like `~/code/bitbar-plugins` and it was able to run plugins inside it. I could even install them from the getbitbar.com website.

**Comment by zendraxl** [comment]
@matryer but not in Catalina?

**Comment by gingerbeardman** [comment]
He's on Catalina, see https://github.com/matryer/bitbar/issues/529#issuecomment-560327368

**Comment by zendraxl** [comment]
@gingerbeardman I don't think so. If I ignore the way how I understood it, then why @welby12 would reply like that?

**Comment by mtl-wgtwo** [comment]
@zendraxl FWIW, bitbar works fine for me on Catalina (10.15.1).  I have my bitbar folder set to ~/.bitbar though, not Documents.  It _seems_ to work when I set it to ~/Documents, but there are so many non-script things in there that it is quite messy.

**Comment by zendraxl** [comment]
Moving outside of common directories work for me also. Thanks.

**Comment by matryer** [comment]
I'll add a note to the README homepage.
