### ISSUE TITLE
Text placement slightly too high

### ISSUE THREAD

**Issue by szhu** [matryer/bitbar#533]
Here's a screenshot of BitBar next to two text-oriented menu bar apps ([ItsyCal] and [Next Meeting]).

![image](https://user-images.githubusercontent.com/1570168/71042193-eaf5e200-20df-11ea-9912-70fc03dceda1.png)

I think the BitBar text is slightly too high?

[ItsyCal]: https://www.mowglii.com/itsycal/
[Next Meeting]: https://apps.apple.com/us/app/next-meeting/id1017470484

**Comment by gingerbeardman** [comment]
Dupe https://github.com/matryer/bitbar/issues/268 & #105 

Solved in #513
