### ISSUE TITLE
BitBar don't show output of Python 3.x script.

### ISSUE THREAD

**Issue by SkyYkb** [matryer/bitbar#538]
Hi, I can't figure out that why BitBar don't show output data:
# Environment
The script I'm using:
https://github.com/Anthonyeef/wuhan-virus-bitbar-plugin/blob/master/wuhan.10s.py
Python installed:
Python 3.8.1 with pip 20.0.2.

# Issue
BitBar always shows a yellow triangle with a exclamation mark on my menu bar, like this:
<img width="34" alt="image" src="https://user-images.githubusercontent.com/44992049/73924352-53ef1e80-4907-11ea-8b34-790f727d77ab.png">
And shows "launch path not accessible" in the sub menu like this:
<img width="233" alt="image" src="https://user-images.githubusercontent.com/44992049/73924446-7a14be80-4907-11ea-8a8b-8915a3039438.png">

Thanks.

**Comment by gingerbeardman** [comment]
Is `/usr/local/bin/python3` valid on your system?

Did you make the wuhan plugin executable? `chmod +X wuhan.10s.py`

**Comment by SkyYkb** [comment]
Thanks, `chmod +x` solved my problem.
Silly me! When I download script from GitHub, the file permission is 644 by default. I think it's good to add this to README file.
