### ISSUE TITLE
Bitbar raised some critical problems to my Macbook pro

### ISSUE THREAD

**Issue by BBuniverse** [matryer/bitbar#539]
After using the plugins named Cryptocurrency, download from [this site](https://github.com/matryer/bitbar-plugins), some problems show up suddenly.

1. The desktop background becomes black suddenly.
2. I cannot switch applications by command + tab. 
3. Dock disappears even though I turn off and then turn on inside the System Preferences.
4. All gestures on the trackpad become useless.

My system is macOS 10.15.2
Download the bitbar from [the site](https://github.com/matryer/bitbar/releases/tag/v1.9.2)

Some solution has been tried after uninstalling bitbar:
1. Restart the computer
2. Log out the user and re-log on

**Comment by gingerbeardman** [comment]
Which crypto plugin exactly did you use?

Have you run other plugins ok before?

No plugin would affect the things you've described. But I'm happy to troubleshoot

**Comment by BBuniverse** [comment]
1. Maybe all plugins inside the [folder](https://github.com/matryer/bitbar-plugins/tree/master/Cryptocurrency), because I switched those plugins by changing the plugins folder directly. 
2. I tried some plugins before, such as Network, Finance, and Tools. By the way, these three plugins worked fine and very useful. I switched those plugins by changing the plugins folder directly. 

I just update my system to macOS 10.15.3. However, those bugs happened on my computer do not be solved by updating.

**Comment by BBuniverse** [comment]
Delete the file desktoppicture.db located in ~/Library/Application Support/Dock/. The computer will create a new one.

This [site](https://apple.stackexchange.com/questions/334077/revert-killall-kill-dock
) helps me fix all the problems I asked temporally. Maybe some potential bugs will come up. So far so good for me.

**Comment by gingerbeardman** [comment]
Congrats on finding your solution!

Hopefully you see that the problem and solution were nothing to do with BitBar?
