### ISSUE TITLE
Question about contributing a plugin.

### ISSUE THREAD

**Issue by SkyYkb** [matryer/bitbar#549]
Hi, there!
So if I contributed a plugin to BitBar-Plugin repo, how should I update my plugin? Do I need to open a new pull request?
Btw, If I want to use my own GitHub repo to show and introduce my plugin, can I contribute my plugin to BitBar-Plugin repo?
Thanks.

**Comment by gingerbeardman** [comment]
> So if I contributed a plugin to BitBar-Plugin repo, how should I update my plugin? Do I need to open a new pull request?

Yes, new PR.

> Btw, If I want to use my own GitHub repo to show and introduce my plugin, can I contribute my plugin to BitBar-Plugin repo?

Yes, you would be responsible for keeping them in sync
