### ISSUE TITLE
Question: How do I show submenu? I tried echo "--$USER" but it just shows --john

### ISSUE THREAD

**Issue by tomer-ben-david** [matryer/bitbar#569]
How do I show submenu? I tried echo "--$USER" but it just shows --john in menu

**Comment by frakman1** [comment]
If I understood you correctly, you just have to do this:

```bash
$cat user.sh
#!/bin/bash

echo "👤"
echo "---"
echo "menu"
echo "--"$USER
```

![image](https://user-images.githubusercontent.com/5826484/89695117-dcfc0800-d8e0-11ea-848d-c6d4758e93c0.png)
