### ISSUE TITLE
[Feature request] Colored base64 menu bar icons

### ISSUE THREAD

**Issue by JayBrown** [matryer/bitbar#574]
I know that it says on the main repo page that the menu icon "should consist of only black and clear pixels", and that "this is the recommended way to set an image for the statusbar". However, many developers (incl. Apple) don't use black & clear pixels exclusively. Furthermore, we can use colored emoji as menu bar icons.

So why are we restricting base64 menu bar icons to black & clear? Shouldn't that be our own decision whether we follow this strict rule or not?

At any rate, it is often prudent to use colored icons, e.g. you have a black & clear default icon, but if there's updated info available via the plugin, it's often a good idea to color the default icon, e.g. green or red etc., as an unobtrusive way to signal the user, instead of bombarding him with notifications.

PS: this would go fine together with changing menu bar icons on click; see here: https://github.com/matryer/bitbar/issues/573

**Comment by JayBrown** [comment]
Another alternative would be an option to colorize the menu bar icon, e.g. with

`echo "| templateImage=$menuicon color=red dropdown=false"`

**Comment by matopeto** [comment]
According to documentation, if you use `image=` instead of `templateImage` you should use color image
