### ISSUE TITLE
Big Sur menu bar text alignment is too high

### ISSUE THREAD

**Issue by tjluoma** [matryer/bitbar#575]
Under macOS version 11.0 (20A5364e) which is the latest public beta, my BitBar items are too close to the top of the menu bar.

If you use the red line as a ‘baseline’ guide, and note that the items marked in yellow are all BitBar, you can see they are higher (closer to the top / further from the bottom) than the other icons.

<img width="851" alt="BitBar On Big Sur Too High" src="https://user-images.githubusercontent.com/26965/93294491-a0ada880-f7b8-11ea-870e-8a3a42dac84b.png">

**Comment by iqandjoke** [comment]
Does #513 helps?

**Comment by tjluoma** [comment]
Grëat.

I wish I had realized that this project was effectively dead even for bug-fixes before I bothered getting involved with it.

Never should have stopped using [TextBar](http://richsomerfield.com/apps/textbar/).
