### ISSUE TITLE
How to make a clickable submenu from lines in a txt file?

### ISSUE THREAD

**Issue by relink2013** [matryer/bitbar#580]
I'm not sure where else to ask as I don't see any community forums or anything. 

I have a feeling this is simple and im overthinking it. 

Id like to make a sub menu in my Bitbar plugin. 

The sub menu should show individual lines from a text file. Each line should be its own menu item. 

When you click on a menu item, it should remove that line, and the blank space left behind from the file, and then refresh bitbar...thats pretty much it. 

MORE INFO:

To be more specific the txt file is a list of WiFi SSIDs. the Sub menu will likely read something like "Remove Other SSID" and you'd hover over it and see a list of every SSID listed in the file. When one of them is clicked, that SSID gets removed from the file, and bitbar refreshes.

**Comment by einstweilen** [comment]
1) sub menu
to create a sub menu item the line must start with `--`
When you read the SSIDs from your text file just add `--` at beginning of each print / echo command

2) remove selected items 
I have written a small BASH script (the BitBar script) to control my audio player.
The player menu has a sub menu for starting , stopping and some other functions.
`echo "--Audiostream stoppen | bash='$0' param1=stop terminal=false refresh=true color=$COLOR0"`
When a menu item is selected the script is reloaded and a parameter 'stop' is passed to the script.

At the beginning of my script I check if the script was called with a parameter 
   if [ ! -z "$1" ]; then
        case "$1" in
        start)
            some commands ...
            ;;
        stop)
            some commands ... 
            ;;
        muteads)
            some commands ...
            ;;
        *) ;;
        esac
    fi

Example:
The file 'list_of_ssids.txt' contains the SSIDs
MyNetwork
Guestnet
neighbour1
neighbour2
neighbour3

Reading the file line by line, add -- at the beginning and a call to the script with the selected SSID as parameter

#!/bin/bash
echo 'Remove Other SSID'
while read line; do
    echo "-- $line | bash='$0' param1=$line terminal=false refresh=true"
done < "list_of_ssids.txt"

output: (foo.sh is tth name of my samle script)
Remove Other SSID
-- MyNetwork | bash='./foo.sh' param1=MyNetwork terminal=false refresh=true
-- Guestnet | bash='./foo.sh' param1=Guestnet terminal=false refresh=true
-- neighbour1 | bash='./foo.sh' param1=neighbour1 terminal=false refresh=true
-- neighbour2 | bash='./foo.sh' param1=neighbour2 terminal=false refresh=true
-- neighbour3 | bash='./foo.sh' param1=neighbour3 terminal=false refresh=true

Now you have to process the passed SSID at the beginning of your script (see 2)

(this is just an example! Please add some checks before passing any input to a delete command)

   if [ ! -z "$1" ]; then
        sed -i '' "/$1/d" list_of_ssids.txt # deletes any line containig the passed SSID
   fi

If you select 'Guestnet' from the sub menu, your 'list_of_ssids.txt' will look like this:
MyNetwork
neighbour1
neighbour2
neighbour3

**Comment by relink2013** [comment]
Awesome, I just saw your comment, I will definitely give this a shot. thank you.

**Comment by relink2013** [comment]
worked perfectly. Made a few tweaks to better suit my situation, but it works beautifully. thank you.
