### ISSUE TITLE
macOS Big Sur linehight / vertical position broken

### ISSUE THREAD

**Issue by Adrian-Grimm** [matryer/bitbar#583]
On macOS Big Sur is the vertical line alignment broken and needs a adjustment.

**Comment by Adrian-Grimm** [comment]
Quick HotFix Release (until new official version): https://github.com/Adrian-Grimm/bitbar/releases/tag/v1.9.2.1

**Comment by KingOfSpades** [comment]
@Adrian-Grimm thnx for the quick fix! Looks good again on my machine.

**Comment by pincheira** [comment]
### 🙏

**Comment by idoo** [comment]
yay!

**Comment by idoo** [comment]
yay! do you have a plan to release a new version with that fix?

**Comment by mdbraber** [comment]
> yay! @matryer do you have a plan to release a new version with that fix?

Would be great to have an official update, for some reason the hotfix from @Adrian-Grimm doesn't give me access to Calendars and Reminders (which I need for my plugin), even with at `tcutil` reset

**Comment by matryer** [comment]
I hope to have some news on this by the end of the week. I’ll post an
update as soon as I can.

Mat

**Comment by Adrian-Grimm** [comment]
> Would be great to have an official update, for some reason the hotfix from @Adrian-Grimm doesn't give me access to Calendars and Reminders (which I need for my plugin), even with at `tcutil` reset

Maybe that's because I've no valid signed Apple Developer Account - affects my build ... sorry for this.

**Comment by mdbraber** [comment]
@matryer any chance you could release a notarized update?

**Comment by matryer** [comment]
@mdbraber Can you try the version at the bottom of https://github.com/matryer/bitbar/issues/590?

**Comment by mdbraber** [comment]
@matryer I've tried it - unfortunately the same problem as with the hotfix from @Adrian-Grimm in that it doesn't ask for permissions to Calendars and Reminders.

**Comment by mdbraber** [comment]
It seems my problem might have been related to a specific `icalBuddy` issue fixed here https://github.com/DavidKaluta/icalBuddy64/commit/e10ddf01143323cad642ed38e1c2f8de8041aadc
