### ISSUE TITLE
New here and confused -- help please

### ISSUE THREAD

**Issue by yanzhang0219** [matryer/bitbar#585]
Dear friends,

I am new here. I saw this repo is kinda inactive now. By reading some issue posts, I know that the author cannot put extra efforts into this repo and he is looking for contributors or someone who can take over this repo, however, I cannot get information about who has taken over this repo and whether there is an alternative repo for the continuous development?

I saw it has been 4 years since the last release, and also since then, there are still some commits on the master branch. If I want to use the latest bitbar, what is the correct way? Should I clone it and build it by myself?

Is there anyone who forked this repo and is developing it actively? Or does this repo remain active and accept new PR? I really appreciate it if someone could tell a story about bitbar and what it will be going on. Thank you so much!

**Comment by matopeto** [comment]
You can read something about it in #495

**Comment by samnunn** [comment]
I highly suggest you check out [SwiftBar](https://github.com/swiftbar/SwiftBar), the spiritual successor to BitBar.

**Comment by yanzhang0219** [comment]
@samnunn Wow!!!! I will definitely give it a shot right now! Thank you.
