### ISSUE TITLE
Release please

### ISSUE THREAD

**Issue by yanzhang0219** [matryer/bitbar#588]
Hello @matryer 
Thank you for coming back to maintain this repo. The last release is in 2016, 4 years ago already. Could you please release a new version now? Thanks.

**Comment by matryer** [comment]
Fair enough, @yanzhang0219  https://github.com/matryer/bitbar/releases/tag/v1.10.0 :)

**Comment by yanzhang0219** [comment]
Thank you very much.
BTW, will you come back to continue to maintain this repo? I remember you mentioned you want to migrate it to swift implementation. It seems so far there are still no other active maintainers here. And recently I stumbled across a strong competitor, [SwiftBar](https://github.com/swiftbar/SwiftBar).

**Comment by yanzhang0219** [comment]
Oh.. Could you please update it on homebrew as well? I saw it is still 1.9.2 there. Thank you.

**Comment by matryer** [comment]
hmm, I'm not sure I control the homebrew stuff.

Yeah SwiftBar is great. I'm advocating for the joining of the two projects.

**Comment by yanzhang0219** [comment]
Wow. You mean merge these two together? That will be great!
