### ISSUE TITLE
it runs but ...

### ISSUE THREAD

**Issue by d7eeem** [matryer/bitbar#592]
i wrote a bash script that check tautlli which is a monitor for plex media server but it only run in terminal and shows information there but not in the bar.

in terminal 
<img width="375" alt="Screen Shot 2020-12-12 at 7 06 31 PM" src="https://user-images.githubusercontent.com/35288751/101988863-8a2ac680-3cad-11eb-9d29-fe57f1d96bba.png">

in bar
<img width="248" alt="Screen Shot 2020-12-12 at 7 06 07 PM" src="https://user-images.githubusercontent.com/35288751/101988865-944cc500-3cad-11eb-8875-9f13fe2b0358.png">
```bash
Plex=$(curl -s "http://10.0.26.6:8181/api/v2?apikey=xxxxxxxxxxxxxx&cmd=get_activity" | jq -r ".response.data.stream_count")
playingNow=$(curl -s "http://10.0.26.6:8181/api/v2?apikey=xxxxxxxxxxxxx&cmd=get_activity" | jq -r ".response.data.sessions[].full_title")

Play=$(if [ -n "$playingNow" ]; then
	    echo "$playingNow"
    else
	    echo '🛑Nothing Playing'
	    fi)



echo "PlexStream"
echo "---"
echo "$Plex"
echo "$Play"
echo "---"
```
on my linux box the same strutter of the script works flawlessly

**Comment by yanzhang0219** [comment]
Seems you're using SwiftBar not BitBar. I think you posted this in the wrong place. :)
Are you using SwiftBar 1.1.0 beta? I have posted such a similar issue, i.e., running the script in terminal works fine but nothing is shown on the memubar.

**Comment by d7eeem** [comment]
> Seems you're using SwiftBar not BitBar. I think you posted this in the wrong place. :)
it seems to :)
> Are you using SwiftBar 1.1.0 beta?
no earlier version  1.0.3

**Comment by yanzhang0219** [comment]
> no earlier version 1.0.3

Okay. We don't have the same issue. :)

You can post this issue to SwiftBar and close this. The Author of SwiftBar is really nice and responsive, so he will get back to you soon.
