### ISSUE TITLE
How to stop refreshing when my MacBook is sleeping?

### ISSUE THREAD

**Issue by billzt** [matryer/bitbar#597]
I wrote a plugin by myself and the refresh time interval is 30s. However just today my MacBook's battery ran from 100% to 0% during a whole-day sleep.

After checking system log, I found thousands of such tasks like this:
```
Dec 16 11:19:22 zhutaodeMacBook-Air com.apple.xpc.launchd[1]: Coalition Cache Evicted: app<application.activateSettings.635FDDE5-192D-46F2-9B43-D060F07484C5(501)> [3697]
Dec 16 11:19:47 zhutaodeMacBook-Air BitBar[491]: Error retrieving PAC file. The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
```

Perhaps there're some bugs within my scripts (although they didn't appear before), however I really don't need BitBar refreshing when my MacBook is sleeping.

**Comment by matryer** [comment]
Strange. I wonder if your laptop didn't properly go to sleep!? I thought the operating system dealt with that.
