### ISSUE TITLE
trying to find someone to BUILD an app.. or...

### ISSUE THREAD

**Issue by fKing** [matryer/bitbar#599]
this is all way above my pay grade! i had an app (mail satellite) that showed an unread mail count in the menubar. it no longer works in big sur; am looking for something to replace it.

any thoughts? did not know how else to reach out here on github. 

if not, anyone you can point me to? will pay something if need be... miss that functionality.

**Comment by matryer** [comment]
Sorry @fKing - closing as it didn't get anyone's attention. I can't think of where might be better to ask something like this.
