### ISSUE TITLE
Auto-update application and plugins

### ISSUE THREAD

**Issue by jcaille** [matryer/bitbar#61]
What's your opinion on providing an auto-updater (such as (sparkle)[http://sparkle-project.org]) to keep both the plugins and applications up to date ?

**Comment by matryer** [comment]
I love the idea for BitBar itself - not sure about the plugins. I think if the project grows in popularity, we'll end up delivering a different way of managing plugins.

**Comment by matryer** [comment]
Plugin discussion: please move discussion to https://github.com/matryer/bitbar/issues/112

**Comment by keithamus** [comment]
@matryer you should close this issue as #112 exists.
