### ISSUE TITLE
Add BitBar to Homebrew properly

### ISSUE THREAD

**Issue by matryer** [matryer/bitbar#64]
Let's just make `brew install bitbar` work?

* see https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md

**Comment by jtokoph** [comment]
What about
$ brew cask install bitbar

**Comment by matryer** [comment]
Any ideas how we update that? Haven't used brew cask before.

**Comment by manojlds** [comment]
@matryer  - it's here - https://github.com/caskroom/homebrew-cask/blob/master/Casks/bitbar.rb

What help do you need with this?

**Comment by alexandregz** [comment]
cask is for binaries, like releases. I think is the correct way to do that.

**Comment by matryer** [comment]
OK cool. A few people have complained about this:

```
$ brew cask install bitbar
Error: Cask 'bitbar' definition is invalid: Bad header line: parse failed`
```

**Comment by npoles** [comment]
Looks like a new change to Homebrew. See here: (https://github.com/Homebrew/homebrew/issues/46850)

The solution posted there (```
brew update && brew uninstall --force brew-cask
```) worked for me.

**Comment by shopblocks** [comment]
to add to @npoles I had to do a `brew unlink cask` to get it to work

**Comment by hsavit1** [comment]
how do i go about installing plugins with home-brew?

**Comment by taylorzane** [comment]
@hsavit1 Currently you don't. I think that most people have been cloning the [bitbar-plugins](/matryer/bitbar-plugins) repo somewhere, and then using that folder as their Bitbar Plugin folder. With that setup, only plugins symlink'd to the `/Enabled` directory of the [bitbar-plugins](/matryer/bitbar-plugins) repo are active.
