### ISSUE TITLE
BitBar Doesn't Update on Assigned Schedule

### ISSUE THREAD

**Issue by rammjet** [matryer/bitbar#7]
I have a BitBar script named netstat.1m.sh.  It checks the status of the internet connection and displays either Up or Down in the menu bar.  It also logs each run of the script.

I expect the status to be updated every 1m.  But after a while, BitBar updates twice per minute - once at the 40 second mark and then again at the 20 second mark.
![bitbar](https://cloud.githubusercontent.com/assets/9166909/5331974/cf9232a6-7e10-11e4-8366-eada3603a5a5.png)

**Comment by matryer** [comment]
I think this is fixed in master - could you get the code and test it again!?

**Comment by rammjet** [comment]
Tried 1.4 beta 2.  It updates at 1 minute intervals as requested.
Thanks for the fix.
