### ISSUE TITLE
(Spotify?) text not aligned with OS X UI text

### ISSUE THREAD

**Issue by daturkel** [matryer/bitbar#72]
As you can see below, the text for the spotify plugin is not exactly vertically aligned with the OS X clock (and left-aligned menu bar items either). Not sure if this is exclusive to Spotify plugin or all text rendered via bitbar.
![](http://i.imgur.com/1QDy5dv.png)

**Comment by matryer** [comment]
Looks fine? No?

**Comment by matryer** [comment]
Oh I see

**Comment by matryer** [comment]
You are right and now it's annoying me so much.

**Comment by herdani** [comment]
Probably a duplicate with the more generic #105

**Comment by XanderLeaDaren** [comment]
Solved by @cedivad in #513 !
