### ISSUE TITLE
Separate repo for plugins

### ISSUE THREAD

**Issue by flxfxp** [matryer/bitbar#78]
As BitBar's popularity will increase, it will be handy to make the plugins a separate repo, similar to [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh). This will ensure that the commit tree won't be cluttered with plugin additions/edits and will allow community moderators to approve/reject plugins without giving access to the full BitBar project scope.

In addition it will allow users to retrieve plugin updates without checking out the entire codebase or configuring a [sparse checkout](http://stackoverflow.com/questions/600079/is-there-any-way-to-clone-a-git-repositorys-sub-directory-only/13738951#13738951).

**Comment by daturkel** [comment]
Agree with this. Admittedly, the size of the plugin repo probably won't get that big (these are scripts) but semantically it feels right and I feel like plugin requests don't belong in the issue tracker for the main repo.

**Comment by matryer** [comment]
How about I make the repos and add you guys as contributors?

**Comment by daturkel** [comment]
👍🏻

**Comment by flxfxp** [comment]
Sounds good to me :)

**Comment by seripap** [comment]
I can spiffy up a quick web interface for easier searching

**Comment by sg-s** [comment]
+1

**Comment by manojlds** [comment]
+1. Also, screenshot in plugins will be useful I think. We are putting them in PRs, but good to have them along with the plugins and README of the plugins.

**Comment by matryer** [comment]
I wonder if we could use brew or similar for plugins - to save us writing something ourselves?

**Comment by BrendanThompson** [comment]
+1

**Comment by matryer** [comment]
please move discussion to https://github.com/matryer/bitbar/issues/112

**Comment by matryer** [comment]
p.s. we now have a different repo for Plugins: https://github.com/matryer/bitbar-plugins
