### ISSUE TITLE
Search plugin folder recursively

### ISSUE THREAD

**Issue by bbrks** [matryer/bitbar#79]
Search for plugins in the selected plugin folder recursively.

This will allow organisation of plugins like the [Plugins folder](/matryer/bitbar/tree/master/Plugins) in this repository.

**Comment by luke3butler** [comment]
I rather like it not being recursive. 

Without recursion I can reference child folder scripts within my main script, but if it was recursed I'd have to put it into an alien folder.

This would be very difficult to distribute my plugin to other people.

**Comment by matryer** [comment]
Going to leave in for now until we can do something like his: https://github.com/matryer/bitbar/issues/103

**Comment by bbrks** [comment]
Sounds good!
