### ISSUE TITLE
BitBar Not Displaying Colors for Text

### ISSUE THREAD

**Issue by rammjet** [matryer/bitbar#8]
This might be a Yosemite problem.

I made a test script with only one line:
#!/bin/sh
echo "FAIL  |  color=red"

And that is exactly what gets displayed in the menu bar:  FAIL | color=red

Follow-up:  I tried with BitBar 1.0 and 1.1 on both Mavericks 10.9.4 and Yosemite 10.10.1 and no joy.

Also, the link on the homepage for the "latest" version of BitBar is for 1.0 not 1.1.

**Comment by alexbepple** [comment]
Having the same problem. .(

**Comment by jcutrell** [comment]
Seeing the same thing.

**Comment by jcutrell** [comment]
(Looks like maybe this hasn't been supported in a while though.)

**Comment by matryer** [comment]
Does anybody fancy having a go at fixing it? Otherwise, I’ll add it to my list - but not sure when I’ll be able to get round to it.

**Comment by jcutrell** [comment]
Looks like perhaps it's fixed in a fork of this project.

On Sat, Mar 28, 2015 at 1:55 PM, Mat Ryer <notifications@github.com> wrote:

> Does anybody fancy having a go at fixing it? Otherwise, I’ll add it to my
> list - but not sure when I’ll be able to get round to it.
>
> > On 28 Mar 2015, at 16:34, Jonathan Cutrell <notifications@github.com>
> wrote:
> >
> > Seeing the same thing.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/stretchr/bitbar/issues/8#issuecomment-87258930>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stretchr/bitbar/issues/8#issuecomment-87274033>.
>



-- 
Jonathan Cutrell
Director of Technology
Whiteboard | http://whiteboard.is

**Comment by rammjet** [comment]
Yes, my test script above works in app from:  https://github.com/kamenevn/bitbar

**Comment by jcutrell** [comment]
The fixes should get merged into the original project.

**Comment by matryer** [comment]
What's the best way to do that? Can someone setup a PR?

**Comment by ripienaar** [comment]
I opened https://github.com/stretchr/bitbar/pull/11 with what was 'released' in that fork, hope we can get this into the original and a official release made

**Comment by matryer** [comment]
Fixed in https://github.com/matryer/bitbar/releases/tag/v1.3.1

**Comment by ripienaar** [comment]
@matryer thanks a lot, really appreciate your work!
