### ISSUE TITLE
BitBar disappears/crashes

### ISSUE THREAD

**Issue by dasilvacontin** [matryer/bitbar#80]
Not really sure what happens. I was trying to create a plugin that uses [contrib-rocket](https://github.com/dasilvacontin/contrib-rocket). The plugin is the following:

```bash
#!/bin/bash
contrib-rocket -d 14
```

After clicking 'Reset' (or now every time I open the app), it disappears together with other menu bar icons. Can you check what's happening? Thanks.

**Comment by manojlds** [comment]
Isn't the output of `contrib-rocket` too long? BitBar disappears if the text is too long

**Comment by dasilvacontin** [comment]
@manojlds what's the max? I didn't know about that. (It can be controlled with the `-d` arg)

**Comment by dasilvacontin** [comment]
Changed it to `-d 7`(which outputs eg █▁▁▁▁▁▄🚀), and nothing. Btw, output takes some ms, since a request is made to a server. (worth noting I guess)

**Comment by manojlds** [comment]
@dasilvacontin you are author of it right? I see a bug in the script. Please check this PR - https://github.com/dasilvacontin/contrib-rocket/pull/4

**Comment by manojlds** [comment]
Tried this and works:

```bash
#!/bin/bash
echo "▁🚀"
```

Actual script doesn't work.

**Comment by manojlds** [comment]
Ok, this works:
```bash
#!/bin/bash
export PATH='/usr/local/bin:/usr/bin:/bin:$PATH'
echo "contrib"
echo "---"
contrib-rocket -d 1
```

@matryer  can pitch in. Should the first text not take time to be echoed? (not looked at the code for BitBar)

**Comment by manojlds** [comment]
Nope, I just had to wait, the following works. The main issue was the PATH handling:

```bash
#!/bin/bash
export PATH='/usr/local/bin:/usr/bin:/bin:$PATH'
contrib-rocket -d 1
```

**Comment by manojlds** [comment]
This is cool :)
<img width="136" alt="screen shot 2016-01-06 at 12 24 45 am" src="https://cloud.githubusercontent.com/assets/191378/12124526/eb84fc1e-b40b-11e5-8f4c-e31d49c78bdb.png">

**Comment by dasilvacontin** [comment]
@manojlds Thanks :) I see, PATH was the issue, thanks much. ;)
