### ISSUE TITLE
Feature request: Preference to refresh plugin folder

### ISSUE THREAD

**Issue by daturkel** [matryer/bitbar#82]
Currently, if I want to make bitbar re-check my plugin folder, I have to click Change Plugin Folder... and select the folder currently in use. It would be nice if there were a button to simply re-check the currently active plugin folder.

**Comment by matryer** [comment]
`Preferences > Reset` should do what you’re looking for.

**Comment by daturkel** [comment]
Ah how obvious! Maybe change text to "refresh"? Reset to me carries connotation of loss of preferences.

**Comment by matryer** [comment]
Yeah that seems reasonable.
