### ISSUE TITLE
github.io page with screenshot gallery

### ISSUE THREAD

**Issue by tomkinsc** [matryer/bitbar#95]
It is wonderful to have so many amazing plugins! As the project grows, it will take time to examine the source of each one to determine how it functions and whether it is worth trying. It would help discoverability to have a github.io page with a screenshot or two for each plugin, demonstrating the functionality. Having a central page like this (with links to the raw plugin files, of course) would make it easy to find great new plugins. The screenshots can probably be taken from pull requests that include them.

**Comment by manojlds** [comment]
+1 to this. Too many feature requests, should start triaging them :)

**Comment by matryer** [comment]
please move discussion to https://github.com/matryer/bitbar/issues/112
